// This file was created by the AIR team.

use crate::components::prelude::*;

pub const RELATION_USES_PER_ROW: [RelationUse; 8] = [
    RelationUse { relation_id: "RangeCheck_9_9", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_B", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_C", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_D", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_E", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_F", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_G", uses: 1 },
    RelationUse { relation_id: "RangeCheck_9_9_H", uses: 1 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints<Value: IValue>(
    input: &[Var],
    context: &mut Context<Value>,
    component_data: &dyn ComponentDataTrait<Value>,
    acc: &mut CompositionConstraintAccumulator,
) -> Vec<Var> {
    let [
        add_252_input_a_limb_0,
        add_252_input_a_limb_1,
        add_252_input_a_limb_2,
        add_252_input_a_limb_3,
        add_252_input_a_limb_4,
        add_252_input_a_limb_5,
        add_252_input_a_limb_6,
        add_252_input_a_limb_7,
        add_252_input_a_limb_8,
        add_252_input_a_limb_9,
        add_252_input_a_limb_10,
        add_252_input_a_limb_11,
        add_252_input_a_limb_12,
        add_252_input_a_limb_13,
        add_252_input_a_limb_14,
        add_252_input_a_limb_15,
        add_252_input_a_limb_16,
        add_252_input_a_limb_17,
        add_252_input_a_limb_18,
        add_252_input_a_limb_19,
        add_252_input_a_limb_20,
        add_252_input_a_limb_21,
        add_252_input_a_limb_22,
        add_252_input_a_limb_23,
        add_252_input_a_limb_24,
        add_252_input_a_limb_25,
        add_252_input_a_limb_26,
        add_252_input_a_limb_27,
        add_252_input_b_limb_0,
        add_252_input_b_limb_1,
        add_252_input_b_limb_2,
        add_252_input_b_limb_3,
        add_252_input_b_limb_4,
        add_252_input_b_limb_5,
        add_252_input_b_limb_6,
        add_252_input_b_limb_7,
        add_252_input_b_limb_8,
        add_252_input_b_limb_9,
        add_252_input_b_limb_10,
        add_252_input_b_limb_11,
        add_252_input_b_limb_12,
        add_252_input_b_limb_13,
        add_252_input_b_limb_14,
        add_252_input_b_limb_15,
        add_252_input_b_limb_16,
        add_252_input_b_limb_17,
        add_252_input_b_limb_18,
        add_252_input_b_limb_19,
        add_252_input_b_limb_20,
        add_252_input_b_limb_21,
        add_252_input_b_limb_22,
        add_252_input_b_limb_23,
        add_252_input_b_limb_24,
        add_252_input_b_limb_25,
        add_252_input_b_limb_26,
        add_252_input_b_limb_27,
        add_res_limb_0_col0,
        add_res_limb_1_col1,
        add_res_limb_2_col2,
        add_res_limb_3_col3,
        add_res_limb_4_col4,
        add_res_limb_5_col5,
        add_res_limb_6_col6,
        add_res_limb_7_col7,
        add_res_limb_8_col8,
        add_res_limb_9_col9,
        add_res_limb_10_col10,
        add_res_limb_11_col11,
        add_res_limb_12_col12,
        add_res_limb_13_col13,
        add_res_limb_14_col14,
        add_res_limb_15_col15,
        add_res_limb_16_col16,
        add_res_limb_17_col17,
        add_res_limb_18_col18,
        add_res_limb_19_col19,
        add_res_limb_20_col20,
        add_res_limb_21_col21,
        add_res_limb_22_col22,
        add_res_limb_23_col23,
        add_res_limb_24_col24,
        add_res_limb_25_col25,
        add_res_limb_26_col26,
        add_res_limb_27_col27,
        sub_p_bit_col28,
    ] = input.try_into().unwrap();

    range_check_mem_value_n_28::accumulate_constraints(
        &[
            eval!(context, add_res_limb_0_col0),
            eval!(context, add_res_limb_1_col1),
            eval!(context, add_res_limb_2_col2),
            eval!(context, add_res_limb_3_col3),
            eval!(context, add_res_limb_4_col4),
            eval!(context, add_res_limb_5_col5),
            eval!(context, add_res_limb_6_col6),
            eval!(context, add_res_limb_7_col7),
            eval!(context, add_res_limb_8_col8),
            eval!(context, add_res_limb_9_col9),
            eval!(context, add_res_limb_10_col10),
            eval!(context, add_res_limb_11_col11),
            eval!(context, add_res_limb_12_col12),
            eval!(context, add_res_limb_13_col13),
            eval!(context, add_res_limb_14_col14),
            eval!(context, add_res_limb_15_col15),
            eval!(context, add_res_limb_16_col16),
            eval!(context, add_res_limb_17_col17),
            eval!(context, add_res_limb_18_col18),
            eval!(context, add_res_limb_19_col19),
            eval!(context, add_res_limb_20_col20),
            eval!(context, add_res_limb_21_col21),
            eval!(context, add_res_limb_22_col22),
            eval!(context, add_res_limb_23_col23),
            eval!(context, add_res_limb_24_col24),
            eval!(context, add_res_limb_25_col25),
            eval!(context, add_res_limb_26_col26),
            eval!(context, add_res_limb_27_col27),
        ],
        context,
        component_data,
        acc,
    );

    verify_add_252::accumulate_constraints(
        &[
            eval!(context, add_252_input_a_limb_0),
            eval!(context, add_252_input_a_limb_1),
            eval!(context, add_252_input_a_limb_2),
            eval!(context, add_252_input_a_limb_3),
            eval!(context, add_252_input_a_limb_4),
            eval!(context, add_252_input_a_limb_5),
            eval!(context, add_252_input_a_limb_6),
            eval!(context, add_252_input_a_limb_7),
            eval!(context, add_252_input_a_limb_8),
            eval!(context, add_252_input_a_limb_9),
            eval!(context, add_252_input_a_limb_10),
            eval!(context, add_252_input_a_limb_11),
            eval!(context, add_252_input_a_limb_12),
            eval!(context, add_252_input_a_limb_13),
            eval!(context, add_252_input_a_limb_14),
            eval!(context, add_252_input_a_limb_15),
            eval!(context, add_252_input_a_limb_16),
            eval!(context, add_252_input_a_limb_17),
            eval!(context, add_252_input_a_limb_18),
            eval!(context, add_252_input_a_limb_19),
            eval!(context, add_252_input_a_limb_20),
            eval!(context, add_252_input_a_limb_21),
            eval!(context, add_252_input_a_limb_22),
            eval!(context, add_252_input_a_limb_23),
            eval!(context, add_252_input_a_limb_24),
            eval!(context, add_252_input_a_limb_25),
            eval!(context, add_252_input_a_limb_26),
            eval!(context, add_252_input_a_limb_27),
            eval!(context, add_252_input_b_limb_0),
            eval!(context, add_252_input_b_limb_1),
            eval!(context, add_252_input_b_limb_2),
            eval!(context, add_252_input_b_limb_3),
            eval!(context, add_252_input_b_limb_4),
            eval!(context, add_252_input_b_limb_5),
            eval!(context, add_252_input_b_limb_6),
            eval!(context, add_252_input_b_limb_7),
            eval!(context, add_252_input_b_limb_8),
            eval!(context, add_252_input_b_limb_9),
            eval!(context, add_252_input_b_limb_10),
            eval!(context, add_252_input_b_limb_11),
            eval!(context, add_252_input_b_limb_12),
            eval!(context, add_252_input_b_limb_13),
            eval!(context, add_252_input_b_limb_14),
            eval!(context, add_252_input_b_limb_15),
            eval!(context, add_252_input_b_limb_16),
            eval!(context, add_252_input_b_limb_17),
            eval!(context, add_252_input_b_limb_18),
            eval!(context, add_252_input_b_limb_19),
            eval!(context, add_252_input_b_limb_20),
            eval!(context, add_252_input_b_limb_21),
            eval!(context, add_252_input_b_limb_22),
            eval!(context, add_252_input_b_limb_23),
            eval!(context, add_252_input_b_limb_24),
            eval!(context, add_252_input_b_limb_25),
            eval!(context, add_252_input_b_limb_26),
            eval!(context, add_252_input_b_limb_27),
            eval!(context, add_res_limb_0_col0),
            eval!(context, add_res_limb_1_col1),
            eval!(context, add_res_limb_2_col2),
            eval!(context, add_res_limb_3_col3),
            eval!(context, add_res_limb_4_col4),
            eval!(context, add_res_limb_5_col5),
            eval!(context, add_res_limb_6_col6),
            eval!(context, add_res_limb_7_col7),
            eval!(context, add_res_limb_8_col8),
            eval!(context, add_res_limb_9_col9),
            eval!(context, add_res_limb_10_col10),
            eval!(context, add_res_limb_11_col11),
            eval!(context, add_res_limb_12_col12),
            eval!(context, add_res_limb_13_col13),
            eval!(context, add_res_limb_14_col14),
            eval!(context, add_res_limb_15_col15),
            eval!(context, add_res_limb_16_col16),
            eval!(context, add_res_limb_17_col17),
            eval!(context, add_res_limb_18_col18),
            eval!(context, add_res_limb_19_col19),
            eval!(context, add_res_limb_20_col20),
            eval!(context, add_res_limb_21_col21),
            eval!(context, add_res_limb_22_col22),
            eval!(context, add_res_limb_23_col23),
            eval!(context, add_res_limb_24_col24),
            eval!(context, add_res_limb_25_col25),
            eval!(context, add_res_limb_26_col26),
            eval!(context, add_res_limb_27_col27),
            eval!(context, sub_p_bit_col28),
        ],
        context,
        component_data,
        acc,
    );
    vec![]
}
