// This file was created by the AIR team.

use crate::components::prelude::*;

pub const RELATION_USES_PER_ROW: [RelationUse; 4] = [
    RelationUse { relation_id: "Cube252", uses: 1 },
    RelationUse { relation_id: "RangeCheck252Width27", uses: 1 },
    RelationUse { relation_id: "RangeCheck_4_4", uses: 1 },
    RelationUse { relation_id: "RangeCheck_4_4_4_4", uses: 2 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints<Value: IValue>(
    input: &[Var],
    context: &mut Context<Value>,
    component_data: &dyn ComponentDataTrait<Value>,
    acc: &mut CompositionConstraintAccumulator,
) -> Vec<Var> {
    let [
        poseidon_partial_round_input_z0_3_limb_0,
        poseidon_partial_round_input_z0_3_limb_1,
        poseidon_partial_round_input_z0_3_limb_2,
        poseidon_partial_round_input_z0_3_limb_3,
        poseidon_partial_round_input_z0_3_limb_4,
        poseidon_partial_round_input_z0_3_limb_5,
        poseidon_partial_round_input_z0_3_limb_6,
        poseidon_partial_round_input_z0_3_limb_7,
        poseidon_partial_round_input_z0_3_limb_8,
        poseidon_partial_round_input_z0_3_limb_9,
        poseidon_partial_round_input_z1_limb_0,
        poseidon_partial_round_input_z1_limb_1,
        poseidon_partial_round_input_z1_limb_2,
        poseidon_partial_round_input_z1_limb_3,
        poseidon_partial_round_input_z1_limb_4,
        poseidon_partial_round_input_z1_limb_5,
        poseidon_partial_round_input_z1_limb_6,
        poseidon_partial_round_input_z1_limb_7,
        poseidon_partial_round_input_z1_limb_8,
        poseidon_partial_round_input_z1_limb_9,
        poseidon_partial_round_input_z1_3_limb_0,
        poseidon_partial_round_input_z1_3_limb_1,
        poseidon_partial_round_input_z1_3_limb_2,
        poseidon_partial_round_input_z1_3_limb_3,
        poseidon_partial_round_input_z1_3_limb_4,
        poseidon_partial_round_input_z1_3_limb_5,
        poseidon_partial_round_input_z1_3_limb_6,
        poseidon_partial_round_input_z1_3_limb_7,
        poseidon_partial_round_input_z1_3_limb_8,
        poseidon_partial_round_input_z1_3_limb_9,
        poseidon_partial_round_input_z2_limb_0,
        poseidon_partial_round_input_z2_limb_1,
        poseidon_partial_round_input_z2_limb_2,
        poseidon_partial_round_input_z2_limb_3,
        poseidon_partial_round_input_z2_limb_4,
        poseidon_partial_round_input_z2_limb_5,
        poseidon_partial_round_input_z2_limb_6,
        poseidon_partial_round_input_z2_limb_7,
        poseidon_partial_round_input_z2_limb_8,
        poseidon_partial_round_input_z2_limb_9,
        poseidon_partial_round_input_half_key_limb_0,
        poseidon_partial_round_input_half_key_limb_1,
        poseidon_partial_round_input_half_key_limb_2,
        poseidon_partial_round_input_half_key_limb_3,
        poseidon_partial_round_input_half_key_limb_4,
        poseidon_partial_round_input_half_key_limb_5,
        poseidon_partial_round_input_half_key_limb_6,
        poseidon_partial_round_input_half_key_limb_7,
        poseidon_partial_round_input_half_key_limb_8,
        poseidon_partial_round_input_half_key_limb_9,
        cube_252_output_limb_0_col0,
        cube_252_output_limb_1_col1,
        cube_252_output_limb_2_col2,
        cube_252_output_limb_3_col3,
        cube_252_output_limb_4_col4,
        cube_252_output_limb_5_col5,
        cube_252_output_limb_6_col6,
        cube_252_output_limb_7_col7,
        cube_252_output_limb_8_col8,
        cube_252_output_limb_9_col9,
        combination_limb_0_col10,
        combination_limb_1_col11,
        combination_limb_2_col12,
        combination_limb_3_col13,
        combination_limb_4_col14,
        combination_limb_5_col15,
        combination_limb_6_col16,
        combination_limb_7_col17,
        combination_limb_8_col18,
        combination_limb_9_col19,
        p_coef_col20,
        combination_limb_0_col21,
        combination_limb_1_col22,
        combination_limb_2_col23,
        combination_limb_3_col24,
        combination_limb_4_col25,
        combination_limb_5_col26,
        combination_limb_6_col27,
        combination_limb_7_col28,
        combination_limb_8_col29,
        combination_limb_9_col30,
        p_coef_col31,
    ] = input.try_into().unwrap();

    // Use Cube252.
    let tuple_0 = &[
        eval!(context, 1987997202),
        eval!(context, poseidon_partial_round_input_z2_limb_0),
        eval!(context, poseidon_partial_round_input_z2_limb_1),
        eval!(context, poseidon_partial_round_input_z2_limb_2),
        eval!(context, poseidon_partial_round_input_z2_limb_3),
        eval!(context, poseidon_partial_round_input_z2_limb_4),
        eval!(context, poseidon_partial_round_input_z2_limb_5),
        eval!(context, poseidon_partial_round_input_z2_limb_6),
        eval!(context, poseidon_partial_round_input_z2_limb_7),
        eval!(context, poseidon_partial_round_input_z2_limb_8),
        eval!(context, poseidon_partial_round_input_z2_limb_9),
        eval!(context, cube_252_output_limb_0_col0),
        eval!(context, cube_252_output_limb_1_col1),
        eval!(context, cube_252_output_limb_2_col2),
        eval!(context, cube_252_output_limb_3_col3),
        eval!(context, cube_252_output_limb_4_col4),
        eval!(context, cube_252_output_limb_5_col5),
        eval!(context, cube_252_output_limb_6_col6),
        eval!(context, cube_252_output_limb_7_col7),
        eval!(context, cube_252_output_limb_8_col8),
        eval!(context, cube_252_output_limb_9_col9),
    ];
    let numerator_0 = eval!(context, 1);
    acc.add_to_relation(context, numerator_0, tuple_0);

    linear_combination_n_6_coefs_4_2_3_1_m1_1::accumulate_constraints(
        &[
            eval!(context, poseidon_partial_round_input_z0_3_limb_0),
            eval!(context, poseidon_partial_round_input_z0_3_limb_1),
            eval!(context, poseidon_partial_round_input_z0_3_limb_2),
            eval!(context, poseidon_partial_round_input_z0_3_limb_3),
            eval!(context, poseidon_partial_round_input_z0_3_limb_4),
            eval!(context, poseidon_partial_round_input_z0_3_limb_5),
            eval!(context, poseidon_partial_round_input_z0_3_limb_6),
            eval!(context, poseidon_partial_round_input_z0_3_limb_7),
            eval!(context, poseidon_partial_round_input_z0_3_limb_8),
            eval!(context, poseidon_partial_round_input_z0_3_limb_9),
            eval!(context, poseidon_partial_round_input_z1_limb_0),
            eval!(context, poseidon_partial_round_input_z1_limb_1),
            eval!(context, poseidon_partial_round_input_z1_limb_2),
            eval!(context, poseidon_partial_round_input_z1_limb_3),
            eval!(context, poseidon_partial_round_input_z1_limb_4),
            eval!(context, poseidon_partial_round_input_z1_limb_5),
            eval!(context, poseidon_partial_round_input_z1_limb_6),
            eval!(context, poseidon_partial_round_input_z1_limb_7),
            eval!(context, poseidon_partial_round_input_z1_limb_8),
            eval!(context, poseidon_partial_round_input_z1_limb_9),
            eval!(context, poseidon_partial_round_input_z1_3_limb_0),
            eval!(context, poseidon_partial_round_input_z1_3_limb_1),
            eval!(context, poseidon_partial_round_input_z1_3_limb_2),
            eval!(context, poseidon_partial_round_input_z1_3_limb_3),
            eval!(context, poseidon_partial_round_input_z1_3_limb_4),
            eval!(context, poseidon_partial_round_input_z1_3_limb_5),
            eval!(context, poseidon_partial_round_input_z1_3_limb_6),
            eval!(context, poseidon_partial_round_input_z1_3_limb_7),
            eval!(context, poseidon_partial_round_input_z1_3_limb_8),
            eval!(context, poseidon_partial_round_input_z1_3_limb_9),
            eval!(context, poseidon_partial_round_input_z2_limb_0),
            eval!(context, poseidon_partial_round_input_z2_limb_1),
            eval!(context, poseidon_partial_round_input_z2_limb_2),
            eval!(context, poseidon_partial_round_input_z2_limb_3),
            eval!(context, poseidon_partial_round_input_z2_limb_4),
            eval!(context, poseidon_partial_round_input_z2_limb_5),
            eval!(context, poseidon_partial_round_input_z2_limb_6),
            eval!(context, poseidon_partial_round_input_z2_limb_7),
            eval!(context, poseidon_partial_round_input_z2_limb_8),
            eval!(context, poseidon_partial_round_input_z2_limb_9),
            eval!(context, cube_252_output_limb_0_col0),
            eval!(context, cube_252_output_limb_1_col1),
            eval!(context, cube_252_output_limb_2_col2),
            eval!(context, cube_252_output_limb_3_col3),
            eval!(context, cube_252_output_limb_4_col4),
            eval!(context, cube_252_output_limb_5_col5),
            eval!(context, cube_252_output_limb_6_col6),
            eval!(context, cube_252_output_limb_7_col7),
            eval!(context, cube_252_output_limb_8_col8),
            eval!(context, cube_252_output_limb_9_col9),
            eval!(context, poseidon_partial_round_input_half_key_limb_0),
            eval!(context, poseidon_partial_round_input_half_key_limb_1),
            eval!(context, poseidon_partial_round_input_half_key_limb_2),
            eval!(context, poseidon_partial_round_input_half_key_limb_3),
            eval!(context, poseidon_partial_round_input_half_key_limb_4),
            eval!(context, poseidon_partial_round_input_half_key_limb_5),
            eval!(context, poseidon_partial_round_input_half_key_limb_6),
            eval!(context, poseidon_partial_round_input_half_key_limb_7),
            eval!(context, poseidon_partial_round_input_half_key_limb_8),
            eval!(context, poseidon_partial_round_input_half_key_limb_9),
            eval!(context, combination_limb_0_col10),
            eval!(context, combination_limb_1_col11),
            eval!(context, combination_limb_2_col12),
            eval!(context, combination_limb_3_col13),
            eval!(context, combination_limb_4_col14),
            eval!(context, combination_limb_5_col15),
            eval!(context, combination_limb_6_col16),
            eval!(context, combination_limb_7_col17),
            eval!(context, combination_limb_8_col18),
            eval!(context, combination_limb_9_col19),
            eval!(context, p_coef_col20),
        ],
        context,
        component_data,
        acc,
    );

    // Use RangeCheck252Width27.
    let tuple_2 = &[
        eval!(context, 1090315331),
        eval!(context, combination_limb_0_col10),
        eval!(context, combination_limb_1_col11),
        eval!(context, combination_limb_2_col12),
        eval!(context, combination_limb_3_col13),
        eval!(context, combination_limb_4_col14),
        eval!(context, combination_limb_5_col15),
        eval!(context, combination_limb_6_col16),
        eval!(context, combination_limb_7_col17),
        eval!(context, combination_limb_8_col18),
        eval!(context, combination_limb_9_col19),
    ];
    let numerator_2 = eval!(context, 1);
    acc.add_to_relation(context, numerator_2, tuple_2);

    linear_combination_n_1_coefs_2::accumulate_constraints(
        &[
            eval!(context, combination_limb_0_col10),
            eval!(context, combination_limb_1_col11),
            eval!(context, combination_limb_2_col12),
            eval!(context, combination_limb_3_col13),
            eval!(context, combination_limb_4_col14),
            eval!(context, combination_limb_5_col15),
            eval!(context, combination_limb_6_col16),
            eval!(context, combination_limb_7_col17),
            eval!(context, combination_limb_8_col18),
            eval!(context, combination_limb_9_col19),
            eval!(context, combination_limb_0_col21),
            eval!(context, combination_limb_1_col22),
            eval!(context, combination_limb_2_col23),
            eval!(context, combination_limb_3_col24),
            eval!(context, combination_limb_4_col25),
            eval!(context, combination_limb_5_col26),
            eval!(context, combination_limb_6_col27),
            eval!(context, combination_limb_7_col28),
            eval!(context, combination_limb_8_col29),
            eval!(context, combination_limb_9_col30),
            eval!(context, p_coef_col31),
        ],
        context,
        component_data,
        acc,
    );
    vec![]
}
