// This file was created by the AIR team.

use crate::cairo_air::components::prelude::*;

pub const N_TRACE_COLUMNS: usize = 174;
pub const N_INTERACTION_COLUMNS: usize = 148;

pub const RELATION_USES_PER_ROW: [RelationUse; 8] = [
    RelationUse { relation_id: "BlakeRound", uses: 1 },
    RelationUse { relation_id: "MemoryAddressToId", uses: 20 },
    RelationUse { relation_id: "MemoryIdToBig", uses: 20 },
    RelationUse { relation_id: "Opcodes", uses: 1 },
    RelationUse { relation_id: "RangeCheck_7_2_5", uses: 17 },
    RelationUse { relation_id: "TripleXor32", uses: 8 },
    RelationUse { relation_id: "VerifyBitwiseXor_8", uses: 4 },
    RelationUse { relation_id: "VerifyInstruction", uses: 1 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints(
    input: &[Var],
    context: &mut Context<impl IValue>,
    component_data: &ComponentData<'_>,
    acc: &mut CompositionConstraintAccumulator,
) {
    let _ = component_data;
    let _ = acc;
    let [
        input_pc_col0,
        input_ap_col1,
        input_fp_col2,
        offset0_col3,
        offset1_col4,
        offset2_col5,
        dst_base_fp_col6,
        op0_base_fp_col7,
        op1_base_fp_col8,
        ap_update_add_1_col9,
        opcode_extension_col10,
        mem0_base_col11,
        op0_id_col12,
        op0_limb_0_col13,
        op0_limb_1_col14,
        op0_limb_2_col15,
        op0_limb_3_col16,
        partial_limb_msb_col17,
        mem1_base_col18,
        op1_id_col19,
        op1_limb_0_col20,
        op1_limb_1_col21,
        op1_limb_2_col22,
        op1_limb_3_col23,
        partial_limb_msb_col24,
        ap_id_col25,
        ap_limb_0_col26,
        ap_limb_1_col27,
        ap_limb_2_col28,
        ap_limb_3_col29,
        partial_limb_msb_col30,
        mem_dst_base_col31,
        low_16_bits_col32,
        high_16_bits_col33,
        low_7_ms_bits_col34,
        high_14_ms_bits_col35,
        high_5_ms_bits_col36,
        dst_id_col37,
        low_16_bits_col38,
        high_16_bits_col39,
        low_7_ms_bits_col40,
        high_14_ms_bits_col41,
        high_5_ms_bits_col42,
        state_0_id_col43,
        low_16_bits_col44,
        high_16_bits_col45,
        low_7_ms_bits_col46,
        high_14_ms_bits_col47,
        high_5_ms_bits_col48,
        state_1_id_col49,
        low_16_bits_col50,
        high_16_bits_col51,
        low_7_ms_bits_col52,
        high_14_ms_bits_col53,
        high_5_ms_bits_col54,
        state_2_id_col55,
        low_16_bits_col56,
        high_16_bits_col57,
        low_7_ms_bits_col58,
        high_14_ms_bits_col59,
        high_5_ms_bits_col60,
        state_3_id_col61,
        low_16_bits_col62,
        high_16_bits_col63,
        low_7_ms_bits_col64,
        high_14_ms_bits_col65,
        high_5_ms_bits_col66,
        state_4_id_col67,
        low_16_bits_col68,
        high_16_bits_col69,
        low_7_ms_bits_col70,
        high_14_ms_bits_col71,
        high_5_ms_bits_col72,
        state_5_id_col73,
        low_16_bits_col74,
        high_16_bits_col75,
        low_7_ms_bits_col76,
        high_14_ms_bits_col77,
        high_5_ms_bits_col78,
        state_6_id_col79,
        low_16_bits_col80,
        high_16_bits_col81,
        low_7_ms_bits_col82,
        high_14_ms_bits_col83,
        high_5_ms_bits_col84,
        state_7_id_col85,
        ms_8_bits_col86,
        ms_8_bits_col87,
        xor_col88,
        xor_col89,
        xor_col90,
        xor_col91,
        blake_round_output_limb_0_col92,
        blake_round_output_limb_1_col93,
        blake_round_output_limb_2_col94,
        blake_round_output_limb_3_col95,
        blake_round_output_limb_4_col96,
        blake_round_output_limb_5_col97,
        blake_round_output_limb_6_col98,
        blake_round_output_limb_7_col99,
        blake_round_output_limb_8_col100,
        blake_round_output_limb_9_col101,
        blake_round_output_limb_10_col102,
        blake_round_output_limb_11_col103,
        blake_round_output_limb_12_col104,
        blake_round_output_limb_13_col105,
        blake_round_output_limb_14_col106,
        blake_round_output_limb_15_col107,
        blake_round_output_limb_16_col108,
        blake_round_output_limb_17_col109,
        blake_round_output_limb_18_col110,
        blake_round_output_limb_19_col111,
        blake_round_output_limb_20_col112,
        blake_round_output_limb_21_col113,
        blake_round_output_limb_22_col114,
        blake_round_output_limb_23_col115,
        blake_round_output_limb_24_col116,
        blake_round_output_limb_25_col117,
        blake_round_output_limb_26_col118,
        blake_round_output_limb_27_col119,
        blake_round_output_limb_28_col120,
        blake_round_output_limb_29_col121,
        blake_round_output_limb_30_col122,
        blake_round_output_limb_31_col123,
        blake_round_output_limb_32_col124,
        triple_xor_32_output_limb_0_col125,
        triple_xor_32_output_limb_1_col126,
        triple_xor_32_output_limb_0_col127,
        triple_xor_32_output_limb_1_col128,
        triple_xor_32_output_limb_0_col129,
        triple_xor_32_output_limb_1_col130,
        triple_xor_32_output_limb_0_col131,
        triple_xor_32_output_limb_1_col132,
        triple_xor_32_output_limb_0_col133,
        triple_xor_32_output_limb_1_col134,
        triple_xor_32_output_limb_0_col135,
        triple_xor_32_output_limb_1_col136,
        triple_xor_32_output_limb_0_col137,
        triple_xor_32_output_limb_1_col138,
        triple_xor_32_output_limb_0_col139,
        triple_xor_32_output_limb_1_col140,
        low_7_ms_bits_col141,
        high_14_ms_bits_col142,
        high_5_ms_bits_col143,
        new_state_0_id_col144,
        low_7_ms_bits_col145,
        high_14_ms_bits_col146,
        high_5_ms_bits_col147,
        new_state_1_id_col148,
        low_7_ms_bits_col149,
        high_14_ms_bits_col150,
        high_5_ms_bits_col151,
        new_state_2_id_col152,
        low_7_ms_bits_col153,
        high_14_ms_bits_col154,
        high_5_ms_bits_col155,
        new_state_3_id_col156,
        low_7_ms_bits_col157,
        high_14_ms_bits_col158,
        high_5_ms_bits_col159,
        new_state_4_id_col160,
        low_7_ms_bits_col161,
        high_14_ms_bits_col162,
        high_5_ms_bits_col163,
        new_state_5_id_col164,
        low_7_ms_bits_col165,
        high_14_ms_bits_col166,
        high_5_ms_bits_col167,
        new_state_6_id_col168,
        low_7_ms_bits_col169,
        high_14_ms_bits_col170,
        high_5_ms_bits_col171,
        new_state_7_id_col172,
        enabler,
    ] = input.try_into().unwrap();
    let seq = seq_of_component_size(context, component_data, acc);
    let enabler_constraint_value = eval!(context, ((enabler) * (enabler)) - (enabler));
    acc.add_constraint(context, enabler_constraint_value);

    let [
        decode_blake_opcode_output_tmp_53f39_42_limb_0,
        decode_blake_opcode_output_tmp_53f39_42_limb_1,
        decode_blake_opcode_output_tmp_53f39_42_limb_2,
        decode_blake_opcode_output_tmp_53f39_42_limb_6,
    ] = decode_blake_opcode::accumulate_constraints(
        &[
            eval!(context, input_pc_col0),
            eval!(context, input_ap_col1),
            eval!(context, input_fp_col2),
            eval!(context, offset0_col3),
            eval!(context, offset1_col4),
            eval!(context, offset2_col5),
            eval!(context, dst_base_fp_col6),
            eval!(context, op0_base_fp_col7),
            eval!(context, op1_base_fp_col8),
            eval!(context, ap_update_add_1_col9),
            eval!(context, opcode_extension_col10),
            eval!(context, mem0_base_col11),
            eval!(context, op0_id_col12),
            eval!(context, op0_limb_0_col13),
            eval!(context, op0_limb_1_col14),
            eval!(context, op0_limb_2_col15),
            eval!(context, op0_limb_3_col16),
            eval!(context, partial_limb_msb_col17),
            eval!(context, mem1_base_col18),
            eval!(context, op1_id_col19),
            eval!(context, op1_limb_0_col20),
            eval!(context, op1_limb_1_col21),
            eval!(context, op1_limb_2_col22),
            eval!(context, op1_limb_3_col23),
            eval!(context, partial_limb_msb_col24),
            eval!(context, ap_id_col25),
            eval!(context, ap_limb_0_col26),
            eval!(context, ap_limb_1_col27),
            eval!(context, ap_limb_2_col28),
            eval!(context, ap_limb_3_col29),
            eval!(context, partial_limb_msb_col30),
            eval!(context, mem_dst_base_col31),
            eval!(context, low_16_bits_col32),
            eval!(context, high_16_bits_col33),
            eval!(context, low_7_ms_bits_col34),
            eval!(context, high_14_ms_bits_col35),
            eval!(context, high_5_ms_bits_col36),
            eval!(context, dst_id_col37),
        ],
        context,
        component_data,
        acc,
    )
    .try_into()
    .unwrap();

    let [
        create_blake_round_input_output_tmp_53f39_143_limb_24,
        create_blake_round_input_output_tmp_53f39_143_limb_25,
        create_blake_round_input_output_tmp_53f39_143_limb_28,
        create_blake_round_input_output_tmp_53f39_143_limb_29,
    ] = create_blake_round_input::accumulate_constraints(
        &[
            eval!(context, decode_blake_opcode_output_tmp_53f39_42_limb_0),
            eval!(context, low_16_bits_col32),
            eval!(context, high_16_bits_col33),
            eval!(context, decode_blake_opcode_output_tmp_53f39_42_limb_6),
            eval!(context, low_16_bits_col38),
            eval!(context, high_16_bits_col39),
            eval!(context, low_7_ms_bits_col40),
            eval!(context, high_14_ms_bits_col41),
            eval!(context, high_5_ms_bits_col42),
            eval!(context, state_0_id_col43),
            eval!(context, low_16_bits_col44),
            eval!(context, high_16_bits_col45),
            eval!(context, low_7_ms_bits_col46),
            eval!(context, high_14_ms_bits_col47),
            eval!(context, high_5_ms_bits_col48),
            eval!(context, state_1_id_col49),
            eval!(context, low_16_bits_col50),
            eval!(context, high_16_bits_col51),
            eval!(context, low_7_ms_bits_col52),
            eval!(context, high_14_ms_bits_col53),
            eval!(context, high_5_ms_bits_col54),
            eval!(context, state_2_id_col55),
            eval!(context, low_16_bits_col56),
            eval!(context, high_16_bits_col57),
            eval!(context, low_7_ms_bits_col58),
            eval!(context, high_14_ms_bits_col59),
            eval!(context, high_5_ms_bits_col60),
            eval!(context, state_3_id_col61),
            eval!(context, low_16_bits_col62),
            eval!(context, high_16_bits_col63),
            eval!(context, low_7_ms_bits_col64),
            eval!(context, high_14_ms_bits_col65),
            eval!(context, high_5_ms_bits_col66),
            eval!(context, state_4_id_col67),
            eval!(context, low_16_bits_col68),
            eval!(context, high_16_bits_col69),
            eval!(context, low_7_ms_bits_col70),
            eval!(context, high_14_ms_bits_col71),
            eval!(context, high_5_ms_bits_col72),
            eval!(context, state_5_id_col73),
            eval!(context, low_16_bits_col74),
            eval!(context, high_16_bits_col75),
            eval!(context, low_7_ms_bits_col76),
            eval!(context, high_14_ms_bits_col77),
            eval!(context, high_5_ms_bits_col78),
            eval!(context, state_6_id_col79),
            eval!(context, low_16_bits_col80),
            eval!(context, high_16_bits_col81),
            eval!(context, low_7_ms_bits_col82),
            eval!(context, high_14_ms_bits_col83),
            eval!(context, high_5_ms_bits_col84),
            eval!(context, state_7_id_col85),
            eval!(context, ms_8_bits_col86),
            eval!(context, ms_8_bits_col87),
            eval!(context, xor_col88),
            eval!(context, xor_col89),
            eval!(context, xor_col90),
            eval!(context, xor_col91),
        ],
        context,
        component_data,
        acc,
    )
    .try_into()
    .unwrap();

    // Yield BlakeRound.
    let tuple_2 = &[
        eval!(context, 40528774),
        eval!(context, seq),
        eval!(context, 0),
        eval!(context, low_16_bits_col38),
        eval!(context, high_16_bits_col39),
        eval!(context, low_16_bits_col44),
        eval!(context, high_16_bits_col45),
        eval!(context, low_16_bits_col50),
        eval!(context, high_16_bits_col51),
        eval!(context, low_16_bits_col56),
        eval!(context, high_16_bits_col57),
        eval!(context, low_16_bits_col62),
        eval!(context, high_16_bits_col63),
        eval!(context, low_16_bits_col68),
        eval!(context, high_16_bits_col69),
        eval!(context, low_16_bits_col74),
        eval!(context, high_16_bits_col75),
        eval!(context, low_16_bits_col80),
        eval!(context, high_16_bits_col81),
        eval!(context, 58983),
        eval!(context, 27145),
        eval!(context, 44677),
        eval!(context, 47975),
        eval!(context, 62322),
        eval!(context, 15470),
        eval!(context, 62778),
        eval!(context, 42319),
        eval!(context, create_blake_round_input_output_tmp_53f39_143_limb_24),
        eval!(context, create_blake_round_input_output_tmp_53f39_143_limb_25),
        eval!(context, 26764),
        eval!(context, 39685),
        eval!(context, create_blake_round_input_output_tmp_53f39_143_limb_28),
        eval!(context, create_blake_round_input_output_tmp_53f39_143_limb_29),
        eval!(context, 52505),
        eval!(context, 23520),
        eval!(context, decode_blake_opcode_output_tmp_53f39_42_limb_1),
    ];
    let numerator_2 = eval!(context, -(1));
    acc.add_to_relation(context, numerator_2, tuple_2);

    // Use BlakeRound.
    let tuple_3 = &[
        eval!(context, 40528774),
        eval!(context, seq),
        eval!(context, 10),
        eval!(context, blake_round_output_limb_0_col92),
        eval!(context, blake_round_output_limb_1_col93),
        eval!(context, blake_round_output_limb_2_col94),
        eval!(context, blake_round_output_limb_3_col95),
        eval!(context, blake_round_output_limb_4_col96),
        eval!(context, blake_round_output_limb_5_col97),
        eval!(context, blake_round_output_limb_6_col98),
        eval!(context, blake_round_output_limb_7_col99),
        eval!(context, blake_round_output_limb_8_col100),
        eval!(context, blake_round_output_limb_9_col101),
        eval!(context, blake_round_output_limb_10_col102),
        eval!(context, blake_round_output_limb_11_col103),
        eval!(context, blake_round_output_limb_12_col104),
        eval!(context, blake_round_output_limb_13_col105),
        eval!(context, blake_round_output_limb_14_col106),
        eval!(context, blake_round_output_limb_15_col107),
        eval!(context, blake_round_output_limb_16_col108),
        eval!(context, blake_round_output_limb_17_col109),
        eval!(context, blake_round_output_limb_18_col110),
        eval!(context, blake_round_output_limb_19_col111),
        eval!(context, blake_round_output_limb_20_col112),
        eval!(context, blake_round_output_limb_21_col113),
        eval!(context, blake_round_output_limb_22_col114),
        eval!(context, blake_round_output_limb_23_col115),
        eval!(context, blake_round_output_limb_24_col116),
        eval!(context, blake_round_output_limb_25_col117),
        eval!(context, blake_round_output_limb_26_col118),
        eval!(context, blake_round_output_limb_27_col119),
        eval!(context, blake_round_output_limb_28_col120),
        eval!(context, blake_round_output_limb_29_col121),
        eval!(context, blake_round_output_limb_30_col122),
        eval!(context, blake_round_output_limb_31_col123),
        eval!(context, blake_round_output_limb_32_col124),
    ];
    let numerator_3 = eval!(context, 1);
    acc.add_to_relation(context, numerator_3, tuple_3);

    create_blake_output::accumulate_constraints(
        &[
            eval!(context, low_16_bits_col38),
            eval!(context, high_16_bits_col39),
            eval!(context, low_16_bits_col44),
            eval!(context, high_16_bits_col45),
            eval!(context, low_16_bits_col50),
            eval!(context, high_16_bits_col51),
            eval!(context, low_16_bits_col56),
            eval!(context, high_16_bits_col57),
            eval!(context, low_16_bits_col62),
            eval!(context, high_16_bits_col63),
            eval!(context, low_16_bits_col68),
            eval!(context, high_16_bits_col69),
            eval!(context, low_16_bits_col74),
            eval!(context, high_16_bits_col75),
            eval!(context, low_16_bits_col80),
            eval!(context, high_16_bits_col81),
            eval!(context, blake_round_output_limb_0_col92),
            eval!(context, blake_round_output_limb_1_col93),
            eval!(context, blake_round_output_limb_2_col94),
            eval!(context, blake_round_output_limb_3_col95),
            eval!(context, blake_round_output_limb_4_col96),
            eval!(context, blake_round_output_limb_5_col97),
            eval!(context, blake_round_output_limb_6_col98),
            eval!(context, blake_round_output_limb_7_col99),
            eval!(context, blake_round_output_limb_8_col100),
            eval!(context, blake_round_output_limb_9_col101),
            eval!(context, blake_round_output_limb_10_col102),
            eval!(context, blake_round_output_limb_11_col103),
            eval!(context, blake_round_output_limb_12_col104),
            eval!(context, blake_round_output_limb_13_col105),
            eval!(context, blake_round_output_limb_14_col106),
            eval!(context, blake_round_output_limb_15_col107),
            eval!(context, blake_round_output_limb_16_col108),
            eval!(context, blake_round_output_limb_17_col109),
            eval!(context, blake_round_output_limb_18_col110),
            eval!(context, blake_round_output_limb_19_col111),
            eval!(context, blake_round_output_limb_20_col112),
            eval!(context, blake_round_output_limb_21_col113),
            eval!(context, blake_round_output_limb_22_col114),
            eval!(context, blake_round_output_limb_23_col115),
            eval!(context, blake_round_output_limb_24_col116),
            eval!(context, blake_round_output_limb_25_col117),
            eval!(context, blake_round_output_limb_26_col118),
            eval!(context, blake_round_output_limb_27_col119),
            eval!(context, blake_round_output_limb_28_col120),
            eval!(context, blake_round_output_limb_29_col121),
            eval!(context, blake_round_output_limb_30_col122),
            eval!(context, blake_round_output_limb_31_col123),
            eval!(context, triple_xor_32_output_limb_0_col125),
            eval!(context, triple_xor_32_output_limb_1_col126),
            eval!(context, triple_xor_32_output_limb_0_col127),
            eval!(context, triple_xor_32_output_limb_1_col128),
            eval!(context, triple_xor_32_output_limb_0_col129),
            eval!(context, triple_xor_32_output_limb_1_col130),
            eval!(context, triple_xor_32_output_limb_0_col131),
            eval!(context, triple_xor_32_output_limb_1_col132),
            eval!(context, triple_xor_32_output_limb_0_col133),
            eval!(context, triple_xor_32_output_limb_1_col134),
            eval!(context, triple_xor_32_output_limb_0_col135),
            eval!(context, triple_xor_32_output_limb_1_col136),
            eval!(context, triple_xor_32_output_limb_0_col137),
            eval!(context, triple_xor_32_output_limb_1_col138),
            eval!(context, triple_xor_32_output_limb_0_col139),
            eval!(context, triple_xor_32_output_limb_1_col140),
        ],
        context,
        component_data,
        acc,
    );

    verify_u_32::accumulate_constraints(
        &[
            eval!(context, decode_blake_opcode_output_tmp_53f39_42_limb_2),
            eval!(context, triple_xor_32_output_limb_0_col125),
            eval!(context, triple_xor_32_output_limb_1_col126),
            eval!(context, low_7_ms_bits_col141),
            eval!(context, high_14_ms_bits_col142),
            eval!(context, high_5_ms_bits_col143),
            eval!(context, new_state_0_id_col144),
        ],
        context,
        component_data,
        acc,
    );

    verify_u_32::accumulate_constraints(
        &[
            eval!(context, (decode_blake_opcode_output_tmp_53f39_42_limb_2) + (1)),
            eval!(context, triple_xor_32_output_limb_0_col127),
            eval!(context, triple_xor_32_output_limb_1_col128),
            eval!(context, low_7_ms_bits_col145),
            eval!(context, high_14_ms_bits_col146),
            eval!(context, high_5_ms_bits_col147),
            eval!(context, new_state_1_id_col148),
        ],
        context,
        component_data,
        acc,
    );

    verify_u_32::accumulate_constraints(
        &[
            eval!(context, (decode_blake_opcode_output_tmp_53f39_42_limb_2) + (2)),
            eval!(context, triple_xor_32_output_limb_0_col129),
            eval!(context, triple_xor_32_output_limb_1_col130),
            eval!(context, low_7_ms_bits_col149),
            eval!(context, high_14_ms_bits_col150),
            eval!(context, high_5_ms_bits_col151),
            eval!(context, new_state_2_id_col152),
        ],
        context,
        component_data,
        acc,
    );

    verify_u_32::accumulate_constraints(
        &[
            eval!(context, (decode_blake_opcode_output_tmp_53f39_42_limb_2) + (3)),
            eval!(context, triple_xor_32_output_limb_0_col131),
            eval!(context, triple_xor_32_output_limb_1_col132),
            eval!(context, low_7_ms_bits_col153),
            eval!(context, high_14_ms_bits_col154),
            eval!(context, high_5_ms_bits_col155),
            eval!(context, new_state_3_id_col156),
        ],
        context,
        component_data,
        acc,
    );

    verify_u_32::accumulate_constraints(
        &[
            eval!(context, (decode_blake_opcode_output_tmp_53f39_42_limb_2) + (4)),
            eval!(context, triple_xor_32_output_limb_0_col133),
            eval!(context, triple_xor_32_output_limb_1_col134),
            eval!(context, low_7_ms_bits_col157),
            eval!(context, high_14_ms_bits_col158),
            eval!(context, high_5_ms_bits_col159),
            eval!(context, new_state_4_id_col160),
        ],
        context,
        component_data,
        acc,
    );

    verify_u_32::accumulate_constraints(
        &[
            eval!(context, (decode_blake_opcode_output_tmp_53f39_42_limb_2) + (5)),
            eval!(context, triple_xor_32_output_limb_0_col135),
            eval!(context, triple_xor_32_output_limb_1_col136),
            eval!(context, low_7_ms_bits_col161),
            eval!(context, high_14_ms_bits_col162),
            eval!(context, high_5_ms_bits_col163),
            eval!(context, new_state_5_id_col164),
        ],
        context,
        component_data,
        acc,
    );

    verify_u_32::accumulate_constraints(
        &[
            eval!(context, (decode_blake_opcode_output_tmp_53f39_42_limb_2) + (6)),
            eval!(context, triple_xor_32_output_limb_0_col137),
            eval!(context, triple_xor_32_output_limb_1_col138),
            eval!(context, low_7_ms_bits_col165),
            eval!(context, high_14_ms_bits_col166),
            eval!(context, high_5_ms_bits_col167),
            eval!(context, new_state_6_id_col168),
        ],
        context,
        component_data,
        acc,
    );

    verify_u_32::accumulate_constraints(
        &[
            eval!(context, (decode_blake_opcode_output_tmp_53f39_42_limb_2) + (7)),
            eval!(context, triple_xor_32_output_limb_0_col139),
            eval!(context, triple_xor_32_output_limb_1_col140),
            eval!(context, low_7_ms_bits_col169),
            eval!(context, high_14_ms_bits_col170),
            eval!(context, high_5_ms_bits_col171),
            eval!(context, new_state_7_id_col172),
        ],
        context,
        component_data,
        acc,
    );

    // Use Opcodes.
    let tuple_13 = &[
        eval!(context, 428564188),
        eval!(context, input_pc_col0),
        eval!(context, input_ap_col1),
        eval!(context, input_fp_col2),
    ];
    let numerator_13 = eval!(context, enabler);
    acc.add_to_relation(context, numerator_13, tuple_13);

    // Yield Opcodes.
    let tuple_14 = &[
        eval!(context, 428564188),
        eval!(context, (input_pc_col0) + (1)),
        eval!(context, (input_ap_col1) + (ap_update_add_1_col9)),
        eval!(context, input_fp_col2),
    ];
    let numerator_14 = eval!(context, -(enabler));
    acc.add_to_relation(context, numerator_14, tuple_14);
}

pub struct Component {}
impl<Value: IValue> CircuitEval<Value> for Component {
    fn evaluate(
        &self,
        context: &mut Context<Value>,
        component_data: &ComponentData<'_>,
        acc: &mut CompositionConstraintAccumulator,
    ) {
        accumulate_constraints(component_data.trace_columns, context, component_data, acc);
    }

    fn trace_columns(&self) -> usize {
        N_TRACE_COLUMNS
    }

    fn interaction_columns(&self) -> usize {
        N_INTERACTION_COLUMNS
    }

    fn relation_uses_per_row(&self) -> &[RelationUse] {
        &RELATION_USES_PER_ROW
    }
}
