// This file was created by the AIR team.

use crate::cairo_air::components::prelude::*;

pub const N_TRACE_COLUMNS: usize = 141;
pub const N_INTERACTION_COLUMNS: usize = 200;

pub const RELATION_USES_PER_ROW: [RelationUse; 16] = [
    RelationUse { relation_id: "RangeCheck_20", uses: 8 },
    RelationUse { relation_id: "RangeCheck_20_B", uses: 8 },
    RelationUse { relation_id: "RangeCheck_20_C", uses: 8 },
    RelationUse { relation_id: "RangeCheck_20_D", uses: 8 },
    RelationUse { relation_id: "RangeCheck_20_E", uses: 6 },
    RelationUse { relation_id: "RangeCheck_20_F", uses: 6 },
    RelationUse { relation_id: "RangeCheck_20_G", uses: 6 },
    RelationUse { relation_id: "RangeCheck_20_H", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_B", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_C", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_D", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_E", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_F", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_G", uses: 3 },
    RelationUse { relation_id: "RangeCheck_9_9_H", uses: 3 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints(
    input: &[Var],
    context: &mut Context<impl IValue>,
    component_data: &ComponentData<'_>,
    acc: &mut CompositionConstraintAccumulator,
) {
    let [
        input_limb_0_col0,
        input_limb_1_col1,
        input_limb_2_col2,
        input_limb_3_col3,
        input_limb_4_col4,
        input_limb_5_col5,
        input_limb_6_col6,
        input_limb_7_col7,
        input_limb_8_col8,
        input_limb_9_col9,
        unpacked_limb_0_col10,
        unpacked_limb_1_col11,
        unpacked_limb_3_col12,
        unpacked_limb_4_col13,
        unpacked_limb_6_col14,
        unpacked_limb_7_col15,
        unpacked_limb_9_col16,
        unpacked_limb_10_col17,
        unpacked_limb_12_col18,
        unpacked_limb_13_col19,
        unpacked_limb_15_col20,
        unpacked_limb_16_col21,
        unpacked_limb_18_col22,
        unpacked_limb_19_col23,
        unpacked_limb_21_col24,
        unpacked_limb_22_col25,
        unpacked_limb_24_col26,
        unpacked_limb_25_col27,
        mul_res_limb_0_col28,
        mul_res_limb_1_col29,
        mul_res_limb_2_col30,
        mul_res_limb_3_col31,
        mul_res_limb_4_col32,
        mul_res_limb_5_col33,
        mul_res_limb_6_col34,
        mul_res_limb_7_col35,
        mul_res_limb_8_col36,
        mul_res_limb_9_col37,
        mul_res_limb_10_col38,
        mul_res_limb_11_col39,
        mul_res_limb_12_col40,
        mul_res_limb_13_col41,
        mul_res_limb_14_col42,
        mul_res_limb_15_col43,
        mul_res_limb_16_col44,
        mul_res_limb_17_col45,
        mul_res_limb_18_col46,
        mul_res_limb_19_col47,
        mul_res_limb_20_col48,
        mul_res_limb_21_col49,
        mul_res_limb_22_col50,
        mul_res_limb_23_col51,
        mul_res_limb_24_col52,
        mul_res_limb_25_col53,
        mul_res_limb_26_col54,
        mul_res_limb_27_col55,
        k_col56,
        carry_0_col57,
        carry_1_col58,
        carry_2_col59,
        carry_3_col60,
        carry_4_col61,
        carry_5_col62,
        carry_6_col63,
        carry_7_col64,
        carry_8_col65,
        carry_9_col66,
        carry_10_col67,
        carry_11_col68,
        carry_12_col69,
        carry_13_col70,
        carry_14_col71,
        carry_15_col72,
        carry_16_col73,
        carry_17_col74,
        carry_18_col75,
        carry_19_col76,
        carry_20_col77,
        carry_21_col78,
        carry_22_col79,
        carry_23_col80,
        carry_24_col81,
        carry_25_col82,
        carry_26_col83,
        mul_res_limb_0_col84,
        mul_res_limb_1_col85,
        mul_res_limb_2_col86,
        mul_res_limb_3_col87,
        mul_res_limb_4_col88,
        mul_res_limb_5_col89,
        mul_res_limb_6_col90,
        mul_res_limb_7_col91,
        mul_res_limb_8_col92,
        mul_res_limb_9_col93,
        mul_res_limb_10_col94,
        mul_res_limb_11_col95,
        mul_res_limb_12_col96,
        mul_res_limb_13_col97,
        mul_res_limb_14_col98,
        mul_res_limb_15_col99,
        mul_res_limb_16_col100,
        mul_res_limb_17_col101,
        mul_res_limb_18_col102,
        mul_res_limb_19_col103,
        mul_res_limb_20_col104,
        mul_res_limb_21_col105,
        mul_res_limb_22_col106,
        mul_res_limb_23_col107,
        mul_res_limb_24_col108,
        mul_res_limb_25_col109,
        mul_res_limb_26_col110,
        mul_res_limb_27_col111,
        k_col112,
        carry_0_col113,
        carry_1_col114,
        carry_2_col115,
        carry_3_col116,
        carry_4_col117,
        carry_5_col118,
        carry_6_col119,
        carry_7_col120,
        carry_8_col121,
        carry_9_col122,
        carry_10_col123,
        carry_11_col124,
        carry_12_col125,
        carry_13_col126,
        carry_14_col127,
        carry_15_col128,
        carry_16_col129,
        carry_17_col130,
        carry_18_col131,
        carry_19_col132,
        carry_20_col133,
        carry_21_col134,
        carry_22_col135,
        carry_23_col136,
        carry_24_col137,
        carry_25_col138,
        carry_26_col139,
        enabler,
    ] = input.try_into().unwrap();
    let enabler_constraint_value = eval!(context, ((enabler) * (enabler)) - (enabler));
    acc.add_constraint(context, enabler_constraint_value);

    let [
        felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_2,
        felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_5,
        felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_8,
        felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_11,
        felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_14,
        felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_17,
        felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_20,
        felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_23,
        felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_26,
        felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_27,
    ] = felt_252_unpack_from_27_range_check_output::accumulate_constraints(
        &[
            eval!(context, input_limb_0_col0),
            eval!(context, input_limb_1_col1),
            eval!(context, input_limb_2_col2),
            eval!(context, input_limb_3_col3),
            eval!(context, input_limb_4_col4),
            eval!(context, input_limb_5_col5),
            eval!(context, input_limb_6_col6),
            eval!(context, input_limb_7_col7),
            eval!(context, input_limb_8_col8),
            eval!(context, input_limb_9_col9),
            eval!(context, unpacked_limb_0_col10),
            eval!(context, unpacked_limb_1_col11),
            eval!(context, unpacked_limb_3_col12),
            eval!(context, unpacked_limb_4_col13),
            eval!(context, unpacked_limb_6_col14),
            eval!(context, unpacked_limb_7_col15),
            eval!(context, unpacked_limb_9_col16),
            eval!(context, unpacked_limb_10_col17),
            eval!(context, unpacked_limb_12_col18),
            eval!(context, unpacked_limb_13_col19),
            eval!(context, unpacked_limb_15_col20),
            eval!(context, unpacked_limb_16_col21),
            eval!(context, unpacked_limb_18_col22),
            eval!(context, unpacked_limb_19_col23),
            eval!(context, unpacked_limb_21_col24),
            eval!(context, unpacked_limb_22_col25),
            eval!(context, unpacked_limb_24_col26),
            eval!(context, unpacked_limb_25_col27),
        ],
        context,
        component_data,
        acc,
    )
    .try_into()
    .unwrap();

    mul_252::accumulate_constraints(
        &[
            eval!(context, unpacked_limb_0_col10),
            eval!(context, unpacked_limb_1_col11),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_2),
            eval!(context, unpacked_limb_3_col12),
            eval!(context, unpacked_limb_4_col13),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_5),
            eval!(context, unpacked_limb_6_col14),
            eval!(context, unpacked_limb_7_col15),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_8),
            eval!(context, unpacked_limb_9_col16),
            eval!(context, unpacked_limb_10_col17),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_11),
            eval!(context, unpacked_limb_12_col18),
            eval!(context, unpacked_limb_13_col19),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_14),
            eval!(context, unpacked_limb_15_col20),
            eval!(context, unpacked_limb_16_col21),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_17),
            eval!(context, unpacked_limb_18_col22),
            eval!(context, unpacked_limb_19_col23),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_20),
            eval!(context, unpacked_limb_21_col24),
            eval!(context, unpacked_limb_22_col25),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_23),
            eval!(context, unpacked_limb_24_col26),
            eval!(context, unpacked_limb_25_col27),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_26),
            eval!(context, input_limb_9_col9),
            eval!(context, unpacked_limb_0_col10),
            eval!(context, unpacked_limb_1_col11),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_2),
            eval!(context, unpacked_limb_3_col12),
            eval!(context, unpacked_limb_4_col13),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_5),
            eval!(context, unpacked_limb_6_col14),
            eval!(context, unpacked_limb_7_col15),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_8),
            eval!(context, unpacked_limb_9_col16),
            eval!(context, unpacked_limb_10_col17),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_11),
            eval!(context, unpacked_limb_12_col18),
            eval!(context, unpacked_limb_13_col19),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_14),
            eval!(context, unpacked_limb_15_col20),
            eval!(context, unpacked_limb_16_col21),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_17),
            eval!(context, unpacked_limb_18_col22),
            eval!(context, unpacked_limb_19_col23),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_20),
            eval!(context, unpacked_limb_21_col24),
            eval!(context, unpacked_limb_22_col25),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_23),
            eval!(context, unpacked_limb_24_col26),
            eval!(context, unpacked_limb_25_col27),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_26),
            eval!(context, input_limb_9_col9),
            eval!(context, mul_res_limb_0_col28),
            eval!(context, mul_res_limb_1_col29),
            eval!(context, mul_res_limb_2_col30),
            eval!(context, mul_res_limb_3_col31),
            eval!(context, mul_res_limb_4_col32),
            eval!(context, mul_res_limb_5_col33),
            eval!(context, mul_res_limb_6_col34),
            eval!(context, mul_res_limb_7_col35),
            eval!(context, mul_res_limb_8_col36),
            eval!(context, mul_res_limb_9_col37),
            eval!(context, mul_res_limb_10_col38),
            eval!(context, mul_res_limb_11_col39),
            eval!(context, mul_res_limb_12_col40),
            eval!(context, mul_res_limb_13_col41),
            eval!(context, mul_res_limb_14_col42),
            eval!(context, mul_res_limb_15_col43),
            eval!(context, mul_res_limb_16_col44),
            eval!(context, mul_res_limb_17_col45),
            eval!(context, mul_res_limb_18_col46),
            eval!(context, mul_res_limb_19_col47),
            eval!(context, mul_res_limb_20_col48),
            eval!(context, mul_res_limb_21_col49),
            eval!(context, mul_res_limb_22_col50),
            eval!(context, mul_res_limb_23_col51),
            eval!(context, mul_res_limb_24_col52),
            eval!(context, mul_res_limb_25_col53),
            eval!(context, mul_res_limb_26_col54),
            eval!(context, mul_res_limb_27_col55),
            eval!(context, k_col56),
            eval!(context, carry_0_col57),
            eval!(context, carry_1_col58),
            eval!(context, carry_2_col59),
            eval!(context, carry_3_col60),
            eval!(context, carry_4_col61),
            eval!(context, carry_5_col62),
            eval!(context, carry_6_col63),
            eval!(context, carry_7_col64),
            eval!(context, carry_8_col65),
            eval!(context, carry_9_col66),
            eval!(context, carry_10_col67),
            eval!(context, carry_11_col68),
            eval!(context, carry_12_col69),
            eval!(context, carry_13_col70),
            eval!(context, carry_14_col71),
            eval!(context, carry_15_col72),
            eval!(context, carry_16_col73),
            eval!(context, carry_17_col74),
            eval!(context, carry_18_col75),
            eval!(context, carry_19_col76),
            eval!(context, carry_20_col77),
            eval!(context, carry_21_col78),
            eval!(context, carry_22_col79),
            eval!(context, carry_23_col80),
            eval!(context, carry_24_col81),
            eval!(context, carry_25_col82),
            eval!(context, carry_26_col83),
        ],
        context,
        component_data,
        acc,
    );

    mul_252::accumulate_constraints(
        &[
            eval!(context, unpacked_limb_0_col10),
            eval!(context, unpacked_limb_1_col11),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_2),
            eval!(context, unpacked_limb_3_col12),
            eval!(context, unpacked_limb_4_col13),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_5),
            eval!(context, unpacked_limb_6_col14),
            eval!(context, unpacked_limb_7_col15),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_8),
            eval!(context, unpacked_limb_9_col16),
            eval!(context, unpacked_limb_10_col17),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_11),
            eval!(context, unpacked_limb_12_col18),
            eval!(context, unpacked_limb_13_col19),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_14),
            eval!(context, unpacked_limb_15_col20),
            eval!(context, unpacked_limb_16_col21),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_17),
            eval!(context, unpacked_limb_18_col22),
            eval!(context, unpacked_limb_19_col23),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_20),
            eval!(context, unpacked_limb_21_col24),
            eval!(context, unpacked_limb_22_col25),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_23),
            eval!(context, unpacked_limb_24_col26),
            eval!(context, unpacked_limb_25_col27),
            eval!(context, felt_252_unpack_from_27_range_check_output_output_tmp_fec87_2_limb_26),
            eval!(context, input_limb_9_col9),
            eval!(context, mul_res_limb_0_col28),
            eval!(context, mul_res_limb_1_col29),
            eval!(context, mul_res_limb_2_col30),
            eval!(context, mul_res_limb_3_col31),
            eval!(context, mul_res_limb_4_col32),
            eval!(context, mul_res_limb_5_col33),
            eval!(context, mul_res_limb_6_col34),
            eval!(context, mul_res_limb_7_col35),
            eval!(context, mul_res_limb_8_col36),
            eval!(context, mul_res_limb_9_col37),
            eval!(context, mul_res_limb_10_col38),
            eval!(context, mul_res_limb_11_col39),
            eval!(context, mul_res_limb_12_col40),
            eval!(context, mul_res_limb_13_col41),
            eval!(context, mul_res_limb_14_col42),
            eval!(context, mul_res_limb_15_col43),
            eval!(context, mul_res_limb_16_col44),
            eval!(context, mul_res_limb_17_col45),
            eval!(context, mul_res_limb_18_col46),
            eval!(context, mul_res_limb_19_col47),
            eval!(context, mul_res_limb_20_col48),
            eval!(context, mul_res_limb_21_col49),
            eval!(context, mul_res_limb_22_col50),
            eval!(context, mul_res_limb_23_col51),
            eval!(context, mul_res_limb_24_col52),
            eval!(context, mul_res_limb_25_col53),
            eval!(context, mul_res_limb_26_col54),
            eval!(context, mul_res_limb_27_col55),
            eval!(context, mul_res_limb_0_col84),
            eval!(context, mul_res_limb_1_col85),
            eval!(context, mul_res_limb_2_col86),
            eval!(context, mul_res_limb_3_col87),
            eval!(context, mul_res_limb_4_col88),
            eval!(context, mul_res_limb_5_col89),
            eval!(context, mul_res_limb_6_col90),
            eval!(context, mul_res_limb_7_col91),
            eval!(context, mul_res_limb_8_col92),
            eval!(context, mul_res_limb_9_col93),
            eval!(context, mul_res_limb_10_col94),
            eval!(context, mul_res_limb_11_col95),
            eval!(context, mul_res_limb_12_col96),
            eval!(context, mul_res_limb_13_col97),
            eval!(context, mul_res_limb_14_col98),
            eval!(context, mul_res_limb_15_col99),
            eval!(context, mul_res_limb_16_col100),
            eval!(context, mul_res_limb_17_col101),
            eval!(context, mul_res_limb_18_col102),
            eval!(context, mul_res_limb_19_col103),
            eval!(context, mul_res_limb_20_col104),
            eval!(context, mul_res_limb_21_col105),
            eval!(context, mul_res_limb_22_col106),
            eval!(context, mul_res_limb_23_col107),
            eval!(context, mul_res_limb_24_col108),
            eval!(context, mul_res_limb_25_col109),
            eval!(context, mul_res_limb_26_col110),
            eval!(context, mul_res_limb_27_col111),
            eval!(context, k_col112),
            eval!(context, carry_0_col113),
            eval!(context, carry_1_col114),
            eval!(context, carry_2_col115),
            eval!(context, carry_3_col116),
            eval!(context, carry_4_col117),
            eval!(context, carry_5_col118),
            eval!(context, carry_6_col119),
            eval!(context, carry_7_col120),
            eval!(context, carry_8_col121),
            eval!(context, carry_9_col122),
            eval!(context, carry_10_col123),
            eval!(context, carry_11_col124),
            eval!(context, carry_12_col125),
            eval!(context, carry_13_col126),
            eval!(context, carry_14_col127),
            eval!(context, carry_15_col128),
            eval!(context, carry_16_col129),
            eval!(context, carry_17_col130),
            eval!(context, carry_18_col131),
            eval!(context, carry_19_col132),
            eval!(context, carry_20_col133),
            eval!(context, carry_21_col134),
            eval!(context, carry_22_col135),
            eval!(context, carry_23_col136),
            eval!(context, carry_24_col137),
            eval!(context, carry_25_col138),
            eval!(context, carry_26_col139),
        ],
        context,
        component_data,
        acc,
    );

    // Yield Cube252.
    let tuple_3 = &[
        eval!(context, 1987997202),
        eval!(context, input_limb_0_col0),
        eval!(context, input_limb_1_col1),
        eval!(context, input_limb_2_col2),
        eval!(context, input_limb_3_col3),
        eval!(context, input_limb_4_col4),
        eval!(context, input_limb_5_col5),
        eval!(context, input_limb_6_col6),
        eval!(context, input_limb_7_col7),
        eval!(context, input_limb_8_col8),
        eval!(context, input_limb_9_col9),
        eval!(
            context,
            ((mul_res_limb_0_col84) + ((mul_res_limb_1_col85) * (512)))
                + ((mul_res_limb_2_col86) * (262144))
        ),
        eval!(
            context,
            ((mul_res_limb_3_col87) + ((mul_res_limb_4_col88) * (512)))
                + ((mul_res_limb_5_col89) * (262144))
        ),
        eval!(
            context,
            ((mul_res_limb_6_col90) + ((mul_res_limb_7_col91) * (512)))
                + ((mul_res_limb_8_col92) * (262144))
        ),
        eval!(
            context,
            ((mul_res_limb_9_col93) + ((mul_res_limb_10_col94) * (512)))
                + ((mul_res_limb_11_col95) * (262144))
        ),
        eval!(
            context,
            ((mul_res_limb_12_col96) + ((mul_res_limb_13_col97) * (512)))
                + ((mul_res_limb_14_col98) * (262144))
        ),
        eval!(
            context,
            ((mul_res_limb_15_col99) + ((mul_res_limb_16_col100) * (512)))
                + ((mul_res_limb_17_col101) * (262144))
        ),
        eval!(
            context,
            ((mul_res_limb_18_col102) + ((mul_res_limb_19_col103) * (512)))
                + ((mul_res_limb_20_col104) * (262144))
        ),
        eval!(
            context,
            ((mul_res_limb_21_col105) + ((mul_res_limb_22_col106) * (512)))
                + ((mul_res_limb_23_col107) * (262144))
        ),
        eval!(
            context,
            ((mul_res_limb_24_col108) + ((mul_res_limb_25_col109) * (512)))
                + ((mul_res_limb_26_col110) * (262144))
        ),
        eval!(context, mul_res_limb_27_col111),
    ];
    let numerator_3 = eval!(context, -(enabler));
    acc.add_to_relation(context, numerator_3, tuple_3);
}

pub struct Component {}
impl<Value: IValue> CircuitEval<Value> for Component {
    fn evaluate(
        &self,
        context: &mut Context<Value>,
        component_data: &ComponentData<'_>,
        acc: &mut CompositionConstraintAccumulator,
    ) {
        accumulate_constraints(component_data.trace_columns, context, component_data, acc);
    }

    fn trace_columns(&self) -> usize {
        N_TRACE_COLUMNS
    }

    fn interaction_columns(&self) -> usize {
        N_INTERACTION_COLUMNS
    }

    fn relation_uses_per_row(&self) -> &[RelationUse] {
        &RELATION_USES_PER_ROW
    }
}
