// This file was created by the AIR team.

use crate::cairo_air::components::prelude::*;

pub const N_TRACE_COLUMNS: usize = 273;
pub const N_INTERACTION_COLUMNS: usize = 36;

pub const RELATION_USES_PER_ROW: [RelationUse; 4] = [
    RelationUse { relation_id: "MemoryAddressToId", uses: 7 },
    RelationUse { relation_id: "MemoryIdToBig", uses: 7 },
    RelationUse { relation_id: "PartialEcMulGeneric", uses: 1 },
    RelationUse { relation_id: "RangeCheck_8", uses: 2 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints(
    input: &[Var],
    context: &mut Context<impl IValue>,
    component_data: &ComponentData<'_>,
    acc: &mut CompositionConstraintAccumulator,
) {
    let [
        p_x_id_col0,
        p_x_limb_0_col1,
        p_x_limb_1_col2,
        p_x_limb_2_col3,
        p_x_limb_3_col4,
        p_x_limb_4_col5,
        p_x_limb_5_col6,
        p_x_limb_6_col7,
        p_x_limb_7_col8,
        p_x_limb_8_col9,
        p_x_limb_9_col10,
        p_x_limb_10_col11,
        p_x_limb_11_col12,
        p_x_limb_12_col13,
        p_x_limb_13_col14,
        p_x_limb_14_col15,
        p_x_limb_15_col16,
        p_x_limb_16_col17,
        p_x_limb_17_col18,
        p_x_limb_18_col19,
        p_x_limb_19_col20,
        p_x_limb_20_col21,
        p_x_limb_21_col22,
        p_x_limb_22_col23,
        p_x_limb_23_col24,
        p_x_limb_24_col25,
        p_x_limb_25_col26,
        p_x_limb_26_col27,
        p_x_limb_27_col28,
        p_y_id_col29,
        p_y_limb_0_col30,
        p_y_limb_1_col31,
        p_y_limb_2_col32,
        p_y_limb_3_col33,
        p_y_limb_4_col34,
        p_y_limb_5_col35,
        p_y_limb_6_col36,
        p_y_limb_7_col37,
        p_y_limb_8_col38,
        p_y_limb_9_col39,
        p_y_limb_10_col40,
        p_y_limb_11_col41,
        p_y_limb_12_col42,
        p_y_limb_13_col43,
        p_y_limb_14_col44,
        p_y_limb_15_col45,
        p_y_limb_16_col46,
        p_y_limb_17_col47,
        p_y_limb_18_col48,
        p_y_limb_19_col49,
        p_y_limb_20_col50,
        p_y_limb_21_col51,
        p_y_limb_22_col52,
        p_y_limb_23_col53,
        p_y_limb_24_col54,
        p_y_limb_25_col55,
        p_y_limb_26_col56,
        p_y_limb_27_col57,
        q_x_id_col58,
        q_x_limb_0_col59,
        q_x_limb_1_col60,
        q_x_limb_2_col61,
        q_x_limb_3_col62,
        q_x_limb_4_col63,
        q_x_limb_5_col64,
        q_x_limb_6_col65,
        q_x_limb_7_col66,
        q_x_limb_8_col67,
        q_x_limb_9_col68,
        q_x_limb_10_col69,
        q_x_limb_11_col70,
        q_x_limb_12_col71,
        q_x_limb_13_col72,
        q_x_limb_14_col73,
        q_x_limb_15_col74,
        q_x_limb_16_col75,
        q_x_limb_17_col76,
        q_x_limb_18_col77,
        q_x_limb_19_col78,
        q_x_limb_20_col79,
        q_x_limb_21_col80,
        q_x_limb_22_col81,
        q_x_limb_23_col82,
        q_x_limb_24_col83,
        q_x_limb_25_col84,
        q_x_limb_26_col85,
        q_x_limb_27_col86,
        q_y_id_col87,
        q_y_limb_0_col88,
        q_y_limb_1_col89,
        q_y_limb_2_col90,
        q_y_limb_3_col91,
        q_y_limb_4_col92,
        q_y_limb_5_col93,
        q_y_limb_6_col94,
        q_y_limb_7_col95,
        q_y_limb_8_col96,
        q_y_limb_9_col97,
        q_y_limb_10_col98,
        q_y_limb_11_col99,
        q_y_limb_12_col100,
        q_y_limb_13_col101,
        q_y_limb_14_col102,
        q_y_limb_15_col103,
        q_y_limb_16_col104,
        q_y_limb_17_col105,
        q_y_limb_18_col106,
        q_y_limb_19_col107,
        q_y_limb_20_col108,
        q_y_limb_21_col109,
        q_y_limb_22_col110,
        q_y_limb_23_col111,
        q_y_limb_24_col112,
        q_y_limb_25_col113,
        q_y_limb_26_col114,
        q_y_limb_27_col115,
        m_id_col116,
        m_limb_0_col117,
        m_limb_1_col118,
        m_limb_2_col119,
        m_limb_3_col120,
        m_limb_4_col121,
        m_limb_5_col122,
        m_limb_6_col123,
        m_limb_7_col124,
        m_limb_8_col125,
        m_limb_9_col126,
        m_limb_10_col127,
        m_limb_11_col128,
        m_limb_12_col129,
        m_limb_13_col130,
        m_limb_14_col131,
        m_limb_15_col132,
        m_limb_16_col133,
        m_limb_17_col134,
        m_limb_18_col135,
        m_limb_19_col136,
        m_limb_20_col137,
        m_limb_21_col138,
        m_limb_22_col139,
        m_limb_23_col140,
        m_limb_24_col141,
        m_limb_25_col142,
        m_limb_26_col143,
        m_limb_27_col144,
        ms_limb_is_max_col145,
        ms_and_mid_limbs_are_max_col146,
        rc_input_col147,
        partial_ec_mul_generic_output_m_limb_0_col148,
        partial_ec_mul_generic_output_m_limb_1_col149,
        partial_ec_mul_generic_output_m_limb_2_col150,
        partial_ec_mul_generic_output_m_limb_3_col151,
        partial_ec_mul_generic_output_m_limb_4_col152,
        partial_ec_mul_generic_output_m_limb_5_col153,
        partial_ec_mul_generic_output_m_limb_6_col154,
        partial_ec_mul_generic_output_m_limb_7_col155,
        partial_ec_mul_generic_output_m_limb_8_col156,
        partial_ec_mul_generic_output_m_limb_9_col157,
        partial_ec_mul_generic_output_q_x_limb_0_col158,
        partial_ec_mul_generic_output_q_x_limb_1_col159,
        partial_ec_mul_generic_output_q_x_limb_2_col160,
        partial_ec_mul_generic_output_q_x_limb_3_col161,
        partial_ec_mul_generic_output_q_x_limb_4_col162,
        partial_ec_mul_generic_output_q_x_limb_5_col163,
        partial_ec_mul_generic_output_q_x_limb_6_col164,
        partial_ec_mul_generic_output_q_x_limb_7_col165,
        partial_ec_mul_generic_output_q_x_limb_8_col166,
        partial_ec_mul_generic_output_q_x_limb_9_col167,
        partial_ec_mul_generic_output_q_x_limb_10_col168,
        partial_ec_mul_generic_output_q_x_limb_11_col169,
        partial_ec_mul_generic_output_q_x_limb_12_col170,
        partial_ec_mul_generic_output_q_x_limb_13_col171,
        partial_ec_mul_generic_output_q_x_limb_14_col172,
        partial_ec_mul_generic_output_q_x_limb_15_col173,
        partial_ec_mul_generic_output_q_x_limb_16_col174,
        partial_ec_mul_generic_output_q_x_limb_17_col175,
        partial_ec_mul_generic_output_q_x_limb_18_col176,
        partial_ec_mul_generic_output_q_x_limb_19_col177,
        partial_ec_mul_generic_output_q_x_limb_20_col178,
        partial_ec_mul_generic_output_q_x_limb_21_col179,
        partial_ec_mul_generic_output_q_x_limb_22_col180,
        partial_ec_mul_generic_output_q_x_limb_23_col181,
        partial_ec_mul_generic_output_q_x_limb_24_col182,
        partial_ec_mul_generic_output_q_x_limb_25_col183,
        partial_ec_mul_generic_output_q_x_limb_26_col184,
        partial_ec_mul_generic_output_q_x_limb_27_col185,
        partial_ec_mul_generic_output_q_y_limb_0_col186,
        partial_ec_mul_generic_output_q_y_limb_1_col187,
        partial_ec_mul_generic_output_q_y_limb_2_col188,
        partial_ec_mul_generic_output_q_y_limb_3_col189,
        partial_ec_mul_generic_output_q_y_limb_4_col190,
        partial_ec_mul_generic_output_q_y_limb_5_col191,
        partial_ec_mul_generic_output_q_y_limb_6_col192,
        partial_ec_mul_generic_output_q_y_limb_7_col193,
        partial_ec_mul_generic_output_q_y_limb_8_col194,
        partial_ec_mul_generic_output_q_y_limb_9_col195,
        partial_ec_mul_generic_output_q_y_limb_10_col196,
        partial_ec_mul_generic_output_q_y_limb_11_col197,
        partial_ec_mul_generic_output_q_y_limb_12_col198,
        partial_ec_mul_generic_output_q_y_limb_13_col199,
        partial_ec_mul_generic_output_q_y_limb_14_col200,
        partial_ec_mul_generic_output_q_y_limb_15_col201,
        partial_ec_mul_generic_output_q_y_limb_16_col202,
        partial_ec_mul_generic_output_q_y_limb_17_col203,
        partial_ec_mul_generic_output_q_y_limb_18_col204,
        partial_ec_mul_generic_output_q_y_limb_19_col205,
        partial_ec_mul_generic_output_q_y_limb_20_col206,
        partial_ec_mul_generic_output_q_y_limb_21_col207,
        partial_ec_mul_generic_output_q_y_limb_22_col208,
        partial_ec_mul_generic_output_q_y_limb_23_col209,
        partial_ec_mul_generic_output_q_y_limb_24_col210,
        partial_ec_mul_generic_output_q_y_limb_25_col211,
        partial_ec_mul_generic_output_q_y_limb_26_col212,
        partial_ec_mul_generic_output_q_y_limb_27_col213,
        partial_ec_mul_generic_output_accumulator_x_limb_0_col214,
        partial_ec_mul_generic_output_accumulator_x_limb_1_col215,
        partial_ec_mul_generic_output_accumulator_x_limb_2_col216,
        partial_ec_mul_generic_output_accumulator_x_limb_3_col217,
        partial_ec_mul_generic_output_accumulator_x_limb_4_col218,
        partial_ec_mul_generic_output_accumulator_x_limb_5_col219,
        partial_ec_mul_generic_output_accumulator_x_limb_6_col220,
        partial_ec_mul_generic_output_accumulator_x_limb_7_col221,
        partial_ec_mul_generic_output_accumulator_x_limb_8_col222,
        partial_ec_mul_generic_output_accumulator_x_limb_9_col223,
        partial_ec_mul_generic_output_accumulator_x_limb_10_col224,
        partial_ec_mul_generic_output_accumulator_x_limb_11_col225,
        partial_ec_mul_generic_output_accumulator_x_limb_12_col226,
        partial_ec_mul_generic_output_accumulator_x_limb_13_col227,
        partial_ec_mul_generic_output_accumulator_x_limb_14_col228,
        partial_ec_mul_generic_output_accumulator_x_limb_15_col229,
        partial_ec_mul_generic_output_accumulator_x_limb_16_col230,
        partial_ec_mul_generic_output_accumulator_x_limb_17_col231,
        partial_ec_mul_generic_output_accumulator_x_limb_18_col232,
        partial_ec_mul_generic_output_accumulator_x_limb_19_col233,
        partial_ec_mul_generic_output_accumulator_x_limb_20_col234,
        partial_ec_mul_generic_output_accumulator_x_limb_21_col235,
        partial_ec_mul_generic_output_accumulator_x_limb_22_col236,
        partial_ec_mul_generic_output_accumulator_x_limb_23_col237,
        partial_ec_mul_generic_output_accumulator_x_limb_24_col238,
        partial_ec_mul_generic_output_accumulator_x_limb_25_col239,
        partial_ec_mul_generic_output_accumulator_x_limb_26_col240,
        partial_ec_mul_generic_output_accumulator_x_limb_27_col241,
        partial_ec_mul_generic_output_accumulator_y_limb_0_col242,
        partial_ec_mul_generic_output_accumulator_y_limb_1_col243,
        partial_ec_mul_generic_output_accumulator_y_limb_2_col244,
        partial_ec_mul_generic_output_accumulator_y_limb_3_col245,
        partial_ec_mul_generic_output_accumulator_y_limb_4_col246,
        partial_ec_mul_generic_output_accumulator_y_limb_5_col247,
        partial_ec_mul_generic_output_accumulator_y_limb_6_col248,
        partial_ec_mul_generic_output_accumulator_y_limb_7_col249,
        partial_ec_mul_generic_output_accumulator_y_limb_8_col250,
        partial_ec_mul_generic_output_accumulator_y_limb_9_col251,
        partial_ec_mul_generic_output_accumulator_y_limb_10_col252,
        partial_ec_mul_generic_output_accumulator_y_limb_11_col253,
        partial_ec_mul_generic_output_accumulator_y_limb_12_col254,
        partial_ec_mul_generic_output_accumulator_y_limb_13_col255,
        partial_ec_mul_generic_output_accumulator_y_limb_14_col256,
        partial_ec_mul_generic_output_accumulator_y_limb_15_col257,
        partial_ec_mul_generic_output_accumulator_y_limb_16_col258,
        partial_ec_mul_generic_output_accumulator_y_limb_17_col259,
        partial_ec_mul_generic_output_accumulator_y_limb_18_col260,
        partial_ec_mul_generic_output_accumulator_y_limb_19_col261,
        partial_ec_mul_generic_output_accumulator_y_limb_20_col262,
        partial_ec_mul_generic_output_accumulator_y_limb_21_col263,
        partial_ec_mul_generic_output_accumulator_y_limb_22_col264,
        partial_ec_mul_generic_output_accumulator_y_limb_23_col265,
        partial_ec_mul_generic_output_accumulator_y_limb_24_col266,
        partial_ec_mul_generic_output_accumulator_y_limb_25_col267,
        partial_ec_mul_generic_output_accumulator_y_limb_26_col268,
        partial_ec_mul_generic_output_accumulator_y_limb_27_col269,
        partial_ec_mul_generic_output_counter_col270,
        res_x_id_col271,
        res_y_id_col272,
    ] = input.try_into().unwrap();
    let seq = seq_of_component_size(context, component_data, acc);
    let ec_op_builtin_segment_start =
        *acc.public_params.get("ec_op_builtin_segment_start").unwrap();

    let instance_addr_tmp_45259_0 = eval!(context, ((seq) * (7)) + (ec_op_builtin_segment_start));

    read_positive_num_bits_252::accumulate_constraints(
        &[
            eval!(context, instance_addr_tmp_45259_0),
            eval!(context, p_x_id_col0),
            eval!(context, p_x_limb_0_col1),
            eval!(context, p_x_limb_1_col2),
            eval!(context, p_x_limb_2_col3),
            eval!(context, p_x_limb_3_col4),
            eval!(context, p_x_limb_4_col5),
            eval!(context, p_x_limb_5_col6),
            eval!(context, p_x_limb_6_col7),
            eval!(context, p_x_limb_7_col8),
            eval!(context, p_x_limb_8_col9),
            eval!(context, p_x_limb_9_col10),
            eval!(context, p_x_limb_10_col11),
            eval!(context, p_x_limb_11_col12),
            eval!(context, p_x_limb_12_col13),
            eval!(context, p_x_limb_13_col14),
            eval!(context, p_x_limb_14_col15),
            eval!(context, p_x_limb_15_col16),
            eval!(context, p_x_limb_16_col17),
            eval!(context, p_x_limb_17_col18),
            eval!(context, p_x_limb_18_col19),
            eval!(context, p_x_limb_19_col20),
            eval!(context, p_x_limb_20_col21),
            eval!(context, p_x_limb_21_col22),
            eval!(context, p_x_limb_22_col23),
            eval!(context, p_x_limb_23_col24),
            eval!(context, p_x_limb_24_col25),
            eval!(context, p_x_limb_25_col26),
            eval!(context, p_x_limb_26_col27),
            eval!(context, p_x_limb_27_col28),
        ],
        context,
        component_data,
        acc,
    );

    read_positive_num_bits_252::accumulate_constraints(
        &[
            eval!(context, (instance_addr_tmp_45259_0) + (1)),
            eval!(context, p_y_id_col29),
            eval!(context, p_y_limb_0_col30),
            eval!(context, p_y_limb_1_col31),
            eval!(context, p_y_limb_2_col32),
            eval!(context, p_y_limb_3_col33),
            eval!(context, p_y_limb_4_col34),
            eval!(context, p_y_limb_5_col35),
            eval!(context, p_y_limb_6_col36),
            eval!(context, p_y_limb_7_col37),
            eval!(context, p_y_limb_8_col38),
            eval!(context, p_y_limb_9_col39),
            eval!(context, p_y_limb_10_col40),
            eval!(context, p_y_limb_11_col41),
            eval!(context, p_y_limb_12_col42),
            eval!(context, p_y_limb_13_col43),
            eval!(context, p_y_limb_14_col44),
            eval!(context, p_y_limb_15_col45),
            eval!(context, p_y_limb_16_col46),
            eval!(context, p_y_limb_17_col47),
            eval!(context, p_y_limb_18_col48),
            eval!(context, p_y_limb_19_col49),
            eval!(context, p_y_limb_20_col50),
            eval!(context, p_y_limb_21_col51),
            eval!(context, p_y_limb_22_col52),
            eval!(context, p_y_limb_23_col53),
            eval!(context, p_y_limb_24_col54),
            eval!(context, p_y_limb_25_col55),
            eval!(context, p_y_limb_26_col56),
            eval!(context, p_y_limb_27_col57),
        ],
        context,
        component_data,
        acc,
    );

    read_positive_num_bits_252::accumulate_constraints(
        &[
            eval!(context, (instance_addr_tmp_45259_0) + (2)),
            eval!(context, q_x_id_col58),
            eval!(context, q_x_limb_0_col59),
            eval!(context, q_x_limb_1_col60),
            eval!(context, q_x_limb_2_col61),
            eval!(context, q_x_limb_3_col62),
            eval!(context, q_x_limb_4_col63),
            eval!(context, q_x_limb_5_col64),
            eval!(context, q_x_limb_6_col65),
            eval!(context, q_x_limb_7_col66),
            eval!(context, q_x_limb_8_col67),
            eval!(context, q_x_limb_9_col68),
            eval!(context, q_x_limb_10_col69),
            eval!(context, q_x_limb_11_col70),
            eval!(context, q_x_limb_12_col71),
            eval!(context, q_x_limb_13_col72),
            eval!(context, q_x_limb_14_col73),
            eval!(context, q_x_limb_15_col74),
            eval!(context, q_x_limb_16_col75),
            eval!(context, q_x_limb_17_col76),
            eval!(context, q_x_limb_18_col77),
            eval!(context, q_x_limb_19_col78),
            eval!(context, q_x_limb_20_col79),
            eval!(context, q_x_limb_21_col80),
            eval!(context, q_x_limb_22_col81),
            eval!(context, q_x_limb_23_col82),
            eval!(context, q_x_limb_24_col83),
            eval!(context, q_x_limb_25_col84),
            eval!(context, q_x_limb_26_col85),
            eval!(context, q_x_limb_27_col86),
        ],
        context,
        component_data,
        acc,
    );

    read_positive_num_bits_252::accumulate_constraints(
        &[
            eval!(context, (instance_addr_tmp_45259_0) + (3)),
            eval!(context, q_y_id_col87),
            eval!(context, q_y_limb_0_col88),
            eval!(context, q_y_limb_1_col89),
            eval!(context, q_y_limb_2_col90),
            eval!(context, q_y_limb_3_col91),
            eval!(context, q_y_limb_4_col92),
            eval!(context, q_y_limb_5_col93),
            eval!(context, q_y_limb_6_col94),
            eval!(context, q_y_limb_7_col95),
            eval!(context, q_y_limb_8_col96),
            eval!(context, q_y_limb_9_col97),
            eval!(context, q_y_limb_10_col98),
            eval!(context, q_y_limb_11_col99),
            eval!(context, q_y_limb_12_col100),
            eval!(context, q_y_limb_13_col101),
            eval!(context, q_y_limb_14_col102),
            eval!(context, q_y_limb_15_col103),
            eval!(context, q_y_limb_16_col104),
            eval!(context, q_y_limb_17_col105),
            eval!(context, q_y_limb_18_col106),
            eval!(context, q_y_limb_19_col107),
            eval!(context, q_y_limb_20_col108),
            eval!(context, q_y_limb_21_col109),
            eval!(context, q_y_limb_22_col110),
            eval!(context, q_y_limb_23_col111),
            eval!(context, q_y_limb_24_col112),
            eval!(context, q_y_limb_25_col113),
            eval!(context, q_y_limb_26_col114),
            eval!(context, q_y_limb_27_col115),
        ],
        context,
        component_data,
        acc,
    );

    read_positive_num_bits_252::accumulate_constraints(
        &[
            eval!(context, (instance_addr_tmp_45259_0) + (4)),
            eval!(context, m_id_col116),
            eval!(context, m_limb_0_col117),
            eval!(context, m_limb_1_col118),
            eval!(context, m_limb_2_col119),
            eval!(context, m_limb_3_col120),
            eval!(context, m_limb_4_col121),
            eval!(context, m_limb_5_col122),
            eval!(context, m_limb_6_col123),
            eval!(context, m_limb_7_col124),
            eval!(context, m_limb_8_col125),
            eval!(context, m_limb_9_col126),
            eval!(context, m_limb_10_col127),
            eval!(context, m_limb_11_col128),
            eval!(context, m_limb_12_col129),
            eval!(context, m_limb_13_col130),
            eval!(context, m_limb_14_col131),
            eval!(context, m_limb_15_col132),
            eval!(context, m_limb_16_col133),
            eval!(context, m_limb_17_col134),
            eval!(context, m_limb_18_col135),
            eval!(context, m_limb_19_col136),
            eval!(context, m_limb_20_col137),
            eval!(context, m_limb_21_col138),
            eval!(context, m_limb_22_col139),
            eval!(context, m_limb_23_col140),
            eval!(context, m_limb_24_col141),
            eval!(context, m_limb_25_col142),
            eval!(context, m_limb_26_col143),
            eval!(context, m_limb_27_col144),
        ],
        context,
        component_data,
        acc,
    );

    verify_reduced_252::accumulate_constraints(
        &[
            eval!(context, m_limb_0_col117),
            eval!(context, m_limb_1_col118),
            eval!(context, m_limb_2_col119),
            eval!(context, m_limb_3_col120),
            eval!(context, m_limb_4_col121),
            eval!(context, m_limb_5_col122),
            eval!(context, m_limb_6_col123),
            eval!(context, m_limb_7_col124),
            eval!(context, m_limb_8_col125),
            eval!(context, m_limb_9_col126),
            eval!(context, m_limb_10_col127),
            eval!(context, m_limb_11_col128),
            eval!(context, m_limb_12_col129),
            eval!(context, m_limb_13_col130),
            eval!(context, m_limb_14_col131),
            eval!(context, m_limb_15_col132),
            eval!(context, m_limb_16_col133),
            eval!(context, m_limb_17_col134),
            eval!(context, m_limb_18_col135),
            eval!(context, m_limb_19_col136),
            eval!(context, m_limb_20_col137),
            eval!(context, m_limb_21_col138),
            eval!(context, m_limb_22_col139),
            eval!(context, m_limb_23_col140),
            eval!(context, m_limb_24_col141),
            eval!(context, m_limb_25_col142),
            eval!(context, m_limb_26_col143),
            eval!(context, m_limb_27_col144),
            eval!(context, ms_limb_is_max_col145),
            eval!(context, ms_and_mid_limbs_are_max_col146),
            eval!(context, rc_input_col147),
        ],
        context,
        component_data,
        acc,
    );

    // Yield PartialEcMulGeneric.
    let tuple_7 = &[
        eval!(context, 183619546),
        eval!(context, seq),
        eval!(context, 0),
        eval!(
            context,
            ((m_limb_0_col117) + ((m_limb_1_col118) * (512))) + ((m_limb_2_col119) * (262144))
        ),
        eval!(
            context,
            ((m_limb_3_col120) + ((m_limb_4_col121) * (512))) + ((m_limb_5_col122) * (262144))
        ),
        eval!(
            context,
            ((m_limb_6_col123) + ((m_limb_7_col124) * (512))) + ((m_limb_8_col125) * (262144))
        ),
        eval!(
            context,
            ((m_limb_9_col126) + ((m_limb_10_col127) * (512))) + ((m_limb_11_col128) * (262144))
        ),
        eval!(
            context,
            ((m_limb_12_col129) + ((m_limb_13_col130) * (512))) + ((m_limb_14_col131) * (262144))
        ),
        eval!(
            context,
            ((m_limb_15_col132) + ((m_limb_16_col133) * (512))) + ((m_limb_17_col134) * (262144))
        ),
        eval!(
            context,
            ((m_limb_18_col135) + ((m_limb_19_col136) * (512))) + ((m_limb_20_col137) * (262144))
        ),
        eval!(
            context,
            ((m_limb_21_col138) + ((m_limb_22_col139) * (512))) + ((m_limb_23_col140) * (262144))
        ),
        eval!(
            context,
            ((m_limb_24_col141) + ((m_limb_25_col142) * (512))) + ((m_limb_26_col143) * (262144))
        ),
        eval!(context, m_limb_27_col144),
        eval!(context, q_x_limb_0_col59),
        eval!(context, q_x_limb_1_col60),
        eval!(context, q_x_limb_2_col61),
        eval!(context, q_x_limb_3_col62),
        eval!(context, q_x_limb_4_col63),
        eval!(context, q_x_limb_5_col64),
        eval!(context, q_x_limb_6_col65),
        eval!(context, q_x_limb_7_col66),
        eval!(context, q_x_limb_8_col67),
        eval!(context, q_x_limb_9_col68),
        eval!(context, q_x_limb_10_col69),
        eval!(context, q_x_limb_11_col70),
        eval!(context, q_x_limb_12_col71),
        eval!(context, q_x_limb_13_col72),
        eval!(context, q_x_limb_14_col73),
        eval!(context, q_x_limb_15_col74),
        eval!(context, q_x_limb_16_col75),
        eval!(context, q_x_limb_17_col76),
        eval!(context, q_x_limb_18_col77),
        eval!(context, q_x_limb_19_col78),
        eval!(context, q_x_limb_20_col79),
        eval!(context, q_x_limb_21_col80),
        eval!(context, q_x_limb_22_col81),
        eval!(context, q_x_limb_23_col82),
        eval!(context, q_x_limb_24_col83),
        eval!(context, q_x_limb_25_col84),
        eval!(context, q_x_limb_26_col85),
        eval!(context, q_x_limb_27_col86),
        eval!(context, q_y_limb_0_col88),
        eval!(context, q_y_limb_1_col89),
        eval!(context, q_y_limb_2_col90),
        eval!(context, q_y_limb_3_col91),
        eval!(context, q_y_limb_4_col92),
        eval!(context, q_y_limb_5_col93),
        eval!(context, q_y_limb_6_col94),
        eval!(context, q_y_limb_7_col95),
        eval!(context, q_y_limb_8_col96),
        eval!(context, q_y_limb_9_col97),
        eval!(context, q_y_limb_10_col98),
        eval!(context, q_y_limb_11_col99),
        eval!(context, q_y_limb_12_col100),
        eval!(context, q_y_limb_13_col101),
        eval!(context, q_y_limb_14_col102),
        eval!(context, q_y_limb_15_col103),
        eval!(context, q_y_limb_16_col104),
        eval!(context, q_y_limb_17_col105),
        eval!(context, q_y_limb_18_col106),
        eval!(context, q_y_limb_19_col107),
        eval!(context, q_y_limb_20_col108),
        eval!(context, q_y_limb_21_col109),
        eval!(context, q_y_limb_22_col110),
        eval!(context, q_y_limb_23_col111),
        eval!(context, q_y_limb_24_col112),
        eval!(context, q_y_limb_25_col113),
        eval!(context, q_y_limb_26_col114),
        eval!(context, q_y_limb_27_col115),
        eval!(context, p_x_limb_0_col1),
        eval!(context, p_x_limb_1_col2),
        eval!(context, p_x_limb_2_col3),
        eval!(context, p_x_limb_3_col4),
        eval!(context, p_x_limb_4_col5),
        eval!(context, p_x_limb_5_col6),
        eval!(context, p_x_limb_6_col7),
        eval!(context, p_x_limb_7_col8),
        eval!(context, p_x_limb_8_col9),
        eval!(context, p_x_limb_9_col10),
        eval!(context, p_x_limb_10_col11),
        eval!(context, p_x_limb_11_col12),
        eval!(context, p_x_limb_12_col13),
        eval!(context, p_x_limb_13_col14),
        eval!(context, p_x_limb_14_col15),
        eval!(context, p_x_limb_15_col16),
        eval!(context, p_x_limb_16_col17),
        eval!(context, p_x_limb_17_col18),
        eval!(context, p_x_limb_18_col19),
        eval!(context, p_x_limb_19_col20),
        eval!(context, p_x_limb_20_col21),
        eval!(context, p_x_limb_21_col22),
        eval!(context, p_x_limb_22_col23),
        eval!(context, p_x_limb_23_col24),
        eval!(context, p_x_limb_24_col25),
        eval!(context, p_x_limb_25_col26),
        eval!(context, p_x_limb_26_col27),
        eval!(context, p_x_limb_27_col28),
        eval!(context, p_y_limb_0_col30),
        eval!(context, p_y_limb_1_col31),
        eval!(context, p_y_limb_2_col32),
        eval!(context, p_y_limb_3_col33),
        eval!(context, p_y_limb_4_col34),
        eval!(context, p_y_limb_5_col35),
        eval!(context, p_y_limb_6_col36),
        eval!(context, p_y_limb_7_col37),
        eval!(context, p_y_limb_8_col38),
        eval!(context, p_y_limb_9_col39),
        eval!(context, p_y_limb_10_col40),
        eval!(context, p_y_limb_11_col41),
        eval!(context, p_y_limb_12_col42),
        eval!(context, p_y_limb_13_col43),
        eval!(context, p_y_limb_14_col44),
        eval!(context, p_y_limb_15_col45),
        eval!(context, p_y_limb_16_col46),
        eval!(context, p_y_limb_17_col47),
        eval!(context, p_y_limb_18_col48),
        eval!(context, p_y_limb_19_col49),
        eval!(context, p_y_limb_20_col50),
        eval!(context, p_y_limb_21_col51),
        eval!(context, p_y_limb_22_col52),
        eval!(context, p_y_limb_23_col53),
        eval!(context, p_y_limb_24_col54),
        eval!(context, p_y_limb_25_col55),
        eval!(context, p_y_limb_26_col56),
        eval!(context, p_y_limb_27_col57),
        eval!(context, 26),
    ];
    let numerator_7 = eval!(context, -(1));
    acc.add_to_relation(context, numerator_7, tuple_7);

    // Use PartialEcMulGeneric.
    let tuple_8 = &[
        eval!(context, 183619546),
        eval!(context, seq),
        eval!(context, 252),
        eval!(context, partial_ec_mul_generic_output_m_limb_0_col148),
        eval!(context, partial_ec_mul_generic_output_m_limb_1_col149),
        eval!(context, partial_ec_mul_generic_output_m_limb_2_col150),
        eval!(context, partial_ec_mul_generic_output_m_limb_3_col151),
        eval!(context, partial_ec_mul_generic_output_m_limb_4_col152),
        eval!(context, partial_ec_mul_generic_output_m_limb_5_col153),
        eval!(context, partial_ec_mul_generic_output_m_limb_6_col154),
        eval!(context, partial_ec_mul_generic_output_m_limb_7_col155),
        eval!(context, partial_ec_mul_generic_output_m_limb_8_col156),
        eval!(context, partial_ec_mul_generic_output_m_limb_9_col157),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_0_col158),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_1_col159),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_2_col160),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_3_col161),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_4_col162),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_5_col163),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_6_col164),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_7_col165),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_8_col166),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_9_col167),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_10_col168),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_11_col169),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_12_col170),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_13_col171),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_14_col172),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_15_col173),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_16_col174),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_17_col175),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_18_col176),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_19_col177),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_20_col178),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_21_col179),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_22_col180),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_23_col181),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_24_col182),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_25_col183),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_26_col184),
        eval!(context, partial_ec_mul_generic_output_q_x_limb_27_col185),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_0_col186),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_1_col187),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_2_col188),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_3_col189),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_4_col190),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_5_col191),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_6_col192),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_7_col193),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_8_col194),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_9_col195),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_10_col196),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_11_col197),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_12_col198),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_13_col199),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_14_col200),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_15_col201),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_16_col202),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_17_col203),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_18_col204),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_19_col205),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_20_col206),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_21_col207),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_22_col208),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_23_col209),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_24_col210),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_25_col211),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_26_col212),
        eval!(context, partial_ec_mul_generic_output_q_y_limb_27_col213),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_0_col214),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_1_col215),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_2_col216),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_3_col217),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_4_col218),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_5_col219),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_6_col220),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_7_col221),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_8_col222),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_9_col223),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_10_col224),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_11_col225),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_12_col226),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_13_col227),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_14_col228),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_15_col229),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_16_col230),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_17_col231),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_18_col232),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_19_col233),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_20_col234),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_21_col235),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_22_col236),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_23_col237),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_24_col238),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_25_col239),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_26_col240),
        eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_27_col241),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_0_col242),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_1_col243),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_2_col244),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_3_col245),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_4_col246),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_5_col247),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_6_col248),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_7_col249),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_8_col250),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_9_col251),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_10_col252),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_11_col253),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_12_col254),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_13_col255),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_14_col256),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_15_col257),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_16_col258),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_17_col259),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_18_col260),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_19_col261),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_20_col262),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_21_col263),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_22_col264),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_23_col265),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_24_col266),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_25_col267),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_26_col268),
        eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_27_col269),
        eval!(context, partial_ec_mul_generic_output_counter_col270),
    ];
    let numerator_8 = eval!(context, 1);
    acc.add_to_relation(context, numerator_8, tuple_8);

    //final m is zero.
    let constraint_9_value = eval!(context, partial_ec_mul_generic_output_m_limb_0_col148);
    acc.add_constraint(context, constraint_9_value);

    mem_verify::accumulate_constraints(
        &[
            eval!(context, (instance_addr_tmp_45259_0) + (5)),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_0_col214),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_1_col215),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_2_col216),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_3_col217),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_4_col218),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_5_col219),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_6_col220),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_7_col221),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_8_col222),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_9_col223),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_10_col224),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_11_col225),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_12_col226),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_13_col227),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_14_col228),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_15_col229),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_16_col230),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_17_col231),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_18_col232),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_19_col233),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_20_col234),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_21_col235),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_22_col236),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_23_col237),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_24_col238),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_25_col239),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_26_col240),
            eval!(context, partial_ec_mul_generic_output_accumulator_x_limb_27_col241),
            eval!(context, res_x_id_col271),
        ],
        context,
        component_data,
        acc,
    );

    mem_verify::accumulate_constraints(
        &[
            eval!(context, (instance_addr_tmp_45259_0) + (6)),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_0_col242),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_1_col243),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_2_col244),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_3_col245),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_4_col246),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_5_col247),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_6_col248),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_7_col249),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_8_col250),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_9_col251),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_10_col252),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_11_col253),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_12_col254),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_13_col255),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_14_col256),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_15_col257),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_16_col258),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_17_col259),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_18_col260),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_19_col261),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_20_col262),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_21_col263),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_22_col264),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_23_col265),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_24_col266),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_25_col267),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_26_col268),
            eval!(context, partial_ec_mul_generic_output_accumulator_y_limb_27_col269),
            eval!(context, res_y_id_col272),
        ],
        context,
        component_data,
        acc,
    );
}

pub struct Component {}
impl<Value: IValue> CircuitEval<Value> for Component {
    fn evaluate(
        &self,
        context: &mut Context<Value>,
        component_data: &ComponentData<'_>,
        acc: &mut CompositionConstraintAccumulator,
    ) {
        accumulate_constraints(component_data.trace_columns, context, component_data, acc);
    }

    fn trace_columns(&self) -> usize {
        N_TRACE_COLUMNS
    }

    fn interaction_columns(&self) -> usize {
        N_INTERACTION_COLUMNS
    }

    fn relation_uses_per_row(&self) -> &[RelationUse] {
        &RELATION_USES_PER_ROW
    }
}
