// This file was created by the AIR team.

use crate::cairo_air::components::prelude::*;

pub const N_TRACE_COLUMNS: usize = 243;
pub const N_INTERACTION_COLUMNS: usize = 136;

pub const RELATION_USES_PER_ROW: [RelationUse; 22] = [
    RelationUse { relation_id: "MemoryAddressToId", uses: 3 },
    RelationUse { relation_id: "MemoryIdToBig", uses: 3 },
    RelationUse { relation_id: "Opcodes", uses: 1 },
    RelationUse { relation_id: "RangeCheck_11", uses: 1 },
    RelationUse { relation_id: "RangeCheck_18", uses: 1 },
    RelationUse { relation_id: "RangeCheck_20", uses: 4 },
    RelationUse { relation_id: "RangeCheck_20_B", uses: 4 },
    RelationUse { relation_id: "RangeCheck_20_C", uses: 4 },
    RelationUse { relation_id: "RangeCheck_20_D", uses: 4 },
    RelationUse { relation_id: "RangeCheck_20_E", uses: 3 },
    RelationUse { relation_id: "RangeCheck_20_F", uses: 3 },
    RelationUse { relation_id: "RangeCheck_20_G", uses: 3 },
    RelationUse { relation_id: "RangeCheck_20_H", uses: 3 },
    RelationUse { relation_id: "RangeCheck_9_9", uses: 4 },
    RelationUse { relation_id: "RangeCheck_9_9_B", uses: 4 },
    RelationUse { relation_id: "RangeCheck_9_9_C", uses: 4 },
    RelationUse { relation_id: "RangeCheck_9_9_D", uses: 4 },
    RelationUse { relation_id: "RangeCheck_9_9_E", uses: 4 },
    RelationUse { relation_id: "RangeCheck_9_9_F", uses: 4 },
    RelationUse { relation_id: "RangeCheck_9_9_G", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_H", uses: 2 },
    RelationUse { relation_id: "VerifyInstruction", uses: 1 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints(
    input: &[Var],
    context: &mut Context<impl IValue>,
    component_data: &ComponentData<'_>,
    acc: &mut CompositionConstraintAccumulator,
) {
    let _ = component_data;
    let _ = acc;
    let [
        input_pc_col0,
        input_ap_col1,
        input_fp_col2,
        offset0_col3,
        offset1_col4,
        offset2_col5,
        dst_base_fp_col6,
        op0_base_fp_col7,
        op1_imm_col8,
        op1_base_fp_col9,
        op1_base_ap_col10,
        res_add_col11,
        res_mul_col12,
        pc_update_jump_col13,
        pc_update_jump_rel_col14,
        pc_update_jnz_col15,
        ap_update_add_col16,
        ap_update_add_1_col17,
        opcode_call_col18,
        opcode_ret_col19,
        opcode_assert_eq_col20,
        dst_src_col21,
        dst_id_col22,
        dst_limb_0_col23,
        dst_limb_1_col24,
        dst_limb_2_col25,
        dst_limb_3_col26,
        dst_limb_4_col27,
        dst_limb_5_col28,
        dst_limb_6_col29,
        dst_limb_7_col30,
        dst_limb_8_col31,
        dst_limb_9_col32,
        dst_limb_10_col33,
        dst_limb_11_col34,
        dst_limb_12_col35,
        dst_limb_13_col36,
        dst_limb_14_col37,
        dst_limb_15_col38,
        dst_limb_16_col39,
        dst_limb_17_col40,
        dst_limb_18_col41,
        dst_limb_19_col42,
        dst_limb_20_col43,
        dst_limb_21_col44,
        dst_limb_22_col45,
        dst_limb_23_col46,
        dst_limb_24_col47,
        dst_limb_25_col48,
        dst_limb_26_col49,
        dst_limb_27_col50,
        op0_src_col51,
        op0_id_col52,
        op0_limb_0_col53,
        op0_limb_1_col54,
        op0_limb_2_col55,
        op0_limb_3_col56,
        op0_limb_4_col57,
        op0_limb_5_col58,
        op0_limb_6_col59,
        op0_limb_7_col60,
        op0_limb_8_col61,
        op0_limb_9_col62,
        op0_limb_10_col63,
        op0_limb_11_col64,
        op0_limb_12_col65,
        op0_limb_13_col66,
        op0_limb_14_col67,
        op0_limb_15_col68,
        op0_limb_16_col69,
        op0_limb_17_col70,
        op0_limb_18_col71,
        op0_limb_19_col72,
        op0_limb_20_col73,
        op0_limb_21_col74,
        op0_limb_22_col75,
        op0_limb_23_col76,
        op0_limb_24_col77,
        op0_limb_25_col78,
        op0_limb_26_col79,
        op0_limb_27_col80,
        partial_limb_msb_col81,
        op1_src_col82,
        op1_id_col83,
        op1_limb_0_col84,
        op1_limb_1_col85,
        op1_limb_2_col86,
        op1_limb_3_col87,
        op1_limb_4_col88,
        op1_limb_5_col89,
        op1_limb_6_col90,
        op1_limb_7_col91,
        op1_limb_8_col92,
        op1_limb_9_col93,
        op1_limb_10_col94,
        op1_limb_11_col95,
        op1_limb_12_col96,
        op1_limb_13_col97,
        op1_limb_14_col98,
        op1_limb_15_col99,
        op1_limb_16_col100,
        op1_limb_17_col101,
        op1_limb_18_col102,
        op1_limb_19_col103,
        op1_limb_20_col104,
        op1_limb_21_col105,
        op1_limb_22_col106,
        op1_limb_23_col107,
        op1_limb_24_col108,
        op1_limb_25_col109,
        op1_limb_26_col110,
        op1_limb_27_col111,
        add_res_limb_0_col112,
        add_res_limb_1_col113,
        add_res_limb_2_col114,
        add_res_limb_3_col115,
        add_res_limb_4_col116,
        add_res_limb_5_col117,
        add_res_limb_6_col118,
        add_res_limb_7_col119,
        add_res_limb_8_col120,
        add_res_limb_9_col121,
        add_res_limb_10_col122,
        add_res_limb_11_col123,
        add_res_limb_12_col124,
        add_res_limb_13_col125,
        add_res_limb_14_col126,
        add_res_limb_15_col127,
        add_res_limb_16_col128,
        add_res_limb_17_col129,
        add_res_limb_18_col130,
        add_res_limb_19_col131,
        add_res_limb_20_col132,
        add_res_limb_21_col133,
        add_res_limb_22_col134,
        add_res_limb_23_col135,
        add_res_limb_24_col136,
        add_res_limb_25_col137,
        add_res_limb_26_col138,
        add_res_limb_27_col139,
        sub_p_bit_col140,
        mul_res_limb_0_col141,
        mul_res_limb_1_col142,
        mul_res_limb_2_col143,
        mul_res_limb_3_col144,
        mul_res_limb_4_col145,
        mul_res_limb_5_col146,
        mul_res_limb_6_col147,
        mul_res_limb_7_col148,
        mul_res_limb_8_col149,
        mul_res_limb_9_col150,
        mul_res_limb_10_col151,
        mul_res_limb_11_col152,
        mul_res_limb_12_col153,
        mul_res_limb_13_col154,
        mul_res_limb_14_col155,
        mul_res_limb_15_col156,
        mul_res_limb_16_col157,
        mul_res_limb_17_col158,
        mul_res_limb_18_col159,
        mul_res_limb_19_col160,
        mul_res_limb_20_col161,
        mul_res_limb_21_col162,
        mul_res_limb_22_col163,
        mul_res_limb_23_col164,
        mul_res_limb_24_col165,
        mul_res_limb_25_col166,
        mul_res_limb_26_col167,
        mul_res_limb_27_col168,
        k_col169,
        carry_0_col170,
        carry_1_col171,
        carry_2_col172,
        carry_3_col173,
        carry_4_col174,
        carry_5_col175,
        carry_6_col176,
        carry_7_col177,
        carry_8_col178,
        carry_9_col179,
        carry_10_col180,
        carry_11_col181,
        carry_12_col182,
        carry_13_col183,
        carry_14_col184,
        carry_15_col185,
        carry_16_col186,
        carry_17_col187,
        carry_18_col188,
        carry_19_col189,
        carry_20_col190,
        carry_21_col191,
        carry_22_col192,
        carry_23_col193,
        carry_24_col194,
        carry_25_col195,
        carry_26_col196,
        res_limb_0_col197,
        res_limb_1_col198,
        res_limb_2_col199,
        res_limb_3_col200,
        res_limb_4_col201,
        res_limb_5_col202,
        res_limb_6_col203,
        res_limb_7_col204,
        res_limb_8_col205,
        res_limb_9_col206,
        res_limb_10_col207,
        res_limb_11_col208,
        res_limb_12_col209,
        res_limb_13_col210,
        res_limb_14_col211,
        res_limb_15_col212,
        res_limb_16_col213,
        res_limb_17_col214,
        res_limb_18_col215,
        res_limb_19_col216,
        res_limb_20_col217,
        res_limb_21_col218,
        res_limb_22_col219,
        res_limb_23_col220,
        res_limb_24_col221,
        res_limb_25_col222,
        res_limb_26_col223,
        res_limb_27_col224,
        partial_limb_msb_col225,
        partial_limb_msb_col226,
        partial_limb_msb_col227,
        msb_col228,
        mid_limbs_set_col229,
        partial_limb_msb_col230,
        dst_sum_squares_inv_col231,
        dst_sum_inv_col232,
        op1_as_rel_imm_cond_col233,
        msb_col234,
        mid_limbs_set_col235,
        partial_limb_msb_col236,
        next_pc_jnz_col237,
        next_pc_col238,
        next_ap_col239,
        range_check_29_bot11bits_col240,
        next_fp_col241,
        enabler,
    ] = input.try_into().unwrap();
    let enabler_constraint_value = eval!(context, ((enabler) * (enabler)) - (enabler));
    acc.add_constraint(context, enabler_constraint_value);

    let [
        decode_generic_instruction_output_tmp_57455_26_op1_base_op0,
        decode_generic_instruction_output_tmp_57455_26_res_op1,
        decode_generic_instruction_output_tmp_57455_26_pc_update_regular,
        decode_generic_instruction_output_tmp_57455_26_fp_update_regular,
        decode_generic_instruction_output_tmp_57455_26_instruction_size,
        decode_generic_instruction_output_tmp_57455_26_offset0,
        decode_generic_instruction_output_tmp_57455_26_offset1,
        decode_generic_instruction_output_tmp_57455_26_offset2,
    ] = decode_generic_instruction::accumulate_constraints(
        &[
            eval!(context, input_pc_col0),
            eval!(context, offset0_col3),
            eval!(context, offset1_col4),
            eval!(context, offset2_col5),
            eval!(context, dst_base_fp_col6),
            eval!(context, op0_base_fp_col7),
            eval!(context, op1_imm_col8),
            eval!(context, op1_base_fp_col9),
            eval!(context, op1_base_ap_col10),
            eval!(context, res_add_col11),
            eval!(context, res_mul_col12),
            eval!(context, pc_update_jump_col13),
            eval!(context, pc_update_jump_rel_col14),
            eval!(context, pc_update_jnz_col15),
            eval!(context, ap_update_add_col16),
            eval!(context, ap_update_add_1_col17),
            eval!(context, opcode_call_col18),
            eval!(context, opcode_ret_col19),
            eval!(context, opcode_assert_eq_col20),
        ],
        context,
        component_data,
        acc,
    )
    .try_into()
    .unwrap();

    eval_operands::accumulate_constraints(
        &[
            eval!(context, input_pc_col0),
            eval!(context, input_ap_col1),
            eval!(context, input_fp_col2),
            eval!(context, dst_base_fp_col6),
            eval!(context, op0_base_fp_col7),
            eval!(context, op1_imm_col8),
            eval!(context, op1_base_fp_col9),
            eval!(context, op1_base_ap_col10),
            eval!(context, res_add_col11),
            eval!(context, res_mul_col12),
            eval!(context, pc_update_jnz_col15),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_op1_base_op0),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_res_op1),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_offset0),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_offset1),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_offset2),
            eval!(context, dst_src_col21),
            eval!(context, dst_id_col22),
            eval!(context, dst_limb_0_col23),
            eval!(context, dst_limb_1_col24),
            eval!(context, dst_limb_2_col25),
            eval!(context, dst_limb_3_col26),
            eval!(context, dst_limb_4_col27),
            eval!(context, dst_limb_5_col28),
            eval!(context, dst_limb_6_col29),
            eval!(context, dst_limb_7_col30),
            eval!(context, dst_limb_8_col31),
            eval!(context, dst_limb_9_col32),
            eval!(context, dst_limb_10_col33),
            eval!(context, dst_limb_11_col34),
            eval!(context, dst_limb_12_col35),
            eval!(context, dst_limb_13_col36),
            eval!(context, dst_limb_14_col37),
            eval!(context, dst_limb_15_col38),
            eval!(context, dst_limb_16_col39),
            eval!(context, dst_limb_17_col40),
            eval!(context, dst_limb_18_col41),
            eval!(context, dst_limb_19_col42),
            eval!(context, dst_limb_20_col43),
            eval!(context, dst_limb_21_col44),
            eval!(context, dst_limb_22_col45),
            eval!(context, dst_limb_23_col46),
            eval!(context, dst_limb_24_col47),
            eval!(context, dst_limb_25_col48),
            eval!(context, dst_limb_26_col49),
            eval!(context, dst_limb_27_col50),
            eval!(context, op0_src_col51),
            eval!(context, op0_id_col52),
            eval!(context, op0_limb_0_col53),
            eval!(context, op0_limb_1_col54),
            eval!(context, op0_limb_2_col55),
            eval!(context, op0_limb_3_col56),
            eval!(context, op0_limb_4_col57),
            eval!(context, op0_limb_5_col58),
            eval!(context, op0_limb_6_col59),
            eval!(context, op0_limb_7_col60),
            eval!(context, op0_limb_8_col61),
            eval!(context, op0_limb_9_col62),
            eval!(context, op0_limb_10_col63),
            eval!(context, op0_limb_11_col64),
            eval!(context, op0_limb_12_col65),
            eval!(context, op0_limb_13_col66),
            eval!(context, op0_limb_14_col67),
            eval!(context, op0_limb_15_col68),
            eval!(context, op0_limb_16_col69),
            eval!(context, op0_limb_17_col70),
            eval!(context, op0_limb_18_col71),
            eval!(context, op0_limb_19_col72),
            eval!(context, op0_limb_20_col73),
            eval!(context, op0_limb_21_col74),
            eval!(context, op0_limb_22_col75),
            eval!(context, op0_limb_23_col76),
            eval!(context, op0_limb_24_col77),
            eval!(context, op0_limb_25_col78),
            eval!(context, op0_limb_26_col79),
            eval!(context, op0_limb_27_col80),
            eval!(context, partial_limb_msb_col81),
            eval!(context, op1_src_col82),
            eval!(context, op1_id_col83),
            eval!(context, op1_limb_0_col84),
            eval!(context, op1_limb_1_col85),
            eval!(context, op1_limb_2_col86),
            eval!(context, op1_limb_3_col87),
            eval!(context, op1_limb_4_col88),
            eval!(context, op1_limb_5_col89),
            eval!(context, op1_limb_6_col90),
            eval!(context, op1_limb_7_col91),
            eval!(context, op1_limb_8_col92),
            eval!(context, op1_limb_9_col93),
            eval!(context, op1_limb_10_col94),
            eval!(context, op1_limb_11_col95),
            eval!(context, op1_limb_12_col96),
            eval!(context, op1_limb_13_col97),
            eval!(context, op1_limb_14_col98),
            eval!(context, op1_limb_15_col99),
            eval!(context, op1_limb_16_col100),
            eval!(context, op1_limb_17_col101),
            eval!(context, op1_limb_18_col102),
            eval!(context, op1_limb_19_col103),
            eval!(context, op1_limb_20_col104),
            eval!(context, op1_limb_21_col105),
            eval!(context, op1_limb_22_col106),
            eval!(context, op1_limb_23_col107),
            eval!(context, op1_limb_24_col108),
            eval!(context, op1_limb_25_col109),
            eval!(context, op1_limb_26_col110),
            eval!(context, op1_limb_27_col111),
            eval!(context, add_res_limb_0_col112),
            eval!(context, add_res_limb_1_col113),
            eval!(context, add_res_limb_2_col114),
            eval!(context, add_res_limb_3_col115),
            eval!(context, add_res_limb_4_col116),
            eval!(context, add_res_limb_5_col117),
            eval!(context, add_res_limb_6_col118),
            eval!(context, add_res_limb_7_col119),
            eval!(context, add_res_limb_8_col120),
            eval!(context, add_res_limb_9_col121),
            eval!(context, add_res_limb_10_col122),
            eval!(context, add_res_limb_11_col123),
            eval!(context, add_res_limb_12_col124),
            eval!(context, add_res_limb_13_col125),
            eval!(context, add_res_limb_14_col126),
            eval!(context, add_res_limb_15_col127),
            eval!(context, add_res_limb_16_col128),
            eval!(context, add_res_limb_17_col129),
            eval!(context, add_res_limb_18_col130),
            eval!(context, add_res_limb_19_col131),
            eval!(context, add_res_limb_20_col132),
            eval!(context, add_res_limb_21_col133),
            eval!(context, add_res_limb_22_col134),
            eval!(context, add_res_limb_23_col135),
            eval!(context, add_res_limb_24_col136),
            eval!(context, add_res_limb_25_col137),
            eval!(context, add_res_limb_26_col138),
            eval!(context, add_res_limb_27_col139),
            eval!(context, sub_p_bit_col140),
            eval!(context, mul_res_limb_0_col141),
            eval!(context, mul_res_limb_1_col142),
            eval!(context, mul_res_limb_2_col143),
            eval!(context, mul_res_limb_3_col144),
            eval!(context, mul_res_limb_4_col145),
            eval!(context, mul_res_limb_5_col146),
            eval!(context, mul_res_limb_6_col147),
            eval!(context, mul_res_limb_7_col148),
            eval!(context, mul_res_limb_8_col149),
            eval!(context, mul_res_limb_9_col150),
            eval!(context, mul_res_limb_10_col151),
            eval!(context, mul_res_limb_11_col152),
            eval!(context, mul_res_limb_12_col153),
            eval!(context, mul_res_limb_13_col154),
            eval!(context, mul_res_limb_14_col155),
            eval!(context, mul_res_limb_15_col156),
            eval!(context, mul_res_limb_16_col157),
            eval!(context, mul_res_limb_17_col158),
            eval!(context, mul_res_limb_18_col159),
            eval!(context, mul_res_limb_19_col160),
            eval!(context, mul_res_limb_20_col161),
            eval!(context, mul_res_limb_21_col162),
            eval!(context, mul_res_limb_22_col163),
            eval!(context, mul_res_limb_23_col164),
            eval!(context, mul_res_limb_24_col165),
            eval!(context, mul_res_limb_25_col166),
            eval!(context, mul_res_limb_26_col167),
            eval!(context, mul_res_limb_27_col168),
            eval!(context, k_col169),
            eval!(context, carry_0_col170),
            eval!(context, carry_1_col171),
            eval!(context, carry_2_col172),
            eval!(context, carry_3_col173),
            eval!(context, carry_4_col174),
            eval!(context, carry_5_col175),
            eval!(context, carry_6_col176),
            eval!(context, carry_7_col177),
            eval!(context, carry_8_col178),
            eval!(context, carry_9_col179),
            eval!(context, carry_10_col180),
            eval!(context, carry_11_col181),
            eval!(context, carry_12_col182),
            eval!(context, carry_13_col183),
            eval!(context, carry_14_col184),
            eval!(context, carry_15_col185),
            eval!(context, carry_16_col186),
            eval!(context, carry_17_col187),
            eval!(context, carry_18_col188),
            eval!(context, carry_19_col189),
            eval!(context, carry_20_col190),
            eval!(context, carry_21_col191),
            eval!(context, carry_22_col192),
            eval!(context, carry_23_col193),
            eval!(context, carry_24_col194),
            eval!(context, carry_25_col195),
            eval!(context, carry_26_col196),
            eval!(context, res_limb_0_col197),
            eval!(context, res_limb_1_col198),
            eval!(context, res_limb_2_col199),
            eval!(context, res_limb_3_col200),
            eval!(context, res_limb_4_col201),
            eval!(context, res_limb_5_col202),
            eval!(context, res_limb_6_col203),
            eval!(context, res_limb_7_col204),
            eval!(context, res_limb_8_col205),
            eval!(context, res_limb_9_col206),
            eval!(context, res_limb_10_col207),
            eval!(context, res_limb_11_col208),
            eval!(context, res_limb_12_col209),
            eval!(context, res_limb_13_col210),
            eval!(context, res_limb_14_col211),
            eval!(context, res_limb_15_col212),
            eval!(context, res_limb_16_col213),
            eval!(context, res_limb_17_col214),
            eval!(context, res_limb_18_col215),
            eval!(context, res_limb_19_col216),
            eval!(context, res_limb_20_col217),
            eval!(context, res_limb_21_col218),
            eval!(context, res_limb_22_col219),
            eval!(context, res_limb_23_col220),
            eval!(context, res_limb_24_col221),
            eval!(context, res_limb_25_col222),
            eval!(context, res_limb_26_col223),
            eval!(context, res_limb_27_col224),
        ],
        context,
        component_data,
        acc,
    );

    handle_opcodes::accumulate_constraints(
        &[
            eval!(context, input_pc_col0),
            eval!(context, input_fp_col2),
            eval!(context, dst_base_fp_col6),
            eval!(context, op0_base_fp_col7),
            eval!(context, op1_base_fp_col9),
            eval!(context, pc_update_jump_col13),
            eval!(context, opcode_call_col18),
            eval!(context, opcode_ret_col19),
            eval!(context, opcode_assert_eq_col20),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_res_op1),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_instruction_size),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_offset0),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_offset1),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_offset2),
            eval!(context, dst_limb_0_col23),
            eval!(context, dst_limb_1_col24),
            eval!(context, dst_limb_2_col25),
            eval!(context, dst_limb_3_col26),
            eval!(context, dst_limb_4_col27),
            eval!(context, dst_limb_5_col28),
            eval!(context, dst_limb_6_col29),
            eval!(context, dst_limb_7_col30),
            eval!(context, dst_limb_8_col31),
            eval!(context, dst_limb_9_col32),
            eval!(context, dst_limb_10_col33),
            eval!(context, dst_limb_11_col34),
            eval!(context, dst_limb_12_col35),
            eval!(context, dst_limb_13_col36),
            eval!(context, dst_limb_14_col37),
            eval!(context, dst_limb_15_col38),
            eval!(context, dst_limb_16_col39),
            eval!(context, dst_limb_17_col40),
            eval!(context, dst_limb_18_col41),
            eval!(context, dst_limb_19_col42),
            eval!(context, dst_limb_20_col43),
            eval!(context, dst_limb_21_col44),
            eval!(context, dst_limb_22_col45),
            eval!(context, dst_limb_23_col46),
            eval!(context, dst_limb_24_col47),
            eval!(context, dst_limb_25_col48),
            eval!(context, dst_limb_26_col49),
            eval!(context, dst_limb_27_col50),
            eval!(context, op0_limb_0_col53),
            eval!(context, op0_limb_1_col54),
            eval!(context, op0_limb_2_col55),
            eval!(context, op0_limb_3_col56),
            eval!(context, op0_limb_4_col57),
            eval!(context, op0_limb_5_col58),
            eval!(context, op0_limb_6_col59),
            eval!(context, op0_limb_7_col60),
            eval!(context, op0_limb_8_col61),
            eval!(context, op0_limb_9_col62),
            eval!(context, op0_limb_10_col63),
            eval!(context, op0_limb_11_col64),
            eval!(context, op0_limb_12_col65),
            eval!(context, op0_limb_13_col66),
            eval!(context, op0_limb_14_col67),
            eval!(context, op0_limb_15_col68),
            eval!(context, op0_limb_16_col69),
            eval!(context, op0_limb_17_col70),
            eval!(context, op0_limb_18_col71),
            eval!(context, op0_limb_19_col72),
            eval!(context, op0_limb_20_col73),
            eval!(context, op0_limb_21_col74),
            eval!(context, op0_limb_22_col75),
            eval!(context, op0_limb_23_col76),
            eval!(context, op0_limb_24_col77),
            eval!(context, op0_limb_25_col78),
            eval!(context, op0_limb_26_col79),
            eval!(context, op0_limb_27_col80),
            eval!(context, res_limb_0_col197),
            eval!(context, res_limb_1_col198),
            eval!(context, res_limb_2_col199),
            eval!(context, res_limb_3_col200),
            eval!(context, res_limb_4_col201),
            eval!(context, res_limb_5_col202),
            eval!(context, res_limb_6_col203),
            eval!(context, res_limb_7_col204),
            eval!(context, res_limb_8_col205),
            eval!(context, res_limb_9_col206),
            eval!(context, res_limb_10_col207),
            eval!(context, res_limb_11_col208),
            eval!(context, res_limb_12_col209),
            eval!(context, res_limb_13_col210),
            eval!(context, res_limb_14_col211),
            eval!(context, res_limb_15_col212),
            eval!(context, res_limb_16_col213),
            eval!(context, res_limb_17_col214),
            eval!(context, res_limb_18_col215),
            eval!(context, res_limb_19_col216),
            eval!(context, res_limb_20_col217),
            eval!(context, res_limb_21_col218),
            eval!(context, res_limb_22_col219),
            eval!(context, res_limb_23_col220),
            eval!(context, res_limb_24_col221),
            eval!(context, res_limb_25_col222),
            eval!(context, res_limb_26_col223),
            eval!(context, res_limb_27_col224),
            eval!(context, partial_limb_msb_col225),
            eval!(context, partial_limb_msb_col226),
        ],
        context,
        component_data,
        acc,
    );

    update_registers::accumulate_constraints(
        &[
            eval!(context, input_pc_col0),
            eval!(context, input_ap_col1),
            eval!(context, input_fp_col2),
            eval!(context, pc_update_jump_col13),
            eval!(context, pc_update_jump_rel_col14),
            eval!(context, pc_update_jnz_col15),
            eval!(context, ap_update_add_col16),
            eval!(context, ap_update_add_1_col17),
            eval!(context, opcode_call_col18),
            eval!(context, opcode_ret_col19),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_pc_update_regular),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_fp_update_regular),
            eval!(context, decode_generic_instruction_output_tmp_57455_26_instruction_size),
            eval!(context, dst_limb_0_col23),
            eval!(context, dst_limb_1_col24),
            eval!(context, dst_limb_2_col25),
            eval!(context, dst_limb_3_col26),
            eval!(context, dst_limb_4_col27),
            eval!(context, dst_limb_5_col28),
            eval!(context, dst_limb_6_col29),
            eval!(context, dst_limb_7_col30),
            eval!(context, dst_limb_8_col31),
            eval!(context, dst_limb_9_col32),
            eval!(context, dst_limb_10_col33),
            eval!(context, dst_limb_11_col34),
            eval!(context, dst_limb_12_col35),
            eval!(context, dst_limb_13_col36),
            eval!(context, dst_limb_14_col37),
            eval!(context, dst_limb_15_col38),
            eval!(context, dst_limb_16_col39),
            eval!(context, dst_limb_17_col40),
            eval!(context, dst_limb_18_col41),
            eval!(context, dst_limb_19_col42),
            eval!(context, dst_limb_20_col43),
            eval!(context, dst_limb_21_col44),
            eval!(context, dst_limb_22_col45),
            eval!(context, dst_limb_23_col46),
            eval!(context, dst_limb_24_col47),
            eval!(context, dst_limb_25_col48),
            eval!(context, dst_limb_26_col49),
            eval!(context, dst_limb_27_col50),
            eval!(context, op1_limb_0_col84),
            eval!(context, op1_limb_1_col85),
            eval!(context, op1_limb_2_col86),
            eval!(context, op1_limb_3_col87),
            eval!(context, op1_limb_4_col88),
            eval!(context, op1_limb_5_col89),
            eval!(context, op1_limb_6_col90),
            eval!(context, op1_limb_7_col91),
            eval!(context, op1_limb_8_col92),
            eval!(context, op1_limb_9_col93),
            eval!(context, op1_limb_10_col94),
            eval!(context, op1_limb_11_col95),
            eval!(context, op1_limb_12_col96),
            eval!(context, op1_limb_13_col97),
            eval!(context, op1_limb_14_col98),
            eval!(context, op1_limb_15_col99),
            eval!(context, op1_limb_16_col100),
            eval!(context, op1_limb_17_col101),
            eval!(context, op1_limb_18_col102),
            eval!(context, op1_limb_19_col103),
            eval!(context, op1_limb_20_col104),
            eval!(context, op1_limb_21_col105),
            eval!(context, op1_limb_22_col106),
            eval!(context, op1_limb_23_col107),
            eval!(context, op1_limb_24_col108),
            eval!(context, op1_limb_25_col109),
            eval!(context, op1_limb_26_col110),
            eval!(context, op1_limb_27_col111),
            eval!(context, res_limb_0_col197),
            eval!(context, res_limb_1_col198),
            eval!(context, res_limb_2_col199),
            eval!(context, res_limb_3_col200),
            eval!(context, res_limb_4_col201),
            eval!(context, res_limb_5_col202),
            eval!(context, res_limb_6_col203),
            eval!(context, res_limb_7_col204),
            eval!(context, res_limb_8_col205),
            eval!(context, res_limb_9_col206),
            eval!(context, res_limb_10_col207),
            eval!(context, res_limb_11_col208),
            eval!(context, res_limb_12_col209),
            eval!(context, res_limb_13_col210),
            eval!(context, res_limb_14_col211),
            eval!(context, res_limb_15_col212),
            eval!(context, res_limb_16_col213),
            eval!(context, res_limb_17_col214),
            eval!(context, res_limb_18_col215),
            eval!(context, res_limb_19_col216),
            eval!(context, res_limb_20_col217),
            eval!(context, res_limb_21_col218),
            eval!(context, res_limb_22_col219),
            eval!(context, res_limb_23_col220),
            eval!(context, res_limb_24_col221),
            eval!(context, res_limb_25_col222),
            eval!(context, res_limb_26_col223),
            eval!(context, res_limb_27_col224),
            eval!(context, partial_limb_msb_col227),
            eval!(context, msb_col228),
            eval!(context, mid_limbs_set_col229),
            eval!(context, partial_limb_msb_col230),
            eval!(context, dst_sum_squares_inv_col231),
            eval!(context, dst_sum_inv_col232),
            eval!(context, op1_as_rel_imm_cond_col233),
            eval!(context, msb_col234),
            eval!(context, mid_limbs_set_col235),
            eval!(context, partial_limb_msb_col236),
            eval!(context, next_pc_jnz_col237),
            eval!(context, next_pc_col238),
            eval!(context, next_ap_col239),
            eval!(context, range_check_29_bot11bits_col240),
            eval!(context, next_fp_col241),
        ],
        context,
        component_data,
        acc,
    );

    // Use Opcodes.
    let tuple_4 = &[
        eval!(context, 428564188),
        eval!(context, input_pc_col0),
        eval!(context, input_ap_col1),
        eval!(context, input_fp_col2),
    ];
    let numerator_4 = eval!(context, enabler);
    acc.add_to_relation(context, numerator_4, tuple_4);

    // Yield Opcodes.
    let tuple_5 = &[
        eval!(context, 428564188),
        eval!(context, next_pc_col238),
        eval!(context, next_ap_col239),
        eval!(context, next_fp_col241),
    ];
    let numerator_5 = eval!(context, -(enabler));
    acc.add_to_relation(context, numerator_5, tuple_5);
}

pub struct Component {}
impl<Value: IValue> CircuitEval<Value> for Component {
    fn evaluate(
        &self,
        context: &mut Context<Value>,
        component_data: &ComponentData<'_>,
        acc: &mut CompositionConstraintAccumulator,
    ) {
        accumulate_constraints(component_data.trace_columns, context, component_data, acc);
    }

    fn trace_columns(&self) -> usize {
        N_TRACE_COLUMNS
    }

    fn interaction_columns(&self) -> usize {
        N_INTERACTION_COLUMNS
    }

    fn relation_uses_per_row(&self) -> &[RelationUse] {
        &RELATION_USES_PER_ROW
    }
}
