// This file was created by the AIR team.

use crate::cairo_air::components::prelude::*;

pub const N_TRACE_COLUMNS: usize = 297;
pub const N_INTERACTION_COLUMNS: usize = 260;

pub const RELATION_USES_PER_ROW: [RelationUse; 18] = [
    RelationUse { relation_id: "PartialEcMulWindowBits18", uses: 1 },
    RelationUse { relation_id: "PedersenPointsTableWindowBits18", uses: 1 },
    RelationUse { relation_id: "RangeCheck_20", uses: 12 },
    RelationUse { relation_id: "RangeCheck_20_B", uses: 12 },
    RelationUse { relation_id: "RangeCheck_20_C", uses: 12 },
    RelationUse { relation_id: "RangeCheck_20_D", uses: 12 },
    RelationUse { relation_id: "RangeCheck_20_E", uses: 9 },
    RelationUse { relation_id: "RangeCheck_20_F", uses: 9 },
    RelationUse { relation_id: "RangeCheck_20_G", uses: 9 },
    RelationUse { relation_id: "RangeCheck_20_H", uses: 9 },
    RelationUse { relation_id: "RangeCheck_9_9", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_B", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_C", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_D", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_E", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_F", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_G", uses: 3 },
    RelationUse { relation_id: "RangeCheck_9_9_H", uses: 3 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints(
    input: &[Var],
    context: &mut Context<impl IValue>,
    component_data: &ComponentData<'_>,
    acc: &mut CompositionConstraintAccumulator,
) {
    let [
        input_limb_0_col0,
        input_limb_1_col1,
        input_limb_2_col2,
        input_limb_3_col3,
        input_limb_4_col4,
        input_limb_5_col5,
        input_limb_6_col6,
        input_limb_7_col7,
        input_limb_8_col8,
        input_limb_9_col9,
        input_limb_10_col10,
        input_limb_11_col11,
        input_limb_12_col12,
        input_limb_13_col13,
        input_limb_14_col14,
        input_limb_15_col15,
        input_limb_16_col16,
        input_limb_17_col17,
        input_limb_18_col18,
        input_limb_19_col19,
        input_limb_20_col20,
        input_limb_21_col21,
        input_limb_22_col22,
        input_limb_23_col23,
        input_limb_24_col24,
        input_limb_25_col25,
        input_limb_26_col26,
        input_limb_27_col27,
        input_limb_28_col28,
        input_limb_29_col29,
        input_limb_30_col30,
        input_limb_31_col31,
        input_limb_32_col32,
        input_limb_33_col33,
        input_limb_34_col34,
        input_limb_35_col35,
        input_limb_36_col36,
        input_limb_37_col37,
        input_limb_38_col38,
        input_limb_39_col39,
        input_limb_40_col40,
        input_limb_41_col41,
        input_limb_42_col42,
        input_limb_43_col43,
        input_limb_44_col44,
        input_limb_45_col45,
        input_limb_46_col46,
        input_limb_47_col47,
        input_limb_48_col48,
        input_limb_49_col49,
        input_limb_50_col50,
        input_limb_51_col51,
        input_limb_52_col52,
        input_limb_53_col53,
        input_limb_54_col54,
        input_limb_55_col55,
        input_limb_56_col56,
        input_limb_57_col57,
        input_limb_58_col58,
        input_limb_59_col59,
        input_limb_60_col60,
        input_limb_61_col61,
        input_limb_62_col62,
        input_limb_63_col63,
        input_limb_64_col64,
        input_limb_65_col65,
        input_limb_66_col66,
        input_limb_67_col67,
        input_limb_68_col68,
        input_limb_69_col69,
        input_limb_70_col70,
        input_limb_71_col71,
        pedersen_points_table_window_bits_18_output_limb_0_col72,
        pedersen_points_table_window_bits_18_output_limb_1_col73,
        pedersen_points_table_window_bits_18_output_limb_2_col74,
        pedersen_points_table_window_bits_18_output_limb_3_col75,
        pedersen_points_table_window_bits_18_output_limb_4_col76,
        pedersen_points_table_window_bits_18_output_limb_5_col77,
        pedersen_points_table_window_bits_18_output_limb_6_col78,
        pedersen_points_table_window_bits_18_output_limb_7_col79,
        pedersen_points_table_window_bits_18_output_limb_8_col80,
        pedersen_points_table_window_bits_18_output_limb_9_col81,
        pedersen_points_table_window_bits_18_output_limb_10_col82,
        pedersen_points_table_window_bits_18_output_limb_11_col83,
        pedersen_points_table_window_bits_18_output_limb_12_col84,
        pedersen_points_table_window_bits_18_output_limb_13_col85,
        pedersen_points_table_window_bits_18_output_limb_14_col86,
        pedersen_points_table_window_bits_18_output_limb_15_col87,
        pedersen_points_table_window_bits_18_output_limb_16_col88,
        pedersen_points_table_window_bits_18_output_limb_17_col89,
        pedersen_points_table_window_bits_18_output_limb_18_col90,
        pedersen_points_table_window_bits_18_output_limb_19_col91,
        pedersen_points_table_window_bits_18_output_limb_20_col92,
        pedersen_points_table_window_bits_18_output_limb_21_col93,
        pedersen_points_table_window_bits_18_output_limb_22_col94,
        pedersen_points_table_window_bits_18_output_limb_23_col95,
        pedersen_points_table_window_bits_18_output_limb_24_col96,
        pedersen_points_table_window_bits_18_output_limb_25_col97,
        pedersen_points_table_window_bits_18_output_limb_26_col98,
        pedersen_points_table_window_bits_18_output_limb_27_col99,
        pedersen_points_table_window_bits_18_output_limb_28_col100,
        pedersen_points_table_window_bits_18_output_limb_29_col101,
        pedersen_points_table_window_bits_18_output_limb_30_col102,
        pedersen_points_table_window_bits_18_output_limb_31_col103,
        pedersen_points_table_window_bits_18_output_limb_32_col104,
        pedersen_points_table_window_bits_18_output_limb_33_col105,
        pedersen_points_table_window_bits_18_output_limb_34_col106,
        pedersen_points_table_window_bits_18_output_limb_35_col107,
        pedersen_points_table_window_bits_18_output_limb_36_col108,
        pedersen_points_table_window_bits_18_output_limb_37_col109,
        pedersen_points_table_window_bits_18_output_limb_38_col110,
        pedersen_points_table_window_bits_18_output_limb_39_col111,
        pedersen_points_table_window_bits_18_output_limb_40_col112,
        pedersen_points_table_window_bits_18_output_limb_41_col113,
        pedersen_points_table_window_bits_18_output_limb_42_col114,
        pedersen_points_table_window_bits_18_output_limb_43_col115,
        pedersen_points_table_window_bits_18_output_limb_44_col116,
        pedersen_points_table_window_bits_18_output_limb_45_col117,
        pedersen_points_table_window_bits_18_output_limb_46_col118,
        pedersen_points_table_window_bits_18_output_limb_47_col119,
        pedersen_points_table_window_bits_18_output_limb_48_col120,
        pedersen_points_table_window_bits_18_output_limb_49_col121,
        pedersen_points_table_window_bits_18_output_limb_50_col122,
        pedersen_points_table_window_bits_18_output_limb_51_col123,
        pedersen_points_table_window_bits_18_output_limb_52_col124,
        pedersen_points_table_window_bits_18_output_limb_53_col125,
        pedersen_points_table_window_bits_18_output_limb_54_col126,
        pedersen_points_table_window_bits_18_output_limb_55_col127,
        slope_limb_0_col128,
        slope_limb_1_col129,
        slope_limb_2_col130,
        slope_limb_3_col131,
        slope_limb_4_col132,
        slope_limb_5_col133,
        slope_limb_6_col134,
        slope_limb_7_col135,
        slope_limb_8_col136,
        slope_limb_9_col137,
        slope_limb_10_col138,
        slope_limb_11_col139,
        slope_limb_12_col140,
        slope_limb_13_col141,
        slope_limb_14_col142,
        slope_limb_15_col143,
        slope_limb_16_col144,
        slope_limb_17_col145,
        slope_limb_18_col146,
        slope_limb_19_col147,
        slope_limb_20_col148,
        slope_limb_21_col149,
        slope_limb_22_col150,
        slope_limb_23_col151,
        slope_limb_24_col152,
        slope_limb_25_col153,
        slope_limb_26_col154,
        slope_limb_27_col155,
        k_col156,
        carry_0_col157,
        carry_1_col158,
        carry_2_col159,
        carry_3_col160,
        carry_4_col161,
        carry_5_col162,
        carry_6_col163,
        carry_7_col164,
        carry_8_col165,
        carry_9_col166,
        carry_10_col167,
        carry_11_col168,
        carry_12_col169,
        carry_13_col170,
        carry_14_col171,
        carry_15_col172,
        carry_16_col173,
        carry_17_col174,
        carry_18_col175,
        carry_19_col176,
        carry_20_col177,
        carry_21_col178,
        carry_22_col179,
        carry_23_col180,
        carry_24_col181,
        carry_25_col182,
        carry_26_col183,
        result_x_limb_0_col184,
        result_x_limb_1_col185,
        result_x_limb_2_col186,
        result_x_limb_3_col187,
        result_x_limb_4_col188,
        result_x_limb_5_col189,
        result_x_limb_6_col190,
        result_x_limb_7_col191,
        result_x_limb_8_col192,
        result_x_limb_9_col193,
        result_x_limb_10_col194,
        result_x_limb_11_col195,
        result_x_limb_12_col196,
        result_x_limb_13_col197,
        result_x_limb_14_col198,
        result_x_limb_15_col199,
        result_x_limb_16_col200,
        result_x_limb_17_col201,
        result_x_limb_18_col202,
        result_x_limb_19_col203,
        result_x_limb_20_col204,
        result_x_limb_21_col205,
        result_x_limb_22_col206,
        result_x_limb_23_col207,
        result_x_limb_24_col208,
        result_x_limb_25_col209,
        result_x_limb_26_col210,
        result_x_limb_27_col211,
        k_col212,
        carry_0_col213,
        carry_1_col214,
        carry_2_col215,
        carry_3_col216,
        carry_4_col217,
        carry_5_col218,
        carry_6_col219,
        carry_7_col220,
        carry_8_col221,
        carry_9_col222,
        carry_10_col223,
        carry_11_col224,
        carry_12_col225,
        carry_13_col226,
        carry_14_col227,
        carry_15_col228,
        carry_16_col229,
        carry_17_col230,
        carry_18_col231,
        carry_19_col232,
        carry_20_col233,
        carry_21_col234,
        carry_22_col235,
        carry_23_col236,
        carry_24_col237,
        carry_25_col238,
        carry_26_col239,
        result_y_limb_0_col240,
        result_y_limb_1_col241,
        result_y_limb_2_col242,
        result_y_limb_3_col243,
        result_y_limb_4_col244,
        result_y_limb_5_col245,
        result_y_limb_6_col246,
        result_y_limb_7_col247,
        result_y_limb_8_col248,
        result_y_limb_9_col249,
        result_y_limb_10_col250,
        result_y_limb_11_col251,
        result_y_limb_12_col252,
        result_y_limb_13_col253,
        result_y_limb_14_col254,
        result_y_limb_15_col255,
        result_y_limb_16_col256,
        result_y_limb_17_col257,
        result_y_limb_18_col258,
        result_y_limb_19_col259,
        result_y_limb_20_col260,
        result_y_limb_21_col261,
        result_y_limb_22_col262,
        result_y_limb_23_col263,
        result_y_limb_24_col264,
        result_y_limb_25_col265,
        result_y_limb_26_col266,
        result_y_limb_27_col267,
        k_col268,
        carry_0_col269,
        carry_1_col270,
        carry_2_col271,
        carry_3_col272,
        carry_4_col273,
        carry_5_col274,
        carry_6_col275,
        carry_7_col276,
        carry_8_col277,
        carry_9_col278,
        carry_10_col279,
        carry_11_col280,
        carry_12_col281,
        carry_13_col282,
        carry_14_col283,
        carry_15_col284,
        carry_16_col285,
        carry_17_col286,
        carry_18_col287,
        carry_19_col288,
        carry_20_col289,
        carry_21_col290,
        carry_22_col291,
        carry_23_col292,
        carry_24_col293,
        carry_25_col294,
        carry_26_col295,
        enabler,
    ] = input.try_into().unwrap();
    let enabler_constraint_value = eval!(context, ((enabler) * (enabler)) - (enabler));
    acc.add_constraint(context, enabler_constraint_value);

    // Use PedersenPointsTableWindowBits18.
    let tuple_0 = &[
        eval!(context, 1444721856),
        eval!(context, ((262144) * (input_limb_1_col1)) + (input_limb_2_col2)),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_0_col72),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_1_col73),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_2_col74),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_3_col75),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_4_col76),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_5_col77),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_6_col78),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_7_col79),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_8_col80),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_9_col81),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_10_col82),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_11_col83),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_12_col84),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_13_col85),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_14_col86),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_15_col87),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_16_col88),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_17_col89),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_18_col90),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_19_col91),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_20_col92),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_21_col93),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_22_col94),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_23_col95),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_24_col96),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_25_col97),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_26_col98),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_27_col99),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_28_col100),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_29_col101),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_30_col102),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_31_col103),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_32_col104),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_33_col105),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_34_col106),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_35_col107),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_36_col108),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_37_col109),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_38_col110),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_39_col111),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_40_col112),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_41_col113),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_42_col114),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_43_col115),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_44_col116),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_45_col117),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_46_col118),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_47_col119),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_48_col120),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_49_col121),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_50_col122),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_51_col123),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_52_col124),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_53_col125),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_54_col126),
        eval!(context, pedersen_points_table_window_bits_18_output_limb_55_col127),
    ];
    let numerator_0 = eval!(context, 1);
    acc.add_to_relation(context, numerator_0, tuple_0);

    ec_add::accumulate_constraints(
        &[
            eval!(context, input_limb_16_col16),
            eval!(context, input_limb_17_col17),
            eval!(context, input_limb_18_col18),
            eval!(context, input_limb_19_col19),
            eval!(context, input_limb_20_col20),
            eval!(context, input_limb_21_col21),
            eval!(context, input_limb_22_col22),
            eval!(context, input_limb_23_col23),
            eval!(context, input_limb_24_col24),
            eval!(context, input_limb_25_col25),
            eval!(context, input_limb_26_col26),
            eval!(context, input_limb_27_col27),
            eval!(context, input_limb_28_col28),
            eval!(context, input_limb_29_col29),
            eval!(context, input_limb_30_col30),
            eval!(context, input_limb_31_col31),
            eval!(context, input_limb_32_col32),
            eval!(context, input_limb_33_col33),
            eval!(context, input_limb_34_col34),
            eval!(context, input_limb_35_col35),
            eval!(context, input_limb_36_col36),
            eval!(context, input_limb_37_col37),
            eval!(context, input_limb_38_col38),
            eval!(context, input_limb_39_col39),
            eval!(context, input_limb_40_col40),
            eval!(context, input_limb_41_col41),
            eval!(context, input_limb_42_col42),
            eval!(context, input_limb_43_col43),
            eval!(context, input_limb_44_col44),
            eval!(context, input_limb_45_col45),
            eval!(context, input_limb_46_col46),
            eval!(context, input_limb_47_col47),
            eval!(context, input_limb_48_col48),
            eval!(context, input_limb_49_col49),
            eval!(context, input_limb_50_col50),
            eval!(context, input_limb_51_col51),
            eval!(context, input_limb_52_col52),
            eval!(context, input_limb_53_col53),
            eval!(context, input_limb_54_col54),
            eval!(context, input_limb_55_col55),
            eval!(context, input_limb_56_col56),
            eval!(context, input_limb_57_col57),
            eval!(context, input_limb_58_col58),
            eval!(context, input_limb_59_col59),
            eval!(context, input_limb_60_col60),
            eval!(context, input_limb_61_col61),
            eval!(context, input_limb_62_col62),
            eval!(context, input_limb_63_col63),
            eval!(context, input_limb_64_col64),
            eval!(context, input_limb_65_col65),
            eval!(context, input_limb_66_col66),
            eval!(context, input_limb_67_col67),
            eval!(context, input_limb_68_col68),
            eval!(context, input_limb_69_col69),
            eval!(context, input_limb_70_col70),
            eval!(context, input_limb_71_col71),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_0_col72),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_1_col73),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_2_col74),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_3_col75),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_4_col76),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_5_col77),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_6_col78),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_7_col79),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_8_col80),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_9_col81),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_10_col82),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_11_col83),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_12_col84),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_13_col85),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_14_col86),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_15_col87),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_16_col88),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_17_col89),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_18_col90),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_19_col91),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_20_col92),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_21_col93),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_22_col94),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_23_col95),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_24_col96),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_25_col97),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_26_col98),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_27_col99),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_28_col100),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_29_col101),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_30_col102),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_31_col103),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_32_col104),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_33_col105),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_34_col106),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_35_col107),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_36_col108),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_37_col109),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_38_col110),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_39_col111),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_40_col112),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_41_col113),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_42_col114),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_43_col115),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_44_col116),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_45_col117),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_46_col118),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_47_col119),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_48_col120),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_49_col121),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_50_col122),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_51_col123),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_52_col124),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_53_col125),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_54_col126),
            eval!(context, pedersen_points_table_window_bits_18_output_limb_55_col127),
            eval!(context, slope_limb_0_col128),
            eval!(context, slope_limb_1_col129),
            eval!(context, slope_limb_2_col130),
            eval!(context, slope_limb_3_col131),
            eval!(context, slope_limb_4_col132),
            eval!(context, slope_limb_5_col133),
            eval!(context, slope_limb_6_col134),
            eval!(context, slope_limb_7_col135),
            eval!(context, slope_limb_8_col136),
            eval!(context, slope_limb_9_col137),
            eval!(context, slope_limb_10_col138),
            eval!(context, slope_limb_11_col139),
            eval!(context, slope_limb_12_col140),
            eval!(context, slope_limb_13_col141),
            eval!(context, slope_limb_14_col142),
            eval!(context, slope_limb_15_col143),
            eval!(context, slope_limb_16_col144),
            eval!(context, slope_limb_17_col145),
            eval!(context, slope_limb_18_col146),
            eval!(context, slope_limb_19_col147),
            eval!(context, slope_limb_20_col148),
            eval!(context, slope_limb_21_col149),
            eval!(context, slope_limb_22_col150),
            eval!(context, slope_limb_23_col151),
            eval!(context, slope_limb_24_col152),
            eval!(context, slope_limb_25_col153),
            eval!(context, slope_limb_26_col154),
            eval!(context, slope_limb_27_col155),
            eval!(context, k_col156),
            eval!(context, carry_0_col157),
            eval!(context, carry_1_col158),
            eval!(context, carry_2_col159),
            eval!(context, carry_3_col160),
            eval!(context, carry_4_col161),
            eval!(context, carry_5_col162),
            eval!(context, carry_6_col163),
            eval!(context, carry_7_col164),
            eval!(context, carry_8_col165),
            eval!(context, carry_9_col166),
            eval!(context, carry_10_col167),
            eval!(context, carry_11_col168),
            eval!(context, carry_12_col169),
            eval!(context, carry_13_col170),
            eval!(context, carry_14_col171),
            eval!(context, carry_15_col172),
            eval!(context, carry_16_col173),
            eval!(context, carry_17_col174),
            eval!(context, carry_18_col175),
            eval!(context, carry_19_col176),
            eval!(context, carry_20_col177),
            eval!(context, carry_21_col178),
            eval!(context, carry_22_col179),
            eval!(context, carry_23_col180),
            eval!(context, carry_24_col181),
            eval!(context, carry_25_col182),
            eval!(context, carry_26_col183),
            eval!(context, result_x_limb_0_col184),
            eval!(context, result_x_limb_1_col185),
            eval!(context, result_x_limb_2_col186),
            eval!(context, result_x_limb_3_col187),
            eval!(context, result_x_limb_4_col188),
            eval!(context, result_x_limb_5_col189),
            eval!(context, result_x_limb_6_col190),
            eval!(context, result_x_limb_7_col191),
            eval!(context, result_x_limb_8_col192),
            eval!(context, result_x_limb_9_col193),
            eval!(context, result_x_limb_10_col194),
            eval!(context, result_x_limb_11_col195),
            eval!(context, result_x_limb_12_col196),
            eval!(context, result_x_limb_13_col197),
            eval!(context, result_x_limb_14_col198),
            eval!(context, result_x_limb_15_col199),
            eval!(context, result_x_limb_16_col200),
            eval!(context, result_x_limb_17_col201),
            eval!(context, result_x_limb_18_col202),
            eval!(context, result_x_limb_19_col203),
            eval!(context, result_x_limb_20_col204),
            eval!(context, result_x_limb_21_col205),
            eval!(context, result_x_limb_22_col206),
            eval!(context, result_x_limb_23_col207),
            eval!(context, result_x_limb_24_col208),
            eval!(context, result_x_limb_25_col209),
            eval!(context, result_x_limb_26_col210),
            eval!(context, result_x_limb_27_col211),
            eval!(context, k_col212),
            eval!(context, carry_0_col213),
            eval!(context, carry_1_col214),
            eval!(context, carry_2_col215),
            eval!(context, carry_3_col216),
            eval!(context, carry_4_col217),
            eval!(context, carry_5_col218),
            eval!(context, carry_6_col219),
            eval!(context, carry_7_col220),
            eval!(context, carry_8_col221),
            eval!(context, carry_9_col222),
            eval!(context, carry_10_col223),
            eval!(context, carry_11_col224),
            eval!(context, carry_12_col225),
            eval!(context, carry_13_col226),
            eval!(context, carry_14_col227),
            eval!(context, carry_15_col228),
            eval!(context, carry_16_col229),
            eval!(context, carry_17_col230),
            eval!(context, carry_18_col231),
            eval!(context, carry_19_col232),
            eval!(context, carry_20_col233),
            eval!(context, carry_21_col234),
            eval!(context, carry_22_col235),
            eval!(context, carry_23_col236),
            eval!(context, carry_24_col237),
            eval!(context, carry_25_col238),
            eval!(context, carry_26_col239),
            eval!(context, result_y_limb_0_col240),
            eval!(context, result_y_limb_1_col241),
            eval!(context, result_y_limb_2_col242),
            eval!(context, result_y_limb_3_col243),
            eval!(context, result_y_limb_4_col244),
            eval!(context, result_y_limb_5_col245),
            eval!(context, result_y_limb_6_col246),
            eval!(context, result_y_limb_7_col247),
            eval!(context, result_y_limb_8_col248),
            eval!(context, result_y_limb_9_col249),
            eval!(context, result_y_limb_10_col250),
            eval!(context, result_y_limb_11_col251),
            eval!(context, result_y_limb_12_col252),
            eval!(context, result_y_limb_13_col253),
            eval!(context, result_y_limb_14_col254),
            eval!(context, result_y_limb_15_col255),
            eval!(context, result_y_limb_16_col256),
            eval!(context, result_y_limb_17_col257),
            eval!(context, result_y_limb_18_col258),
            eval!(context, result_y_limb_19_col259),
            eval!(context, result_y_limb_20_col260),
            eval!(context, result_y_limb_21_col261),
            eval!(context, result_y_limb_22_col262),
            eval!(context, result_y_limb_23_col263),
            eval!(context, result_y_limb_24_col264),
            eval!(context, result_y_limb_25_col265),
            eval!(context, result_y_limb_26_col266),
            eval!(context, result_y_limb_27_col267),
            eval!(context, k_col268),
            eval!(context, carry_0_col269),
            eval!(context, carry_1_col270),
            eval!(context, carry_2_col271),
            eval!(context, carry_3_col272),
            eval!(context, carry_4_col273),
            eval!(context, carry_5_col274),
            eval!(context, carry_6_col275),
            eval!(context, carry_7_col276),
            eval!(context, carry_8_col277),
            eval!(context, carry_9_col278),
            eval!(context, carry_10_col279),
            eval!(context, carry_11_col280),
            eval!(context, carry_12_col281),
            eval!(context, carry_13_col282),
            eval!(context, carry_14_col283),
            eval!(context, carry_15_col284),
            eval!(context, carry_16_col285),
            eval!(context, carry_17_col286),
            eval!(context, carry_18_col287),
            eval!(context, carry_19_col288),
            eval!(context, carry_20_col289),
            eval!(context, carry_21_col290),
            eval!(context, carry_22_col291),
            eval!(context, carry_23_col292),
            eval!(context, carry_24_col293),
            eval!(context, carry_25_col294),
            eval!(context, carry_26_col295),
        ],
        context,
        component_data,
        acc,
    );

    // Use PartialEcMulWindowBits18.
    let tuple_2 = &[
        eval!(context, 1621226978),
        eval!(context, input_limb_0_col0),
        eval!(context, input_limb_1_col1),
        eval!(context, input_limb_2_col2),
        eval!(context, input_limb_3_col3),
        eval!(context, input_limb_4_col4),
        eval!(context, input_limb_5_col5),
        eval!(context, input_limb_6_col6),
        eval!(context, input_limb_7_col7),
        eval!(context, input_limb_8_col8),
        eval!(context, input_limb_9_col9),
        eval!(context, input_limb_10_col10),
        eval!(context, input_limb_11_col11),
        eval!(context, input_limb_12_col12),
        eval!(context, input_limb_13_col13),
        eval!(context, input_limb_14_col14),
        eval!(context, input_limb_15_col15),
        eval!(context, input_limb_16_col16),
        eval!(context, input_limb_17_col17),
        eval!(context, input_limb_18_col18),
        eval!(context, input_limb_19_col19),
        eval!(context, input_limb_20_col20),
        eval!(context, input_limb_21_col21),
        eval!(context, input_limb_22_col22),
        eval!(context, input_limb_23_col23),
        eval!(context, input_limb_24_col24),
        eval!(context, input_limb_25_col25),
        eval!(context, input_limb_26_col26),
        eval!(context, input_limb_27_col27),
        eval!(context, input_limb_28_col28),
        eval!(context, input_limb_29_col29),
        eval!(context, input_limb_30_col30),
        eval!(context, input_limb_31_col31),
        eval!(context, input_limb_32_col32),
        eval!(context, input_limb_33_col33),
        eval!(context, input_limb_34_col34),
        eval!(context, input_limb_35_col35),
        eval!(context, input_limb_36_col36),
        eval!(context, input_limb_37_col37),
        eval!(context, input_limb_38_col38),
        eval!(context, input_limb_39_col39),
        eval!(context, input_limb_40_col40),
        eval!(context, input_limb_41_col41),
        eval!(context, input_limb_42_col42),
        eval!(context, input_limb_43_col43),
        eval!(context, input_limb_44_col44),
        eval!(context, input_limb_45_col45),
        eval!(context, input_limb_46_col46),
        eval!(context, input_limb_47_col47),
        eval!(context, input_limb_48_col48),
        eval!(context, input_limb_49_col49),
        eval!(context, input_limb_50_col50),
        eval!(context, input_limb_51_col51),
        eval!(context, input_limb_52_col52),
        eval!(context, input_limb_53_col53),
        eval!(context, input_limb_54_col54),
        eval!(context, input_limb_55_col55),
        eval!(context, input_limb_56_col56),
        eval!(context, input_limb_57_col57),
        eval!(context, input_limb_58_col58),
        eval!(context, input_limb_59_col59),
        eval!(context, input_limb_60_col60),
        eval!(context, input_limb_61_col61),
        eval!(context, input_limb_62_col62),
        eval!(context, input_limb_63_col63),
        eval!(context, input_limb_64_col64),
        eval!(context, input_limb_65_col65),
        eval!(context, input_limb_66_col66),
        eval!(context, input_limb_67_col67),
        eval!(context, input_limb_68_col68),
        eval!(context, input_limb_69_col69),
        eval!(context, input_limb_70_col70),
        eval!(context, input_limb_71_col71),
    ];
    let numerator_2 = eval!(context, enabler);
    acc.add_to_relation(context, numerator_2, tuple_2);

    // Yield PartialEcMulWindowBits18.
    let tuple_3 = &[
        eval!(context, 1621226978),
        eval!(context, input_limb_0_col0),
        eval!(context, (input_limb_1_col1) + (1)),
        eval!(context, input_limb_3_col3),
        eval!(context, input_limb_4_col4),
        eval!(context, input_limb_5_col5),
        eval!(context, input_limb_6_col6),
        eval!(context, input_limb_7_col7),
        eval!(context, input_limb_8_col8),
        eval!(context, input_limb_9_col9),
        eval!(context, input_limb_10_col10),
        eval!(context, input_limb_11_col11),
        eval!(context, input_limb_12_col12),
        eval!(context, input_limb_13_col13),
        eval!(context, input_limb_14_col14),
        eval!(context, input_limb_15_col15),
        eval!(context, 0),
        eval!(context, result_x_limb_0_col184),
        eval!(context, result_x_limb_1_col185),
        eval!(context, result_x_limb_2_col186),
        eval!(context, result_x_limb_3_col187),
        eval!(context, result_x_limb_4_col188),
        eval!(context, result_x_limb_5_col189),
        eval!(context, result_x_limb_6_col190),
        eval!(context, result_x_limb_7_col191),
        eval!(context, result_x_limb_8_col192),
        eval!(context, result_x_limb_9_col193),
        eval!(context, result_x_limb_10_col194),
        eval!(context, result_x_limb_11_col195),
        eval!(context, result_x_limb_12_col196),
        eval!(context, result_x_limb_13_col197),
        eval!(context, result_x_limb_14_col198),
        eval!(context, result_x_limb_15_col199),
        eval!(context, result_x_limb_16_col200),
        eval!(context, result_x_limb_17_col201),
        eval!(context, result_x_limb_18_col202),
        eval!(context, result_x_limb_19_col203),
        eval!(context, result_x_limb_20_col204),
        eval!(context, result_x_limb_21_col205),
        eval!(context, result_x_limb_22_col206),
        eval!(context, result_x_limb_23_col207),
        eval!(context, result_x_limb_24_col208),
        eval!(context, result_x_limb_25_col209),
        eval!(context, result_x_limb_26_col210),
        eval!(context, result_x_limb_27_col211),
        eval!(context, result_y_limb_0_col240),
        eval!(context, result_y_limb_1_col241),
        eval!(context, result_y_limb_2_col242),
        eval!(context, result_y_limb_3_col243),
        eval!(context, result_y_limb_4_col244),
        eval!(context, result_y_limb_5_col245),
        eval!(context, result_y_limb_6_col246),
        eval!(context, result_y_limb_7_col247),
        eval!(context, result_y_limb_8_col248),
        eval!(context, result_y_limb_9_col249),
        eval!(context, result_y_limb_10_col250),
        eval!(context, result_y_limb_11_col251),
        eval!(context, result_y_limb_12_col252),
        eval!(context, result_y_limb_13_col253),
        eval!(context, result_y_limb_14_col254),
        eval!(context, result_y_limb_15_col255),
        eval!(context, result_y_limb_16_col256),
        eval!(context, result_y_limb_17_col257),
        eval!(context, result_y_limb_18_col258),
        eval!(context, result_y_limb_19_col259),
        eval!(context, result_y_limb_20_col260),
        eval!(context, result_y_limb_21_col261),
        eval!(context, result_y_limb_22_col262),
        eval!(context, result_y_limb_23_col263),
        eval!(context, result_y_limb_24_col264),
        eval!(context, result_y_limb_25_col265),
        eval!(context, result_y_limb_26_col266),
        eval!(context, result_y_limb_27_col267),
    ];
    let numerator_3 = eval!(context, -(enabler));
    acc.add_to_relation(context, numerator_3, tuple_3);
}

pub struct Component {}
impl<Value: IValue> CircuitEval<Value> for Component {
    fn evaluate(
        &self,
        context: &mut Context<Value>,
        component_data: &ComponentData<'_>,
        acc: &mut CompositionConstraintAccumulator,
    ) {
        accumulate_constraints(component_data.trace_columns, context, component_data, acc);
    }

    fn trace_columns(&self) -> usize {
        N_TRACE_COLUMNS
    }

    fn interaction_columns(&self) -> usize {
        N_INTERACTION_COLUMNS
    }

    fn relation_uses_per_row(&self) -> &[RelationUse] {
        &RELATION_USES_PER_ROW
    }
}
