// This file was created by the AIR team.

use crate::cairo_air::components::prelude::*;

pub const N_TRACE_COLUMNS: usize = 311;
pub const N_INTERACTION_COLUMNS: usize = 260;

pub const RELATION_USES_PER_ROW: [RelationUse; 18] = [
    RelationUse { relation_id: "PartialEcMulWindowBits9", uses: 1 },
    RelationUse { relation_id: "PedersenPointsTableWindowBits9", uses: 1 },
    RelationUse { relation_id: "RangeCheck_20", uses: 12 },
    RelationUse { relation_id: "RangeCheck_20_B", uses: 12 },
    RelationUse { relation_id: "RangeCheck_20_C", uses: 12 },
    RelationUse { relation_id: "RangeCheck_20_D", uses: 12 },
    RelationUse { relation_id: "RangeCheck_20_E", uses: 9 },
    RelationUse { relation_id: "RangeCheck_20_F", uses: 9 },
    RelationUse { relation_id: "RangeCheck_20_G", uses: 9 },
    RelationUse { relation_id: "RangeCheck_20_H", uses: 9 },
    RelationUse { relation_id: "RangeCheck_9_9", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_B", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_C", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_D", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_E", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_F", uses: 6 },
    RelationUse { relation_id: "RangeCheck_9_9_G", uses: 3 },
    RelationUse { relation_id: "RangeCheck_9_9_H", uses: 3 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints(
    input: &[Var],
    context: &mut Context<impl IValue>,
    component_data: &ComponentData<'_>,
    acc: &mut CompositionConstraintAccumulator,
) {
    let [
        input_limb_0_col0,
        input_limb_1_col1,
        input_limb_2_col2,
        input_limb_3_col3,
        input_limb_4_col4,
        input_limb_5_col5,
        input_limb_6_col6,
        input_limb_7_col7,
        input_limb_8_col8,
        input_limb_9_col9,
        input_limb_10_col10,
        input_limb_11_col11,
        input_limb_12_col12,
        input_limb_13_col13,
        input_limb_14_col14,
        input_limb_15_col15,
        input_limb_16_col16,
        input_limb_17_col17,
        input_limb_18_col18,
        input_limb_19_col19,
        input_limb_20_col20,
        input_limb_21_col21,
        input_limb_22_col22,
        input_limb_23_col23,
        input_limb_24_col24,
        input_limb_25_col25,
        input_limb_26_col26,
        input_limb_27_col27,
        input_limb_28_col28,
        input_limb_29_col29,
        input_limb_30_col30,
        input_limb_31_col31,
        input_limb_32_col32,
        input_limb_33_col33,
        input_limb_34_col34,
        input_limb_35_col35,
        input_limb_36_col36,
        input_limb_37_col37,
        input_limb_38_col38,
        input_limb_39_col39,
        input_limb_40_col40,
        input_limb_41_col41,
        input_limb_42_col42,
        input_limb_43_col43,
        input_limb_44_col44,
        input_limb_45_col45,
        input_limb_46_col46,
        input_limb_47_col47,
        input_limb_48_col48,
        input_limb_49_col49,
        input_limb_50_col50,
        input_limb_51_col51,
        input_limb_52_col52,
        input_limb_53_col53,
        input_limb_54_col54,
        input_limb_55_col55,
        input_limb_56_col56,
        input_limb_57_col57,
        input_limb_58_col58,
        input_limb_59_col59,
        input_limb_60_col60,
        input_limb_61_col61,
        input_limb_62_col62,
        input_limb_63_col63,
        input_limb_64_col64,
        input_limb_65_col65,
        input_limb_66_col66,
        input_limb_67_col67,
        input_limb_68_col68,
        input_limb_69_col69,
        input_limb_70_col70,
        input_limb_71_col71,
        input_limb_72_col72,
        input_limb_73_col73,
        input_limb_74_col74,
        input_limb_75_col75,
        input_limb_76_col76,
        input_limb_77_col77,
        input_limb_78_col78,
        input_limb_79_col79,
        input_limb_80_col80,
        input_limb_81_col81,
        input_limb_82_col82,
        input_limb_83_col83,
        input_limb_84_col84,
        input_limb_85_col85,
        pedersen_points_table_window_bits_9_output_limb_0_col86,
        pedersen_points_table_window_bits_9_output_limb_1_col87,
        pedersen_points_table_window_bits_9_output_limb_2_col88,
        pedersen_points_table_window_bits_9_output_limb_3_col89,
        pedersen_points_table_window_bits_9_output_limb_4_col90,
        pedersen_points_table_window_bits_9_output_limb_5_col91,
        pedersen_points_table_window_bits_9_output_limb_6_col92,
        pedersen_points_table_window_bits_9_output_limb_7_col93,
        pedersen_points_table_window_bits_9_output_limb_8_col94,
        pedersen_points_table_window_bits_9_output_limb_9_col95,
        pedersen_points_table_window_bits_9_output_limb_10_col96,
        pedersen_points_table_window_bits_9_output_limb_11_col97,
        pedersen_points_table_window_bits_9_output_limb_12_col98,
        pedersen_points_table_window_bits_9_output_limb_13_col99,
        pedersen_points_table_window_bits_9_output_limb_14_col100,
        pedersen_points_table_window_bits_9_output_limb_15_col101,
        pedersen_points_table_window_bits_9_output_limb_16_col102,
        pedersen_points_table_window_bits_9_output_limb_17_col103,
        pedersen_points_table_window_bits_9_output_limb_18_col104,
        pedersen_points_table_window_bits_9_output_limb_19_col105,
        pedersen_points_table_window_bits_9_output_limb_20_col106,
        pedersen_points_table_window_bits_9_output_limb_21_col107,
        pedersen_points_table_window_bits_9_output_limb_22_col108,
        pedersen_points_table_window_bits_9_output_limb_23_col109,
        pedersen_points_table_window_bits_9_output_limb_24_col110,
        pedersen_points_table_window_bits_9_output_limb_25_col111,
        pedersen_points_table_window_bits_9_output_limb_26_col112,
        pedersen_points_table_window_bits_9_output_limb_27_col113,
        pedersen_points_table_window_bits_9_output_limb_28_col114,
        pedersen_points_table_window_bits_9_output_limb_29_col115,
        pedersen_points_table_window_bits_9_output_limb_30_col116,
        pedersen_points_table_window_bits_9_output_limb_31_col117,
        pedersen_points_table_window_bits_9_output_limb_32_col118,
        pedersen_points_table_window_bits_9_output_limb_33_col119,
        pedersen_points_table_window_bits_9_output_limb_34_col120,
        pedersen_points_table_window_bits_9_output_limb_35_col121,
        pedersen_points_table_window_bits_9_output_limb_36_col122,
        pedersen_points_table_window_bits_9_output_limb_37_col123,
        pedersen_points_table_window_bits_9_output_limb_38_col124,
        pedersen_points_table_window_bits_9_output_limb_39_col125,
        pedersen_points_table_window_bits_9_output_limb_40_col126,
        pedersen_points_table_window_bits_9_output_limb_41_col127,
        pedersen_points_table_window_bits_9_output_limb_42_col128,
        pedersen_points_table_window_bits_9_output_limb_43_col129,
        pedersen_points_table_window_bits_9_output_limb_44_col130,
        pedersen_points_table_window_bits_9_output_limb_45_col131,
        pedersen_points_table_window_bits_9_output_limb_46_col132,
        pedersen_points_table_window_bits_9_output_limb_47_col133,
        pedersen_points_table_window_bits_9_output_limb_48_col134,
        pedersen_points_table_window_bits_9_output_limb_49_col135,
        pedersen_points_table_window_bits_9_output_limb_50_col136,
        pedersen_points_table_window_bits_9_output_limb_51_col137,
        pedersen_points_table_window_bits_9_output_limb_52_col138,
        pedersen_points_table_window_bits_9_output_limb_53_col139,
        pedersen_points_table_window_bits_9_output_limb_54_col140,
        pedersen_points_table_window_bits_9_output_limb_55_col141,
        slope_limb_0_col142,
        slope_limb_1_col143,
        slope_limb_2_col144,
        slope_limb_3_col145,
        slope_limb_4_col146,
        slope_limb_5_col147,
        slope_limb_6_col148,
        slope_limb_7_col149,
        slope_limb_8_col150,
        slope_limb_9_col151,
        slope_limb_10_col152,
        slope_limb_11_col153,
        slope_limb_12_col154,
        slope_limb_13_col155,
        slope_limb_14_col156,
        slope_limb_15_col157,
        slope_limb_16_col158,
        slope_limb_17_col159,
        slope_limb_18_col160,
        slope_limb_19_col161,
        slope_limb_20_col162,
        slope_limb_21_col163,
        slope_limb_22_col164,
        slope_limb_23_col165,
        slope_limb_24_col166,
        slope_limb_25_col167,
        slope_limb_26_col168,
        slope_limb_27_col169,
        k_col170,
        carry_0_col171,
        carry_1_col172,
        carry_2_col173,
        carry_3_col174,
        carry_4_col175,
        carry_5_col176,
        carry_6_col177,
        carry_7_col178,
        carry_8_col179,
        carry_9_col180,
        carry_10_col181,
        carry_11_col182,
        carry_12_col183,
        carry_13_col184,
        carry_14_col185,
        carry_15_col186,
        carry_16_col187,
        carry_17_col188,
        carry_18_col189,
        carry_19_col190,
        carry_20_col191,
        carry_21_col192,
        carry_22_col193,
        carry_23_col194,
        carry_24_col195,
        carry_25_col196,
        carry_26_col197,
        result_x_limb_0_col198,
        result_x_limb_1_col199,
        result_x_limb_2_col200,
        result_x_limb_3_col201,
        result_x_limb_4_col202,
        result_x_limb_5_col203,
        result_x_limb_6_col204,
        result_x_limb_7_col205,
        result_x_limb_8_col206,
        result_x_limb_9_col207,
        result_x_limb_10_col208,
        result_x_limb_11_col209,
        result_x_limb_12_col210,
        result_x_limb_13_col211,
        result_x_limb_14_col212,
        result_x_limb_15_col213,
        result_x_limb_16_col214,
        result_x_limb_17_col215,
        result_x_limb_18_col216,
        result_x_limb_19_col217,
        result_x_limb_20_col218,
        result_x_limb_21_col219,
        result_x_limb_22_col220,
        result_x_limb_23_col221,
        result_x_limb_24_col222,
        result_x_limb_25_col223,
        result_x_limb_26_col224,
        result_x_limb_27_col225,
        k_col226,
        carry_0_col227,
        carry_1_col228,
        carry_2_col229,
        carry_3_col230,
        carry_4_col231,
        carry_5_col232,
        carry_6_col233,
        carry_7_col234,
        carry_8_col235,
        carry_9_col236,
        carry_10_col237,
        carry_11_col238,
        carry_12_col239,
        carry_13_col240,
        carry_14_col241,
        carry_15_col242,
        carry_16_col243,
        carry_17_col244,
        carry_18_col245,
        carry_19_col246,
        carry_20_col247,
        carry_21_col248,
        carry_22_col249,
        carry_23_col250,
        carry_24_col251,
        carry_25_col252,
        carry_26_col253,
        result_y_limb_0_col254,
        result_y_limb_1_col255,
        result_y_limb_2_col256,
        result_y_limb_3_col257,
        result_y_limb_4_col258,
        result_y_limb_5_col259,
        result_y_limb_6_col260,
        result_y_limb_7_col261,
        result_y_limb_8_col262,
        result_y_limb_9_col263,
        result_y_limb_10_col264,
        result_y_limb_11_col265,
        result_y_limb_12_col266,
        result_y_limb_13_col267,
        result_y_limb_14_col268,
        result_y_limb_15_col269,
        result_y_limb_16_col270,
        result_y_limb_17_col271,
        result_y_limb_18_col272,
        result_y_limb_19_col273,
        result_y_limb_20_col274,
        result_y_limb_21_col275,
        result_y_limb_22_col276,
        result_y_limb_23_col277,
        result_y_limb_24_col278,
        result_y_limb_25_col279,
        result_y_limb_26_col280,
        result_y_limb_27_col281,
        k_col282,
        carry_0_col283,
        carry_1_col284,
        carry_2_col285,
        carry_3_col286,
        carry_4_col287,
        carry_5_col288,
        carry_6_col289,
        carry_7_col290,
        carry_8_col291,
        carry_9_col292,
        carry_10_col293,
        carry_11_col294,
        carry_12_col295,
        carry_13_col296,
        carry_14_col297,
        carry_15_col298,
        carry_16_col299,
        carry_17_col300,
        carry_18_col301,
        carry_19_col302,
        carry_20_col303,
        carry_21_col304,
        carry_22_col305,
        carry_23_col306,
        carry_24_col307,
        carry_25_col308,
        carry_26_col309,
        enabler,
    ] = input.try_into().unwrap();
    let enabler_constraint_value = eval!(context, ((enabler) * (enabler)) - (enabler));
    acc.add_constraint(context, enabler_constraint_value);

    // Use PedersenPointsTableWindowBits9.
    let tuple_0 = &[
        eval!(context, 1791500038),
        eval!(context, ((512) * (input_limb_1_col1)) + (input_limb_2_col2)),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_0_col86),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_1_col87),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_2_col88),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_3_col89),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_4_col90),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_5_col91),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_6_col92),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_7_col93),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_8_col94),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_9_col95),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_10_col96),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_11_col97),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_12_col98),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_13_col99),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_14_col100),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_15_col101),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_16_col102),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_17_col103),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_18_col104),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_19_col105),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_20_col106),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_21_col107),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_22_col108),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_23_col109),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_24_col110),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_25_col111),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_26_col112),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_27_col113),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_28_col114),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_29_col115),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_30_col116),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_31_col117),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_32_col118),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_33_col119),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_34_col120),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_35_col121),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_36_col122),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_37_col123),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_38_col124),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_39_col125),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_40_col126),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_41_col127),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_42_col128),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_43_col129),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_44_col130),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_45_col131),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_46_col132),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_47_col133),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_48_col134),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_49_col135),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_50_col136),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_51_col137),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_52_col138),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_53_col139),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_54_col140),
        eval!(context, pedersen_points_table_window_bits_9_output_limb_55_col141),
    ];
    let numerator_0 = eval!(context, 1);
    acc.add_to_relation(context, numerator_0, tuple_0);

    ec_add::accumulate_constraints(
        &[
            eval!(context, input_limb_30_col30),
            eval!(context, input_limb_31_col31),
            eval!(context, input_limb_32_col32),
            eval!(context, input_limb_33_col33),
            eval!(context, input_limb_34_col34),
            eval!(context, input_limb_35_col35),
            eval!(context, input_limb_36_col36),
            eval!(context, input_limb_37_col37),
            eval!(context, input_limb_38_col38),
            eval!(context, input_limb_39_col39),
            eval!(context, input_limb_40_col40),
            eval!(context, input_limb_41_col41),
            eval!(context, input_limb_42_col42),
            eval!(context, input_limb_43_col43),
            eval!(context, input_limb_44_col44),
            eval!(context, input_limb_45_col45),
            eval!(context, input_limb_46_col46),
            eval!(context, input_limb_47_col47),
            eval!(context, input_limb_48_col48),
            eval!(context, input_limb_49_col49),
            eval!(context, input_limb_50_col50),
            eval!(context, input_limb_51_col51),
            eval!(context, input_limb_52_col52),
            eval!(context, input_limb_53_col53),
            eval!(context, input_limb_54_col54),
            eval!(context, input_limb_55_col55),
            eval!(context, input_limb_56_col56),
            eval!(context, input_limb_57_col57),
            eval!(context, input_limb_58_col58),
            eval!(context, input_limb_59_col59),
            eval!(context, input_limb_60_col60),
            eval!(context, input_limb_61_col61),
            eval!(context, input_limb_62_col62),
            eval!(context, input_limb_63_col63),
            eval!(context, input_limb_64_col64),
            eval!(context, input_limb_65_col65),
            eval!(context, input_limb_66_col66),
            eval!(context, input_limb_67_col67),
            eval!(context, input_limb_68_col68),
            eval!(context, input_limb_69_col69),
            eval!(context, input_limb_70_col70),
            eval!(context, input_limb_71_col71),
            eval!(context, input_limb_72_col72),
            eval!(context, input_limb_73_col73),
            eval!(context, input_limb_74_col74),
            eval!(context, input_limb_75_col75),
            eval!(context, input_limb_76_col76),
            eval!(context, input_limb_77_col77),
            eval!(context, input_limb_78_col78),
            eval!(context, input_limb_79_col79),
            eval!(context, input_limb_80_col80),
            eval!(context, input_limb_81_col81),
            eval!(context, input_limb_82_col82),
            eval!(context, input_limb_83_col83),
            eval!(context, input_limb_84_col84),
            eval!(context, input_limb_85_col85),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_0_col86),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_1_col87),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_2_col88),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_3_col89),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_4_col90),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_5_col91),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_6_col92),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_7_col93),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_8_col94),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_9_col95),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_10_col96),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_11_col97),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_12_col98),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_13_col99),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_14_col100),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_15_col101),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_16_col102),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_17_col103),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_18_col104),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_19_col105),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_20_col106),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_21_col107),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_22_col108),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_23_col109),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_24_col110),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_25_col111),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_26_col112),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_27_col113),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_28_col114),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_29_col115),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_30_col116),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_31_col117),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_32_col118),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_33_col119),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_34_col120),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_35_col121),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_36_col122),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_37_col123),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_38_col124),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_39_col125),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_40_col126),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_41_col127),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_42_col128),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_43_col129),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_44_col130),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_45_col131),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_46_col132),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_47_col133),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_48_col134),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_49_col135),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_50_col136),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_51_col137),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_52_col138),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_53_col139),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_54_col140),
            eval!(context, pedersen_points_table_window_bits_9_output_limb_55_col141),
            eval!(context, slope_limb_0_col142),
            eval!(context, slope_limb_1_col143),
            eval!(context, slope_limb_2_col144),
            eval!(context, slope_limb_3_col145),
            eval!(context, slope_limb_4_col146),
            eval!(context, slope_limb_5_col147),
            eval!(context, slope_limb_6_col148),
            eval!(context, slope_limb_7_col149),
            eval!(context, slope_limb_8_col150),
            eval!(context, slope_limb_9_col151),
            eval!(context, slope_limb_10_col152),
            eval!(context, slope_limb_11_col153),
            eval!(context, slope_limb_12_col154),
            eval!(context, slope_limb_13_col155),
            eval!(context, slope_limb_14_col156),
            eval!(context, slope_limb_15_col157),
            eval!(context, slope_limb_16_col158),
            eval!(context, slope_limb_17_col159),
            eval!(context, slope_limb_18_col160),
            eval!(context, slope_limb_19_col161),
            eval!(context, slope_limb_20_col162),
            eval!(context, slope_limb_21_col163),
            eval!(context, slope_limb_22_col164),
            eval!(context, slope_limb_23_col165),
            eval!(context, slope_limb_24_col166),
            eval!(context, slope_limb_25_col167),
            eval!(context, slope_limb_26_col168),
            eval!(context, slope_limb_27_col169),
            eval!(context, k_col170),
            eval!(context, carry_0_col171),
            eval!(context, carry_1_col172),
            eval!(context, carry_2_col173),
            eval!(context, carry_3_col174),
            eval!(context, carry_4_col175),
            eval!(context, carry_5_col176),
            eval!(context, carry_6_col177),
            eval!(context, carry_7_col178),
            eval!(context, carry_8_col179),
            eval!(context, carry_9_col180),
            eval!(context, carry_10_col181),
            eval!(context, carry_11_col182),
            eval!(context, carry_12_col183),
            eval!(context, carry_13_col184),
            eval!(context, carry_14_col185),
            eval!(context, carry_15_col186),
            eval!(context, carry_16_col187),
            eval!(context, carry_17_col188),
            eval!(context, carry_18_col189),
            eval!(context, carry_19_col190),
            eval!(context, carry_20_col191),
            eval!(context, carry_21_col192),
            eval!(context, carry_22_col193),
            eval!(context, carry_23_col194),
            eval!(context, carry_24_col195),
            eval!(context, carry_25_col196),
            eval!(context, carry_26_col197),
            eval!(context, result_x_limb_0_col198),
            eval!(context, result_x_limb_1_col199),
            eval!(context, result_x_limb_2_col200),
            eval!(context, result_x_limb_3_col201),
            eval!(context, result_x_limb_4_col202),
            eval!(context, result_x_limb_5_col203),
            eval!(context, result_x_limb_6_col204),
            eval!(context, result_x_limb_7_col205),
            eval!(context, result_x_limb_8_col206),
            eval!(context, result_x_limb_9_col207),
            eval!(context, result_x_limb_10_col208),
            eval!(context, result_x_limb_11_col209),
            eval!(context, result_x_limb_12_col210),
            eval!(context, result_x_limb_13_col211),
            eval!(context, result_x_limb_14_col212),
            eval!(context, result_x_limb_15_col213),
            eval!(context, result_x_limb_16_col214),
            eval!(context, result_x_limb_17_col215),
            eval!(context, result_x_limb_18_col216),
            eval!(context, result_x_limb_19_col217),
            eval!(context, result_x_limb_20_col218),
            eval!(context, result_x_limb_21_col219),
            eval!(context, result_x_limb_22_col220),
            eval!(context, result_x_limb_23_col221),
            eval!(context, result_x_limb_24_col222),
            eval!(context, result_x_limb_25_col223),
            eval!(context, result_x_limb_26_col224),
            eval!(context, result_x_limb_27_col225),
            eval!(context, k_col226),
            eval!(context, carry_0_col227),
            eval!(context, carry_1_col228),
            eval!(context, carry_2_col229),
            eval!(context, carry_3_col230),
            eval!(context, carry_4_col231),
            eval!(context, carry_5_col232),
            eval!(context, carry_6_col233),
            eval!(context, carry_7_col234),
            eval!(context, carry_8_col235),
            eval!(context, carry_9_col236),
            eval!(context, carry_10_col237),
            eval!(context, carry_11_col238),
            eval!(context, carry_12_col239),
            eval!(context, carry_13_col240),
            eval!(context, carry_14_col241),
            eval!(context, carry_15_col242),
            eval!(context, carry_16_col243),
            eval!(context, carry_17_col244),
            eval!(context, carry_18_col245),
            eval!(context, carry_19_col246),
            eval!(context, carry_20_col247),
            eval!(context, carry_21_col248),
            eval!(context, carry_22_col249),
            eval!(context, carry_23_col250),
            eval!(context, carry_24_col251),
            eval!(context, carry_25_col252),
            eval!(context, carry_26_col253),
            eval!(context, result_y_limb_0_col254),
            eval!(context, result_y_limb_1_col255),
            eval!(context, result_y_limb_2_col256),
            eval!(context, result_y_limb_3_col257),
            eval!(context, result_y_limb_4_col258),
            eval!(context, result_y_limb_5_col259),
            eval!(context, result_y_limb_6_col260),
            eval!(context, result_y_limb_7_col261),
            eval!(context, result_y_limb_8_col262),
            eval!(context, result_y_limb_9_col263),
            eval!(context, result_y_limb_10_col264),
            eval!(context, result_y_limb_11_col265),
            eval!(context, result_y_limb_12_col266),
            eval!(context, result_y_limb_13_col267),
            eval!(context, result_y_limb_14_col268),
            eval!(context, result_y_limb_15_col269),
            eval!(context, result_y_limb_16_col270),
            eval!(context, result_y_limb_17_col271),
            eval!(context, result_y_limb_18_col272),
            eval!(context, result_y_limb_19_col273),
            eval!(context, result_y_limb_20_col274),
            eval!(context, result_y_limb_21_col275),
            eval!(context, result_y_limb_22_col276),
            eval!(context, result_y_limb_23_col277),
            eval!(context, result_y_limb_24_col278),
            eval!(context, result_y_limb_25_col279),
            eval!(context, result_y_limb_26_col280),
            eval!(context, result_y_limb_27_col281),
            eval!(context, k_col282),
            eval!(context, carry_0_col283),
            eval!(context, carry_1_col284),
            eval!(context, carry_2_col285),
            eval!(context, carry_3_col286),
            eval!(context, carry_4_col287),
            eval!(context, carry_5_col288),
            eval!(context, carry_6_col289),
            eval!(context, carry_7_col290),
            eval!(context, carry_8_col291),
            eval!(context, carry_9_col292),
            eval!(context, carry_10_col293),
            eval!(context, carry_11_col294),
            eval!(context, carry_12_col295),
            eval!(context, carry_13_col296),
            eval!(context, carry_14_col297),
            eval!(context, carry_15_col298),
            eval!(context, carry_16_col299),
            eval!(context, carry_17_col300),
            eval!(context, carry_18_col301),
            eval!(context, carry_19_col302),
            eval!(context, carry_20_col303),
            eval!(context, carry_21_col304),
            eval!(context, carry_22_col305),
            eval!(context, carry_23_col306),
            eval!(context, carry_24_col307),
            eval!(context, carry_25_col308),
            eval!(context, carry_26_col309),
        ],
        context,
        component_data,
        acc,
    );

    // Use PartialEcMulWindowBits9.
    let tuple_2 = &[
        eval!(context, 2038149019),
        eval!(context, input_limb_0_col0),
        eval!(context, input_limb_1_col1),
        eval!(context, input_limb_2_col2),
        eval!(context, input_limb_3_col3),
        eval!(context, input_limb_4_col4),
        eval!(context, input_limb_5_col5),
        eval!(context, input_limb_6_col6),
        eval!(context, input_limb_7_col7),
        eval!(context, input_limb_8_col8),
        eval!(context, input_limb_9_col9),
        eval!(context, input_limb_10_col10),
        eval!(context, input_limb_11_col11),
        eval!(context, input_limb_12_col12),
        eval!(context, input_limb_13_col13),
        eval!(context, input_limb_14_col14),
        eval!(context, input_limb_15_col15),
        eval!(context, input_limb_16_col16),
        eval!(context, input_limb_17_col17),
        eval!(context, input_limb_18_col18),
        eval!(context, input_limb_19_col19),
        eval!(context, input_limb_20_col20),
        eval!(context, input_limb_21_col21),
        eval!(context, input_limb_22_col22),
        eval!(context, input_limb_23_col23),
        eval!(context, input_limb_24_col24),
        eval!(context, input_limb_25_col25),
        eval!(context, input_limb_26_col26),
        eval!(context, input_limb_27_col27),
        eval!(context, input_limb_28_col28),
        eval!(context, input_limb_29_col29),
        eval!(context, input_limb_30_col30),
        eval!(context, input_limb_31_col31),
        eval!(context, input_limb_32_col32),
        eval!(context, input_limb_33_col33),
        eval!(context, input_limb_34_col34),
        eval!(context, input_limb_35_col35),
        eval!(context, input_limb_36_col36),
        eval!(context, input_limb_37_col37),
        eval!(context, input_limb_38_col38),
        eval!(context, input_limb_39_col39),
        eval!(context, input_limb_40_col40),
        eval!(context, input_limb_41_col41),
        eval!(context, input_limb_42_col42),
        eval!(context, input_limb_43_col43),
        eval!(context, input_limb_44_col44),
        eval!(context, input_limb_45_col45),
        eval!(context, input_limb_46_col46),
        eval!(context, input_limb_47_col47),
        eval!(context, input_limb_48_col48),
        eval!(context, input_limb_49_col49),
        eval!(context, input_limb_50_col50),
        eval!(context, input_limb_51_col51),
        eval!(context, input_limb_52_col52),
        eval!(context, input_limb_53_col53),
        eval!(context, input_limb_54_col54),
        eval!(context, input_limb_55_col55),
        eval!(context, input_limb_56_col56),
        eval!(context, input_limb_57_col57),
        eval!(context, input_limb_58_col58),
        eval!(context, input_limb_59_col59),
        eval!(context, input_limb_60_col60),
        eval!(context, input_limb_61_col61),
        eval!(context, input_limb_62_col62),
        eval!(context, input_limb_63_col63),
        eval!(context, input_limb_64_col64),
        eval!(context, input_limb_65_col65),
        eval!(context, input_limb_66_col66),
        eval!(context, input_limb_67_col67),
        eval!(context, input_limb_68_col68),
        eval!(context, input_limb_69_col69),
        eval!(context, input_limb_70_col70),
        eval!(context, input_limb_71_col71),
        eval!(context, input_limb_72_col72),
        eval!(context, input_limb_73_col73),
        eval!(context, input_limb_74_col74),
        eval!(context, input_limb_75_col75),
        eval!(context, input_limb_76_col76),
        eval!(context, input_limb_77_col77),
        eval!(context, input_limb_78_col78),
        eval!(context, input_limb_79_col79),
        eval!(context, input_limb_80_col80),
        eval!(context, input_limb_81_col81),
        eval!(context, input_limb_82_col82),
        eval!(context, input_limb_83_col83),
        eval!(context, input_limb_84_col84),
        eval!(context, input_limb_85_col85),
    ];
    let numerator_2 = eval!(context, enabler);
    acc.add_to_relation(context, numerator_2, tuple_2);

    // Yield PartialEcMulWindowBits9.
    let tuple_3 = &[
        eval!(context, 2038149019),
        eval!(context, input_limb_0_col0),
        eval!(context, (input_limb_1_col1) + (1)),
        eval!(context, input_limb_3_col3),
        eval!(context, input_limb_4_col4),
        eval!(context, input_limb_5_col5),
        eval!(context, input_limb_6_col6),
        eval!(context, input_limb_7_col7),
        eval!(context, input_limb_8_col8),
        eval!(context, input_limb_9_col9),
        eval!(context, input_limb_10_col10),
        eval!(context, input_limb_11_col11),
        eval!(context, input_limb_12_col12),
        eval!(context, input_limb_13_col13),
        eval!(context, input_limb_14_col14),
        eval!(context, input_limb_15_col15),
        eval!(context, input_limb_16_col16),
        eval!(context, input_limb_17_col17),
        eval!(context, input_limb_18_col18),
        eval!(context, input_limb_19_col19),
        eval!(context, input_limb_20_col20),
        eval!(context, input_limb_21_col21),
        eval!(context, input_limb_22_col22),
        eval!(context, input_limb_23_col23),
        eval!(context, input_limb_24_col24),
        eval!(context, input_limb_25_col25),
        eval!(context, input_limb_26_col26),
        eval!(context, input_limb_27_col27),
        eval!(context, input_limb_28_col28),
        eval!(context, input_limb_29_col29),
        eval!(context, 0),
        eval!(context, result_x_limb_0_col198),
        eval!(context, result_x_limb_1_col199),
        eval!(context, result_x_limb_2_col200),
        eval!(context, result_x_limb_3_col201),
        eval!(context, result_x_limb_4_col202),
        eval!(context, result_x_limb_5_col203),
        eval!(context, result_x_limb_6_col204),
        eval!(context, result_x_limb_7_col205),
        eval!(context, result_x_limb_8_col206),
        eval!(context, result_x_limb_9_col207),
        eval!(context, result_x_limb_10_col208),
        eval!(context, result_x_limb_11_col209),
        eval!(context, result_x_limb_12_col210),
        eval!(context, result_x_limb_13_col211),
        eval!(context, result_x_limb_14_col212),
        eval!(context, result_x_limb_15_col213),
        eval!(context, result_x_limb_16_col214),
        eval!(context, result_x_limb_17_col215),
        eval!(context, result_x_limb_18_col216),
        eval!(context, result_x_limb_19_col217),
        eval!(context, result_x_limb_20_col218),
        eval!(context, result_x_limb_21_col219),
        eval!(context, result_x_limb_22_col220),
        eval!(context, result_x_limb_23_col221),
        eval!(context, result_x_limb_24_col222),
        eval!(context, result_x_limb_25_col223),
        eval!(context, result_x_limb_26_col224),
        eval!(context, result_x_limb_27_col225),
        eval!(context, result_y_limb_0_col254),
        eval!(context, result_y_limb_1_col255),
        eval!(context, result_y_limb_2_col256),
        eval!(context, result_y_limb_3_col257),
        eval!(context, result_y_limb_4_col258),
        eval!(context, result_y_limb_5_col259),
        eval!(context, result_y_limb_6_col260),
        eval!(context, result_y_limb_7_col261),
        eval!(context, result_y_limb_8_col262),
        eval!(context, result_y_limb_9_col263),
        eval!(context, result_y_limb_10_col264),
        eval!(context, result_y_limb_11_col265),
        eval!(context, result_y_limb_12_col266),
        eval!(context, result_y_limb_13_col267),
        eval!(context, result_y_limb_14_col268),
        eval!(context, result_y_limb_15_col269),
        eval!(context, result_y_limb_16_col270),
        eval!(context, result_y_limb_17_col271),
        eval!(context, result_y_limb_18_col272),
        eval!(context, result_y_limb_19_col273),
        eval!(context, result_y_limb_20_col274),
        eval!(context, result_y_limb_21_col275),
        eval!(context, result_y_limb_22_col276),
        eval!(context, result_y_limb_23_col277),
        eval!(context, result_y_limb_24_col278),
        eval!(context, result_y_limb_25_col279),
        eval!(context, result_y_limb_26_col280),
        eval!(context, result_y_limb_27_col281),
    ];
    let numerator_3 = eval!(context, -(enabler));
    acc.add_to_relation(context, numerator_3, tuple_3);
}

pub struct Component {}
impl<Value: IValue> CircuitEval<Value> for Component {
    fn evaluate(
        &self,
        context: &mut Context<Value>,
        component_data: &ComponentData<'_>,
        acc: &mut CompositionConstraintAccumulator,
    ) {
        accumulate_constraints(component_data.trace_columns, context, component_data, acc);
    }

    fn trace_columns(&self) -> usize {
        N_TRACE_COLUMNS
    }

    fn interaction_columns(&self) -> usize {
        N_INTERACTION_COLUMNS
    }

    fn relation_uses_per_row(&self) -> &[RelationUse] {
        &RELATION_USES_PER_ROW
    }
}
