// This file was created by the AIR team.

use crate::cairo_air::components::prelude::*;

pub const N_TRACE_COLUMNS: usize = 234;
pub const N_INTERACTION_COLUMNS: usize = 24;

pub const RELATION_USES_PER_ROW: [RelationUse; 3] = [
    RelationUse { relation_id: "MemoryIdToBig", uses: 3 },
    RelationUse { relation_id: "PartialEcMulWindowBits9", uses: 2 },
    RelationUse { relation_id: "RangeCheck_8", uses: 4 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints(
    input: &[Var],
    context: &mut Context<impl IValue>,
    component_data: &ComponentData<'_>,
    acc: &mut CompositionConstraintAccumulator,
) {
    let [
        input_limb_0_col0,
        input_limb_1_col1,
        input_limb_2_col2,
        value_limb_0_col3,
        value_limb_1_col4,
        value_limb_2_col5,
        value_limb_3_col6,
        value_limb_4_col7,
        value_limb_5_col8,
        value_limb_6_col9,
        value_limb_7_col10,
        value_limb_8_col11,
        value_limb_9_col12,
        value_limb_10_col13,
        value_limb_11_col14,
        value_limb_12_col15,
        value_limb_13_col16,
        value_limb_14_col17,
        value_limb_15_col18,
        value_limb_16_col19,
        value_limb_17_col20,
        value_limb_18_col21,
        value_limb_19_col22,
        value_limb_20_col23,
        value_limb_21_col24,
        value_limb_22_col25,
        value_limb_23_col26,
        value_limb_24_col27,
        value_limb_25_col28,
        value_limb_26_col29,
        value_limb_27_col30,
        value_limb_0_col31,
        value_limb_1_col32,
        value_limb_2_col33,
        value_limb_3_col34,
        value_limb_4_col35,
        value_limb_5_col36,
        value_limb_6_col37,
        value_limb_7_col38,
        value_limb_8_col39,
        value_limb_9_col40,
        value_limb_10_col41,
        value_limb_11_col42,
        value_limb_12_col43,
        value_limb_13_col44,
        value_limb_14_col45,
        value_limb_15_col46,
        value_limb_16_col47,
        value_limb_17_col48,
        value_limb_18_col49,
        value_limb_19_col50,
        value_limb_20_col51,
        value_limb_21_col52,
        value_limb_22_col53,
        value_limb_23_col54,
        value_limb_24_col55,
        value_limb_25_col56,
        value_limb_26_col57,
        value_limb_27_col58,
        ms_limb_is_max_col59,
        ms_and_mid_limbs_are_max_col60,
        rc_input_col61,
        ms_limb_is_max_col62,
        ms_and_mid_limbs_are_max_col63,
        rc_input_col64,
        partial_ec_mul_window_bits_9_output_limb_0_col65,
        partial_ec_mul_window_bits_9_output_limb_1_col66,
        partial_ec_mul_window_bits_9_output_limb_2_col67,
        partial_ec_mul_window_bits_9_output_limb_3_col68,
        partial_ec_mul_window_bits_9_output_limb_4_col69,
        partial_ec_mul_window_bits_9_output_limb_5_col70,
        partial_ec_mul_window_bits_9_output_limb_6_col71,
        partial_ec_mul_window_bits_9_output_limb_7_col72,
        partial_ec_mul_window_bits_9_output_limb_8_col73,
        partial_ec_mul_window_bits_9_output_limb_9_col74,
        partial_ec_mul_window_bits_9_output_limb_10_col75,
        partial_ec_mul_window_bits_9_output_limb_11_col76,
        partial_ec_mul_window_bits_9_output_limb_12_col77,
        partial_ec_mul_window_bits_9_output_limb_13_col78,
        partial_ec_mul_window_bits_9_output_limb_14_col79,
        partial_ec_mul_window_bits_9_output_limb_15_col80,
        partial_ec_mul_window_bits_9_output_limb_16_col81,
        partial_ec_mul_window_bits_9_output_limb_17_col82,
        partial_ec_mul_window_bits_9_output_limb_18_col83,
        partial_ec_mul_window_bits_9_output_limb_19_col84,
        partial_ec_mul_window_bits_9_output_limb_20_col85,
        partial_ec_mul_window_bits_9_output_limb_21_col86,
        partial_ec_mul_window_bits_9_output_limb_22_col87,
        partial_ec_mul_window_bits_9_output_limb_23_col88,
        partial_ec_mul_window_bits_9_output_limb_24_col89,
        partial_ec_mul_window_bits_9_output_limb_25_col90,
        partial_ec_mul_window_bits_9_output_limb_26_col91,
        partial_ec_mul_window_bits_9_output_limb_27_col92,
        partial_ec_mul_window_bits_9_output_limb_28_col93,
        partial_ec_mul_window_bits_9_output_limb_29_col94,
        partial_ec_mul_window_bits_9_output_limb_30_col95,
        partial_ec_mul_window_bits_9_output_limb_31_col96,
        partial_ec_mul_window_bits_9_output_limb_32_col97,
        partial_ec_mul_window_bits_9_output_limb_33_col98,
        partial_ec_mul_window_bits_9_output_limb_34_col99,
        partial_ec_mul_window_bits_9_output_limb_35_col100,
        partial_ec_mul_window_bits_9_output_limb_36_col101,
        partial_ec_mul_window_bits_9_output_limb_37_col102,
        partial_ec_mul_window_bits_9_output_limb_38_col103,
        partial_ec_mul_window_bits_9_output_limb_39_col104,
        partial_ec_mul_window_bits_9_output_limb_40_col105,
        partial_ec_mul_window_bits_9_output_limb_41_col106,
        partial_ec_mul_window_bits_9_output_limb_42_col107,
        partial_ec_mul_window_bits_9_output_limb_43_col108,
        partial_ec_mul_window_bits_9_output_limb_44_col109,
        partial_ec_mul_window_bits_9_output_limb_45_col110,
        partial_ec_mul_window_bits_9_output_limb_46_col111,
        partial_ec_mul_window_bits_9_output_limb_47_col112,
        partial_ec_mul_window_bits_9_output_limb_48_col113,
        partial_ec_mul_window_bits_9_output_limb_49_col114,
        partial_ec_mul_window_bits_9_output_limb_50_col115,
        partial_ec_mul_window_bits_9_output_limb_51_col116,
        partial_ec_mul_window_bits_9_output_limb_52_col117,
        partial_ec_mul_window_bits_9_output_limb_53_col118,
        partial_ec_mul_window_bits_9_output_limb_54_col119,
        partial_ec_mul_window_bits_9_output_limb_55_col120,
        partial_ec_mul_window_bits_9_output_limb_56_col121,
        partial_ec_mul_window_bits_9_output_limb_57_col122,
        partial_ec_mul_window_bits_9_output_limb_58_col123,
        partial_ec_mul_window_bits_9_output_limb_59_col124,
        partial_ec_mul_window_bits_9_output_limb_60_col125,
        partial_ec_mul_window_bits_9_output_limb_61_col126,
        partial_ec_mul_window_bits_9_output_limb_62_col127,
        partial_ec_mul_window_bits_9_output_limb_63_col128,
        partial_ec_mul_window_bits_9_output_limb_64_col129,
        partial_ec_mul_window_bits_9_output_limb_65_col130,
        partial_ec_mul_window_bits_9_output_limb_66_col131,
        partial_ec_mul_window_bits_9_output_limb_67_col132,
        partial_ec_mul_window_bits_9_output_limb_68_col133,
        partial_ec_mul_window_bits_9_output_limb_69_col134,
        partial_ec_mul_window_bits_9_output_limb_70_col135,
        partial_ec_mul_window_bits_9_output_limb_71_col136,
        partial_ec_mul_window_bits_9_output_limb_72_col137,
        partial_ec_mul_window_bits_9_output_limb_73_col138,
        partial_ec_mul_window_bits_9_output_limb_74_col139,
        partial_ec_mul_window_bits_9_output_limb_75_col140,
        partial_ec_mul_window_bits_9_output_limb_76_col141,
        partial_ec_mul_window_bits_9_output_limb_77_col142,
        partial_ec_mul_window_bits_9_output_limb_78_col143,
        partial_ec_mul_window_bits_9_output_limb_79_col144,
        partial_ec_mul_window_bits_9_output_limb_80_col145,
        partial_ec_mul_window_bits_9_output_limb_81_col146,
        partial_ec_mul_window_bits_9_output_limb_82_col147,
        partial_ec_mul_window_bits_9_output_limb_83_col148,
        partial_ec_mul_window_bits_9_output_limb_0_col149,
        partial_ec_mul_window_bits_9_output_limb_1_col150,
        partial_ec_mul_window_bits_9_output_limb_2_col151,
        partial_ec_mul_window_bits_9_output_limb_3_col152,
        partial_ec_mul_window_bits_9_output_limb_4_col153,
        partial_ec_mul_window_bits_9_output_limb_5_col154,
        partial_ec_mul_window_bits_9_output_limb_6_col155,
        partial_ec_mul_window_bits_9_output_limb_7_col156,
        partial_ec_mul_window_bits_9_output_limb_8_col157,
        partial_ec_mul_window_bits_9_output_limb_9_col158,
        partial_ec_mul_window_bits_9_output_limb_10_col159,
        partial_ec_mul_window_bits_9_output_limb_11_col160,
        partial_ec_mul_window_bits_9_output_limb_12_col161,
        partial_ec_mul_window_bits_9_output_limb_13_col162,
        partial_ec_mul_window_bits_9_output_limb_14_col163,
        partial_ec_mul_window_bits_9_output_limb_15_col164,
        partial_ec_mul_window_bits_9_output_limb_16_col165,
        partial_ec_mul_window_bits_9_output_limb_17_col166,
        partial_ec_mul_window_bits_9_output_limb_18_col167,
        partial_ec_mul_window_bits_9_output_limb_19_col168,
        partial_ec_mul_window_bits_9_output_limb_20_col169,
        partial_ec_mul_window_bits_9_output_limb_21_col170,
        partial_ec_mul_window_bits_9_output_limb_22_col171,
        partial_ec_mul_window_bits_9_output_limb_23_col172,
        partial_ec_mul_window_bits_9_output_limb_24_col173,
        partial_ec_mul_window_bits_9_output_limb_25_col174,
        partial_ec_mul_window_bits_9_output_limb_26_col175,
        partial_ec_mul_window_bits_9_output_limb_27_col176,
        partial_ec_mul_window_bits_9_output_limb_28_col177,
        partial_ec_mul_window_bits_9_output_limb_29_col178,
        partial_ec_mul_window_bits_9_output_limb_30_col179,
        partial_ec_mul_window_bits_9_output_limb_31_col180,
        partial_ec_mul_window_bits_9_output_limb_32_col181,
        partial_ec_mul_window_bits_9_output_limb_33_col182,
        partial_ec_mul_window_bits_9_output_limb_34_col183,
        partial_ec_mul_window_bits_9_output_limb_35_col184,
        partial_ec_mul_window_bits_9_output_limb_36_col185,
        partial_ec_mul_window_bits_9_output_limb_37_col186,
        partial_ec_mul_window_bits_9_output_limb_38_col187,
        partial_ec_mul_window_bits_9_output_limb_39_col188,
        partial_ec_mul_window_bits_9_output_limb_40_col189,
        partial_ec_mul_window_bits_9_output_limb_41_col190,
        partial_ec_mul_window_bits_9_output_limb_42_col191,
        partial_ec_mul_window_bits_9_output_limb_43_col192,
        partial_ec_mul_window_bits_9_output_limb_44_col193,
        partial_ec_mul_window_bits_9_output_limb_45_col194,
        partial_ec_mul_window_bits_9_output_limb_46_col195,
        partial_ec_mul_window_bits_9_output_limb_47_col196,
        partial_ec_mul_window_bits_9_output_limb_48_col197,
        partial_ec_mul_window_bits_9_output_limb_49_col198,
        partial_ec_mul_window_bits_9_output_limb_50_col199,
        partial_ec_mul_window_bits_9_output_limb_51_col200,
        partial_ec_mul_window_bits_9_output_limb_52_col201,
        partial_ec_mul_window_bits_9_output_limb_53_col202,
        partial_ec_mul_window_bits_9_output_limb_54_col203,
        partial_ec_mul_window_bits_9_output_limb_55_col204,
        partial_ec_mul_window_bits_9_output_limb_56_col205,
        partial_ec_mul_window_bits_9_output_limb_57_col206,
        partial_ec_mul_window_bits_9_output_limb_58_col207,
        partial_ec_mul_window_bits_9_output_limb_59_col208,
        partial_ec_mul_window_bits_9_output_limb_60_col209,
        partial_ec_mul_window_bits_9_output_limb_61_col210,
        partial_ec_mul_window_bits_9_output_limb_62_col211,
        partial_ec_mul_window_bits_9_output_limb_63_col212,
        partial_ec_mul_window_bits_9_output_limb_64_col213,
        partial_ec_mul_window_bits_9_output_limb_65_col214,
        partial_ec_mul_window_bits_9_output_limb_66_col215,
        partial_ec_mul_window_bits_9_output_limb_67_col216,
        partial_ec_mul_window_bits_9_output_limb_68_col217,
        partial_ec_mul_window_bits_9_output_limb_69_col218,
        partial_ec_mul_window_bits_9_output_limb_70_col219,
        partial_ec_mul_window_bits_9_output_limb_71_col220,
        partial_ec_mul_window_bits_9_output_limb_72_col221,
        partial_ec_mul_window_bits_9_output_limb_73_col222,
        partial_ec_mul_window_bits_9_output_limb_74_col223,
        partial_ec_mul_window_bits_9_output_limb_75_col224,
        partial_ec_mul_window_bits_9_output_limb_76_col225,
        partial_ec_mul_window_bits_9_output_limb_77_col226,
        partial_ec_mul_window_bits_9_output_limb_78_col227,
        partial_ec_mul_window_bits_9_output_limb_79_col228,
        partial_ec_mul_window_bits_9_output_limb_80_col229,
        partial_ec_mul_window_bits_9_output_limb_81_col230,
        partial_ec_mul_window_bits_9_output_limb_82_col231,
        partial_ec_mul_window_bits_9_output_limb_83_col232,
        multiplicity_0,
    ] = input.try_into().unwrap();
    let seq = seq_of_component_size(context, component_data, acc);

    read_positive_known_id_num_bits_252::accumulate_constraints(
        &[
            eval!(context, input_limb_0_col0),
            eval!(context, value_limb_0_col3),
            eval!(context, value_limb_1_col4),
            eval!(context, value_limb_2_col5),
            eval!(context, value_limb_3_col6),
            eval!(context, value_limb_4_col7),
            eval!(context, value_limb_5_col8),
            eval!(context, value_limb_6_col9),
            eval!(context, value_limb_7_col10),
            eval!(context, value_limb_8_col11),
            eval!(context, value_limb_9_col12),
            eval!(context, value_limb_10_col13),
            eval!(context, value_limb_11_col14),
            eval!(context, value_limb_12_col15),
            eval!(context, value_limb_13_col16),
            eval!(context, value_limb_14_col17),
            eval!(context, value_limb_15_col18),
            eval!(context, value_limb_16_col19),
            eval!(context, value_limb_17_col20),
            eval!(context, value_limb_18_col21),
            eval!(context, value_limb_19_col22),
            eval!(context, value_limb_20_col23),
            eval!(context, value_limb_21_col24),
            eval!(context, value_limb_22_col25),
            eval!(context, value_limb_23_col26),
            eval!(context, value_limb_24_col27),
            eval!(context, value_limb_25_col28),
            eval!(context, value_limb_26_col29),
            eval!(context, value_limb_27_col30),
        ],
        context,
        component_data,
        acc,
    );

    read_positive_known_id_num_bits_252::accumulate_constraints(
        &[
            eval!(context, input_limb_1_col1),
            eval!(context, value_limb_0_col31),
            eval!(context, value_limb_1_col32),
            eval!(context, value_limb_2_col33),
            eval!(context, value_limb_3_col34),
            eval!(context, value_limb_4_col35),
            eval!(context, value_limb_5_col36),
            eval!(context, value_limb_6_col37),
            eval!(context, value_limb_7_col38),
            eval!(context, value_limb_8_col39),
            eval!(context, value_limb_9_col40),
            eval!(context, value_limb_10_col41),
            eval!(context, value_limb_11_col42),
            eval!(context, value_limb_12_col43),
            eval!(context, value_limb_13_col44),
            eval!(context, value_limb_14_col45),
            eval!(context, value_limb_15_col46),
            eval!(context, value_limb_16_col47),
            eval!(context, value_limb_17_col48),
            eval!(context, value_limb_18_col49),
            eval!(context, value_limb_19_col50),
            eval!(context, value_limb_20_col51),
            eval!(context, value_limb_21_col52),
            eval!(context, value_limb_22_col53),
            eval!(context, value_limb_23_col54),
            eval!(context, value_limb_24_col55),
            eval!(context, value_limb_25_col56),
            eval!(context, value_limb_26_col57),
            eval!(context, value_limb_27_col58),
        ],
        context,
        component_data,
        acc,
    );

    verify_reduced_252::accumulate_constraints(
        &[
            eval!(context, value_limb_0_col3),
            eval!(context, value_limb_1_col4),
            eval!(context, value_limb_2_col5),
            eval!(context, value_limb_3_col6),
            eval!(context, value_limb_4_col7),
            eval!(context, value_limb_5_col8),
            eval!(context, value_limb_6_col9),
            eval!(context, value_limb_7_col10),
            eval!(context, value_limb_8_col11),
            eval!(context, value_limb_9_col12),
            eval!(context, value_limb_10_col13),
            eval!(context, value_limb_11_col14),
            eval!(context, value_limb_12_col15),
            eval!(context, value_limb_13_col16),
            eval!(context, value_limb_14_col17),
            eval!(context, value_limb_15_col18),
            eval!(context, value_limb_16_col19),
            eval!(context, value_limb_17_col20),
            eval!(context, value_limb_18_col21),
            eval!(context, value_limb_19_col22),
            eval!(context, value_limb_20_col23),
            eval!(context, value_limb_21_col24),
            eval!(context, value_limb_22_col25),
            eval!(context, value_limb_23_col26),
            eval!(context, value_limb_24_col27),
            eval!(context, value_limb_25_col28),
            eval!(context, value_limb_26_col29),
            eval!(context, value_limb_27_col30),
            eval!(context, ms_limb_is_max_col59),
            eval!(context, ms_and_mid_limbs_are_max_col60),
            eval!(context, rc_input_col61),
        ],
        context,
        component_data,
        acc,
    );

    verify_reduced_252::accumulate_constraints(
        &[
            eval!(context, value_limb_0_col31),
            eval!(context, value_limb_1_col32),
            eval!(context, value_limb_2_col33),
            eval!(context, value_limb_3_col34),
            eval!(context, value_limb_4_col35),
            eval!(context, value_limb_5_col36),
            eval!(context, value_limb_6_col37),
            eval!(context, value_limb_7_col38),
            eval!(context, value_limb_8_col39),
            eval!(context, value_limb_9_col40),
            eval!(context, value_limb_10_col41),
            eval!(context, value_limb_11_col42),
            eval!(context, value_limb_12_col43),
            eval!(context, value_limb_13_col44),
            eval!(context, value_limb_14_col45),
            eval!(context, value_limb_15_col46),
            eval!(context, value_limb_16_col47),
            eval!(context, value_limb_17_col48),
            eval!(context, value_limb_18_col49),
            eval!(context, value_limb_19_col50),
            eval!(context, value_limb_20_col51),
            eval!(context, value_limb_21_col52),
            eval!(context, value_limb_22_col53),
            eval!(context, value_limb_23_col54),
            eval!(context, value_limb_24_col55),
            eval!(context, value_limb_25_col56),
            eval!(context, value_limb_26_col57),
            eval!(context, value_limb_27_col58),
            eval!(context, ms_limb_is_max_col62),
            eval!(context, ms_and_mid_limbs_are_max_col63),
            eval!(context, rc_input_col64),
        ],
        context,
        component_data,
        acc,
    );

    let partial_ec_mul_window_bits_9_chain_tmp_tmp_344c0_8 = eval!(context, (seq) * (2));

    // Yield PartialEcMulWindowBits9.
    let tuple_5 = &[
        eval!(context, 2038149019),
        eval!(context, partial_ec_mul_window_bits_9_chain_tmp_tmp_344c0_8),
        eval!(context, 0),
        eval!(context, value_limb_0_col3),
        eval!(context, value_limb_1_col4),
        eval!(context, value_limb_2_col5),
        eval!(context, value_limb_3_col6),
        eval!(context, value_limb_4_col7),
        eval!(context, value_limb_5_col8),
        eval!(context, value_limb_6_col9),
        eval!(context, value_limb_7_col10),
        eval!(context, value_limb_8_col11),
        eval!(context, value_limb_9_col12),
        eval!(context, value_limb_10_col13),
        eval!(context, value_limb_11_col14),
        eval!(context, value_limb_12_col15),
        eval!(context, value_limb_13_col16),
        eval!(context, value_limb_14_col17),
        eval!(context, value_limb_15_col18),
        eval!(context, value_limb_16_col19),
        eval!(context, value_limb_17_col20),
        eval!(context, value_limb_18_col21),
        eval!(context, value_limb_19_col22),
        eval!(context, value_limb_20_col23),
        eval!(context, value_limb_21_col24),
        eval!(context, value_limb_22_col25),
        eval!(context, value_limb_23_col26),
        eval!(context, value_limb_24_col27),
        eval!(context, value_limb_25_col28),
        eval!(context, value_limb_26_col29),
        eval!(context, value_limb_27_col30),
        eval!(context, 427),
        eval!(context, 381),
        eval!(context, 378),
        eval!(context, 484),
        eval!(context, 320),
        eval!(context, 88),
        eval!(context, 319),
        eval!(context, 396),
        eval!(context, 429),
        eval!(context, 59),
        eval!(context, 52),
        eval!(context, 478),
        eval!(context, 148),
        eval!(context, 181),
        eval!(context, 18),
        eval!(context, 309),
        eval!(context, 412),
        eval!(context, 88),
        eval!(context, 2),
        eval!(context, 184),
        eval!(context, 126),
        eval!(context, 46),
        eval!(context, 29),
        eval!(context, 206),
        eval!(context, 134),
        eval!(context, 233),
        eval!(context, 448),
        eval!(context, 211),
        eval!(context, 508),
        eval!(context, 420),
        eval!(context, 374),
        eval!(context, 283),
        eval!(context, 306),
        eval!(context, 450),
        eval!(context, 278),
        eval!(context, 86),
        eval!(context, 131),
        eval!(context, 160),
        eval!(context, 411),
        eval!(context, 301),
        eval!(context, 264),
        eval!(context, 322),
        eval!(context, 161),
        eval!(context, 346),
        eval!(context, 320),
        eval!(context, 342),
        eval!(context, 261),
        eval!(context, 184),
        eval!(context, 280),
        eval!(context, 326),
        eval!(context, 220),
        eval!(context, 167),
        eval!(context, 21),
        eval!(context, 260),
        eval!(context, 19),
        eval!(context, 199),
    ];
    let numerator_5 = eval!(context, -(1));
    acc.add_to_relation(context, numerator_5, tuple_5);

    // Use PartialEcMulWindowBits9.
    let tuple_6 = &[
        eval!(context, 2038149019),
        eval!(context, partial_ec_mul_window_bits_9_chain_tmp_tmp_344c0_8),
        eval!(context, 28),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_0_col65),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_1_col66),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_2_col67),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_3_col68),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_4_col69),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_5_col70),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_6_col71),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_7_col72),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_8_col73),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_9_col74),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_10_col75),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_11_col76),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_12_col77),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_13_col78),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_14_col79),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_15_col80),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_16_col81),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_17_col82),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_18_col83),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_19_col84),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_20_col85),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_21_col86),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_22_col87),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_23_col88),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_24_col89),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_25_col90),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_26_col91),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_27_col92),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_28_col93),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_29_col94),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_30_col95),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_31_col96),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_32_col97),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_33_col98),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_34_col99),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_35_col100),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_36_col101),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_37_col102),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_38_col103),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_39_col104),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_40_col105),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_41_col106),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_42_col107),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_43_col108),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_44_col109),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_45_col110),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_46_col111),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_47_col112),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_48_col113),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_49_col114),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_50_col115),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_51_col116),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_52_col117),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_53_col118),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_54_col119),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_55_col120),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_56_col121),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_57_col122),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_58_col123),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_59_col124),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_60_col125),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_61_col126),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_62_col127),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_63_col128),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_64_col129),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_65_col130),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_66_col131),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_67_col132),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_68_col133),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_69_col134),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_70_col135),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_71_col136),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_72_col137),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_73_col138),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_74_col139),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_75_col140),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_76_col141),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_77_col142),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_78_col143),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_79_col144),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_80_col145),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_81_col146),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_82_col147),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_83_col148),
    ];
    let numerator_6 = eval!(context, 1);
    acc.add_to_relation(context, numerator_6, tuple_6);

    let partial_ec_mul_window_bits_9_chain_id_tmp_344c0_37 =
        eval!(context, (partial_ec_mul_window_bits_9_chain_tmp_tmp_344c0_8) + (1));

    // Yield PartialEcMulWindowBits9.
    let tuple_8 = &[
        eval!(context, 2038149019),
        eval!(context, partial_ec_mul_window_bits_9_chain_id_tmp_344c0_37),
        eval!(context, 28),
        eval!(context, value_limb_0_col31),
        eval!(context, value_limb_1_col32),
        eval!(context, value_limb_2_col33),
        eval!(context, value_limb_3_col34),
        eval!(context, value_limb_4_col35),
        eval!(context, value_limb_5_col36),
        eval!(context, value_limb_6_col37),
        eval!(context, value_limb_7_col38),
        eval!(context, value_limb_8_col39),
        eval!(context, value_limb_9_col40),
        eval!(context, value_limb_10_col41),
        eval!(context, value_limb_11_col42),
        eval!(context, value_limb_12_col43),
        eval!(context, value_limb_13_col44),
        eval!(context, value_limb_14_col45),
        eval!(context, value_limb_15_col46),
        eval!(context, value_limb_16_col47),
        eval!(context, value_limb_17_col48),
        eval!(context, value_limb_18_col49),
        eval!(context, value_limb_19_col50),
        eval!(context, value_limb_20_col51),
        eval!(context, value_limb_21_col52),
        eval!(context, value_limb_22_col53),
        eval!(context, value_limb_23_col54),
        eval!(context, value_limb_24_col55),
        eval!(context, value_limb_25_col56),
        eval!(context, value_limb_26_col57),
        eval!(context, value_limb_27_col58),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_28_col93),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_29_col94),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_30_col95),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_31_col96),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_32_col97),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_33_col98),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_34_col99),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_35_col100),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_36_col101),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_37_col102),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_38_col103),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_39_col104),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_40_col105),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_41_col106),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_42_col107),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_43_col108),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_44_col109),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_45_col110),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_46_col111),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_47_col112),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_48_col113),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_49_col114),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_50_col115),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_51_col116),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_52_col117),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_53_col118),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_54_col119),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_55_col120),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_56_col121),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_57_col122),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_58_col123),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_59_col124),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_60_col125),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_61_col126),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_62_col127),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_63_col128),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_64_col129),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_65_col130),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_66_col131),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_67_col132),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_68_col133),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_69_col134),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_70_col135),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_71_col136),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_72_col137),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_73_col138),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_74_col139),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_75_col140),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_76_col141),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_77_col142),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_78_col143),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_79_col144),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_80_col145),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_81_col146),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_82_col147),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_83_col148),
    ];
    let numerator_8 = eval!(context, -(1));
    acc.add_to_relation(context, numerator_8, tuple_8);

    // Use PartialEcMulWindowBits9.
    let tuple_9 = &[
        eval!(context, 2038149019),
        eval!(context, partial_ec_mul_window_bits_9_chain_id_tmp_344c0_37),
        eval!(context, 56),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_0_col149),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_1_col150),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_2_col151),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_3_col152),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_4_col153),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_5_col154),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_6_col155),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_7_col156),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_8_col157),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_9_col158),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_10_col159),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_11_col160),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_12_col161),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_13_col162),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_14_col163),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_15_col164),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_16_col165),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_17_col166),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_18_col167),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_19_col168),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_20_col169),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_21_col170),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_22_col171),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_23_col172),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_24_col173),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_25_col174),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_26_col175),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_27_col176),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_28_col177),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_29_col178),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_30_col179),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_31_col180),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_32_col181),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_33_col182),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_34_col183),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_35_col184),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_36_col185),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_37_col186),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_38_col187),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_39_col188),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_40_col189),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_41_col190),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_42_col191),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_43_col192),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_44_col193),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_45_col194),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_46_col195),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_47_col196),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_48_col197),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_49_col198),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_50_col199),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_51_col200),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_52_col201),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_53_col202),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_54_col203),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_55_col204),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_56_col205),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_57_col206),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_58_col207),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_59_col208),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_60_col209),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_61_col210),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_62_col211),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_63_col212),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_64_col213),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_65_col214),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_66_col215),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_67_col216),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_68_col217),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_69_col218),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_70_col219),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_71_col220),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_72_col221),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_73_col222),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_74_col223),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_75_col224),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_76_col225),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_77_col226),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_78_col227),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_79_col228),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_80_col229),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_81_col230),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_82_col231),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_83_col232),
    ];
    let numerator_9 = eval!(context, 1);
    acc.add_to_relation(context, numerator_9, tuple_9);

    // Use MemoryIdToBig.
    let tuple_10 = &[
        eval!(context, 1662111297),
        eval!(context, input_limb_2_col2),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_28_col177),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_29_col178),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_30_col179),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_31_col180),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_32_col181),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_33_col182),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_34_col183),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_35_col184),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_36_col185),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_37_col186),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_38_col187),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_39_col188),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_40_col189),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_41_col190),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_42_col191),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_43_col192),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_44_col193),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_45_col194),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_46_col195),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_47_col196),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_48_col197),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_49_col198),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_50_col199),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_51_col200),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_52_col201),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_53_col202),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_54_col203),
        eval!(context, partial_ec_mul_window_bits_9_output_limb_55_col204),
    ];
    let numerator_10 = eval!(context, 1);
    acc.add_to_relation(context, numerator_10, tuple_10);

    // Yield PedersenAggregatorWindowBits9.
    let tuple_11 = &[
        eval!(context, 194336987),
        eval!(context, input_limb_0_col0),
        eval!(context, input_limb_1_col1),
        eval!(context, input_limb_2_col2),
    ];
    let numerator_11 = eval!(context, -(multiplicity_0));
    acc.add_to_relation(context, numerator_11, tuple_11);
}

pub struct Component {}
impl<Value: IValue> CircuitEval<Value> for Component {
    fn evaluate(
        &self,
        context: &mut Context<Value>,
        component_data: &ComponentData<'_>,
        acc: &mut CompositionConstraintAccumulator,
    ) {
        accumulate_constraints(component_data.trace_columns, context, component_data, acc);
    }

    fn trace_columns(&self) -> usize {
        N_TRACE_COLUMNS
    }

    fn interaction_columns(&self) -> usize {
        N_INTERACTION_COLUMNS
    }

    fn relation_uses_per_row(&self) -> &[RelationUse] {
        &RELATION_USES_PER_ROW
    }
}
