// This file was created by the AIR team.

use crate::cairo_air::components::prelude::*;

pub const N_TRACE_COLUMNS: usize = 169;
pub const N_INTERACTION_COLUMNS: usize = 36;

pub const RELATION_USES_PER_ROW: [RelationUse; 6] = [
    RelationUse { relation_id: "Cube252", uses: 3 },
    RelationUse { relation_id: "Poseidon3PartialRoundsChain", uses: 1 },
    RelationUse { relation_id: "PoseidonRoundKeys", uses: 1 },
    RelationUse { relation_id: "RangeCheck252Width27", uses: 3 },
    RelationUse { relation_id: "RangeCheck_4_4", uses: 3 },
    RelationUse { relation_id: "RangeCheck_4_4_4_4", uses: 6 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints(
    input: &[Var],
    context: &mut Context<impl IValue>,
    component_data: &ComponentData<'_>,
    acc: &mut CompositionConstraintAccumulator,
) {
    let [
        input_limb_0_col0,
        input_limb_1_col1,
        input_limb_2_col2,
        input_limb_3_col3,
        input_limb_4_col4,
        input_limb_5_col5,
        input_limb_6_col6,
        input_limb_7_col7,
        input_limb_8_col8,
        input_limb_9_col9,
        input_limb_10_col10,
        input_limb_11_col11,
        input_limb_12_col12,
        input_limb_13_col13,
        input_limb_14_col14,
        input_limb_15_col15,
        input_limb_16_col16,
        input_limb_17_col17,
        input_limb_18_col18,
        input_limb_19_col19,
        input_limb_20_col20,
        input_limb_21_col21,
        input_limb_22_col22,
        input_limb_23_col23,
        input_limb_24_col24,
        input_limb_25_col25,
        input_limb_26_col26,
        input_limb_27_col27,
        input_limb_28_col28,
        input_limb_29_col29,
        input_limb_30_col30,
        input_limb_31_col31,
        input_limb_32_col32,
        input_limb_33_col33,
        input_limb_34_col34,
        input_limb_35_col35,
        input_limb_36_col36,
        input_limb_37_col37,
        input_limb_38_col38,
        input_limb_39_col39,
        input_limb_40_col40,
        input_limb_41_col41,
        poseidon_round_keys_output_limb_0_col42,
        poseidon_round_keys_output_limb_1_col43,
        poseidon_round_keys_output_limb_2_col44,
        poseidon_round_keys_output_limb_3_col45,
        poseidon_round_keys_output_limb_4_col46,
        poseidon_round_keys_output_limb_5_col47,
        poseidon_round_keys_output_limb_6_col48,
        poseidon_round_keys_output_limb_7_col49,
        poseidon_round_keys_output_limb_8_col50,
        poseidon_round_keys_output_limb_9_col51,
        poseidon_round_keys_output_limb_10_col52,
        poseidon_round_keys_output_limb_11_col53,
        poseidon_round_keys_output_limb_12_col54,
        poseidon_round_keys_output_limb_13_col55,
        poseidon_round_keys_output_limb_14_col56,
        poseidon_round_keys_output_limb_15_col57,
        poseidon_round_keys_output_limb_16_col58,
        poseidon_round_keys_output_limb_17_col59,
        poseidon_round_keys_output_limb_18_col60,
        poseidon_round_keys_output_limb_19_col61,
        poseidon_round_keys_output_limb_20_col62,
        poseidon_round_keys_output_limb_21_col63,
        poseidon_round_keys_output_limb_22_col64,
        poseidon_round_keys_output_limb_23_col65,
        poseidon_round_keys_output_limb_24_col66,
        poseidon_round_keys_output_limb_25_col67,
        poseidon_round_keys_output_limb_26_col68,
        poseidon_round_keys_output_limb_27_col69,
        poseidon_round_keys_output_limb_28_col70,
        poseidon_round_keys_output_limb_29_col71,
        cube_252_output_limb_0_col72,
        cube_252_output_limb_1_col73,
        cube_252_output_limb_2_col74,
        cube_252_output_limb_3_col75,
        cube_252_output_limb_4_col76,
        cube_252_output_limb_5_col77,
        cube_252_output_limb_6_col78,
        cube_252_output_limb_7_col79,
        cube_252_output_limb_8_col80,
        cube_252_output_limb_9_col81,
        combination_limb_0_col82,
        combination_limb_1_col83,
        combination_limb_2_col84,
        combination_limb_3_col85,
        combination_limb_4_col86,
        combination_limb_5_col87,
        combination_limb_6_col88,
        combination_limb_7_col89,
        combination_limb_8_col90,
        combination_limb_9_col91,
        p_coef_col92,
        combination_limb_0_col93,
        combination_limb_1_col94,
        combination_limb_2_col95,
        combination_limb_3_col96,
        combination_limb_4_col97,
        combination_limb_5_col98,
        combination_limb_6_col99,
        combination_limb_7_col100,
        combination_limb_8_col101,
        combination_limb_9_col102,
        p_coef_col103,
        cube_252_output_limb_0_col104,
        cube_252_output_limb_1_col105,
        cube_252_output_limb_2_col106,
        cube_252_output_limb_3_col107,
        cube_252_output_limb_4_col108,
        cube_252_output_limb_5_col109,
        cube_252_output_limb_6_col110,
        cube_252_output_limb_7_col111,
        cube_252_output_limb_8_col112,
        cube_252_output_limb_9_col113,
        combination_limb_0_col114,
        combination_limb_1_col115,
        combination_limb_2_col116,
        combination_limb_3_col117,
        combination_limb_4_col118,
        combination_limb_5_col119,
        combination_limb_6_col120,
        combination_limb_7_col121,
        combination_limb_8_col122,
        combination_limb_9_col123,
        p_coef_col124,
        combination_limb_0_col125,
        combination_limb_1_col126,
        combination_limb_2_col127,
        combination_limb_3_col128,
        combination_limb_4_col129,
        combination_limb_5_col130,
        combination_limb_6_col131,
        combination_limb_7_col132,
        combination_limb_8_col133,
        combination_limb_9_col134,
        p_coef_col135,
        cube_252_output_limb_0_col136,
        cube_252_output_limb_1_col137,
        cube_252_output_limb_2_col138,
        cube_252_output_limb_3_col139,
        cube_252_output_limb_4_col140,
        cube_252_output_limb_5_col141,
        cube_252_output_limb_6_col142,
        cube_252_output_limb_7_col143,
        cube_252_output_limb_8_col144,
        cube_252_output_limb_9_col145,
        combination_limb_0_col146,
        combination_limb_1_col147,
        combination_limb_2_col148,
        combination_limb_3_col149,
        combination_limb_4_col150,
        combination_limb_5_col151,
        combination_limb_6_col152,
        combination_limb_7_col153,
        combination_limb_8_col154,
        combination_limb_9_col155,
        p_coef_col156,
        combination_limb_0_col157,
        combination_limb_1_col158,
        combination_limb_2_col159,
        combination_limb_3_col160,
        combination_limb_4_col161,
        combination_limb_5_col162,
        combination_limb_6_col163,
        combination_limb_7_col164,
        combination_limb_8_col165,
        combination_limb_9_col166,
        p_coef_col167,
        enabler,
    ] = input.try_into().unwrap();
    let enabler_constraint_value = eval!(context, ((enabler) * (enabler)) - (enabler));
    acc.add_constraint(context, enabler_constraint_value);

    // Use PoseidonRoundKeys.
    let tuple_0 = &[
        eval!(context, 1024310512),
        eval!(context, input_limb_1_col1),
        eval!(context, poseidon_round_keys_output_limb_0_col42),
        eval!(context, poseidon_round_keys_output_limb_1_col43),
        eval!(context, poseidon_round_keys_output_limb_2_col44),
        eval!(context, poseidon_round_keys_output_limb_3_col45),
        eval!(context, poseidon_round_keys_output_limb_4_col46),
        eval!(context, poseidon_round_keys_output_limb_5_col47),
        eval!(context, poseidon_round_keys_output_limb_6_col48),
        eval!(context, poseidon_round_keys_output_limb_7_col49),
        eval!(context, poseidon_round_keys_output_limb_8_col50),
        eval!(context, poseidon_round_keys_output_limb_9_col51),
        eval!(context, poseidon_round_keys_output_limb_10_col52),
        eval!(context, poseidon_round_keys_output_limb_11_col53),
        eval!(context, poseidon_round_keys_output_limb_12_col54),
        eval!(context, poseidon_round_keys_output_limb_13_col55),
        eval!(context, poseidon_round_keys_output_limb_14_col56),
        eval!(context, poseidon_round_keys_output_limb_15_col57),
        eval!(context, poseidon_round_keys_output_limb_16_col58),
        eval!(context, poseidon_round_keys_output_limb_17_col59),
        eval!(context, poseidon_round_keys_output_limb_18_col60),
        eval!(context, poseidon_round_keys_output_limb_19_col61),
        eval!(context, poseidon_round_keys_output_limb_20_col62),
        eval!(context, poseidon_round_keys_output_limb_21_col63),
        eval!(context, poseidon_round_keys_output_limb_22_col64),
        eval!(context, poseidon_round_keys_output_limb_23_col65),
        eval!(context, poseidon_round_keys_output_limb_24_col66),
        eval!(context, poseidon_round_keys_output_limb_25_col67),
        eval!(context, poseidon_round_keys_output_limb_26_col68),
        eval!(context, poseidon_round_keys_output_limb_27_col69),
        eval!(context, poseidon_round_keys_output_limb_28_col70),
        eval!(context, poseidon_round_keys_output_limb_29_col71),
    ];
    let numerator_0 = eval!(context, 1);
    acc.add_to_relation(context, numerator_0, tuple_0);

    poseidon_partial_round::accumulate_constraints(
        &[
            eval!(context, input_limb_2_col2),
            eval!(context, input_limb_3_col3),
            eval!(context, input_limb_4_col4),
            eval!(context, input_limb_5_col5),
            eval!(context, input_limb_6_col6),
            eval!(context, input_limb_7_col7),
            eval!(context, input_limb_8_col8),
            eval!(context, input_limb_9_col9),
            eval!(context, input_limb_10_col10),
            eval!(context, input_limb_11_col11),
            eval!(context, input_limb_12_col12),
            eval!(context, input_limb_13_col13),
            eval!(context, input_limb_14_col14),
            eval!(context, input_limb_15_col15),
            eval!(context, input_limb_16_col16),
            eval!(context, input_limb_17_col17),
            eval!(context, input_limb_18_col18),
            eval!(context, input_limb_19_col19),
            eval!(context, input_limb_20_col20),
            eval!(context, input_limb_21_col21),
            eval!(context, input_limb_22_col22),
            eval!(context, input_limb_23_col23),
            eval!(context, input_limb_24_col24),
            eval!(context, input_limb_25_col25),
            eval!(context, input_limb_26_col26),
            eval!(context, input_limb_27_col27),
            eval!(context, input_limb_28_col28),
            eval!(context, input_limb_29_col29),
            eval!(context, input_limb_30_col30),
            eval!(context, input_limb_31_col31),
            eval!(context, input_limb_32_col32),
            eval!(context, input_limb_33_col33),
            eval!(context, input_limb_34_col34),
            eval!(context, input_limb_35_col35),
            eval!(context, input_limb_36_col36),
            eval!(context, input_limb_37_col37),
            eval!(context, input_limb_38_col38),
            eval!(context, input_limb_39_col39),
            eval!(context, input_limb_40_col40),
            eval!(context, input_limb_41_col41),
            eval!(context, poseidon_round_keys_output_limb_0_col42),
            eval!(context, poseidon_round_keys_output_limb_1_col43),
            eval!(context, poseidon_round_keys_output_limb_2_col44),
            eval!(context, poseidon_round_keys_output_limb_3_col45),
            eval!(context, poseidon_round_keys_output_limb_4_col46),
            eval!(context, poseidon_round_keys_output_limb_5_col47),
            eval!(context, poseidon_round_keys_output_limb_6_col48),
            eval!(context, poseidon_round_keys_output_limb_7_col49),
            eval!(context, poseidon_round_keys_output_limb_8_col50),
            eval!(context, poseidon_round_keys_output_limb_9_col51),
            eval!(context, cube_252_output_limb_0_col72),
            eval!(context, cube_252_output_limb_1_col73),
            eval!(context, cube_252_output_limb_2_col74),
            eval!(context, cube_252_output_limb_3_col75),
            eval!(context, cube_252_output_limb_4_col76),
            eval!(context, cube_252_output_limb_5_col77),
            eval!(context, cube_252_output_limb_6_col78),
            eval!(context, cube_252_output_limb_7_col79),
            eval!(context, cube_252_output_limb_8_col80),
            eval!(context, cube_252_output_limb_9_col81),
            eval!(context, combination_limb_0_col82),
            eval!(context, combination_limb_1_col83),
            eval!(context, combination_limb_2_col84),
            eval!(context, combination_limb_3_col85),
            eval!(context, combination_limb_4_col86),
            eval!(context, combination_limb_5_col87),
            eval!(context, combination_limb_6_col88),
            eval!(context, combination_limb_7_col89),
            eval!(context, combination_limb_8_col90),
            eval!(context, combination_limb_9_col91),
            eval!(context, p_coef_col92),
            eval!(context, combination_limb_0_col93),
            eval!(context, combination_limb_1_col94),
            eval!(context, combination_limb_2_col95),
            eval!(context, combination_limb_3_col96),
            eval!(context, combination_limb_4_col97),
            eval!(context, combination_limb_5_col98),
            eval!(context, combination_limb_6_col99),
            eval!(context, combination_limb_7_col100),
            eval!(context, combination_limb_8_col101),
            eval!(context, combination_limb_9_col102),
            eval!(context, p_coef_col103),
        ],
        context,
        component_data,
        acc,
    );

    poseidon_partial_round::accumulate_constraints(
        &[
            eval!(context, input_limb_22_col22),
            eval!(context, input_limb_23_col23),
            eval!(context, input_limb_24_col24),
            eval!(context, input_limb_25_col25),
            eval!(context, input_limb_26_col26),
            eval!(context, input_limb_27_col27),
            eval!(context, input_limb_28_col28),
            eval!(context, input_limb_29_col29),
            eval!(context, input_limb_30_col30),
            eval!(context, input_limb_31_col31),
            eval!(context, input_limb_32_col32),
            eval!(context, input_limb_33_col33),
            eval!(context, input_limb_34_col34),
            eval!(context, input_limb_35_col35),
            eval!(context, input_limb_36_col36),
            eval!(context, input_limb_37_col37),
            eval!(context, input_limb_38_col38),
            eval!(context, input_limb_39_col39),
            eval!(context, input_limb_40_col40),
            eval!(context, input_limb_41_col41),
            eval!(context, cube_252_output_limb_0_col72),
            eval!(context, cube_252_output_limb_1_col73),
            eval!(context, cube_252_output_limb_2_col74),
            eval!(context, cube_252_output_limb_3_col75),
            eval!(context, cube_252_output_limb_4_col76),
            eval!(context, cube_252_output_limb_5_col77),
            eval!(context, cube_252_output_limb_6_col78),
            eval!(context, cube_252_output_limb_7_col79),
            eval!(context, cube_252_output_limb_8_col80),
            eval!(context, cube_252_output_limb_9_col81),
            eval!(context, combination_limb_0_col93),
            eval!(context, combination_limb_1_col94),
            eval!(context, combination_limb_2_col95),
            eval!(context, combination_limb_3_col96),
            eval!(context, combination_limb_4_col97),
            eval!(context, combination_limb_5_col98),
            eval!(context, combination_limb_6_col99),
            eval!(context, combination_limb_7_col100),
            eval!(context, combination_limb_8_col101),
            eval!(context, combination_limb_9_col102),
            eval!(context, poseidon_round_keys_output_limb_10_col52),
            eval!(context, poseidon_round_keys_output_limb_11_col53),
            eval!(context, poseidon_round_keys_output_limb_12_col54),
            eval!(context, poseidon_round_keys_output_limb_13_col55),
            eval!(context, poseidon_round_keys_output_limb_14_col56),
            eval!(context, poseidon_round_keys_output_limb_15_col57),
            eval!(context, poseidon_round_keys_output_limb_16_col58),
            eval!(context, poseidon_round_keys_output_limb_17_col59),
            eval!(context, poseidon_round_keys_output_limb_18_col60),
            eval!(context, poseidon_round_keys_output_limb_19_col61),
            eval!(context, cube_252_output_limb_0_col104),
            eval!(context, cube_252_output_limb_1_col105),
            eval!(context, cube_252_output_limb_2_col106),
            eval!(context, cube_252_output_limb_3_col107),
            eval!(context, cube_252_output_limb_4_col108),
            eval!(context, cube_252_output_limb_5_col109),
            eval!(context, cube_252_output_limb_6_col110),
            eval!(context, cube_252_output_limb_7_col111),
            eval!(context, cube_252_output_limb_8_col112),
            eval!(context, cube_252_output_limb_9_col113),
            eval!(context, combination_limb_0_col114),
            eval!(context, combination_limb_1_col115),
            eval!(context, combination_limb_2_col116),
            eval!(context, combination_limb_3_col117),
            eval!(context, combination_limb_4_col118),
            eval!(context, combination_limb_5_col119),
            eval!(context, combination_limb_6_col120),
            eval!(context, combination_limb_7_col121),
            eval!(context, combination_limb_8_col122),
            eval!(context, combination_limb_9_col123),
            eval!(context, p_coef_col124),
            eval!(context, combination_limb_0_col125),
            eval!(context, combination_limb_1_col126),
            eval!(context, combination_limb_2_col127),
            eval!(context, combination_limb_3_col128),
            eval!(context, combination_limb_4_col129),
            eval!(context, combination_limb_5_col130),
            eval!(context, combination_limb_6_col131),
            eval!(context, combination_limb_7_col132),
            eval!(context, combination_limb_8_col133),
            eval!(context, combination_limb_9_col134),
            eval!(context, p_coef_col135),
        ],
        context,
        component_data,
        acc,
    );

    poseidon_partial_round::accumulate_constraints(
        &[
            eval!(context, cube_252_output_limb_0_col72),
            eval!(context, cube_252_output_limb_1_col73),
            eval!(context, cube_252_output_limb_2_col74),
            eval!(context, cube_252_output_limb_3_col75),
            eval!(context, cube_252_output_limb_4_col76),
            eval!(context, cube_252_output_limb_5_col77),
            eval!(context, cube_252_output_limb_6_col78),
            eval!(context, cube_252_output_limb_7_col79),
            eval!(context, cube_252_output_limb_8_col80),
            eval!(context, cube_252_output_limb_9_col81),
            eval!(context, combination_limb_0_col93),
            eval!(context, combination_limb_1_col94),
            eval!(context, combination_limb_2_col95),
            eval!(context, combination_limb_3_col96),
            eval!(context, combination_limb_4_col97),
            eval!(context, combination_limb_5_col98),
            eval!(context, combination_limb_6_col99),
            eval!(context, combination_limb_7_col100),
            eval!(context, combination_limb_8_col101),
            eval!(context, combination_limb_9_col102),
            eval!(context, cube_252_output_limb_0_col104),
            eval!(context, cube_252_output_limb_1_col105),
            eval!(context, cube_252_output_limb_2_col106),
            eval!(context, cube_252_output_limb_3_col107),
            eval!(context, cube_252_output_limb_4_col108),
            eval!(context, cube_252_output_limb_5_col109),
            eval!(context, cube_252_output_limb_6_col110),
            eval!(context, cube_252_output_limb_7_col111),
            eval!(context, cube_252_output_limb_8_col112),
            eval!(context, cube_252_output_limb_9_col113),
            eval!(context, combination_limb_0_col125),
            eval!(context, combination_limb_1_col126),
            eval!(context, combination_limb_2_col127),
            eval!(context, combination_limb_3_col128),
            eval!(context, combination_limb_4_col129),
            eval!(context, combination_limb_5_col130),
            eval!(context, combination_limb_6_col131),
            eval!(context, combination_limb_7_col132),
            eval!(context, combination_limb_8_col133),
            eval!(context, combination_limb_9_col134),
            eval!(context, poseidon_round_keys_output_limb_20_col62),
            eval!(context, poseidon_round_keys_output_limb_21_col63),
            eval!(context, poseidon_round_keys_output_limb_22_col64),
            eval!(context, poseidon_round_keys_output_limb_23_col65),
            eval!(context, poseidon_round_keys_output_limb_24_col66),
            eval!(context, poseidon_round_keys_output_limb_25_col67),
            eval!(context, poseidon_round_keys_output_limb_26_col68),
            eval!(context, poseidon_round_keys_output_limb_27_col69),
            eval!(context, poseidon_round_keys_output_limb_28_col70),
            eval!(context, poseidon_round_keys_output_limb_29_col71),
            eval!(context, cube_252_output_limb_0_col136),
            eval!(context, cube_252_output_limb_1_col137),
            eval!(context, cube_252_output_limb_2_col138),
            eval!(context, cube_252_output_limb_3_col139),
            eval!(context, cube_252_output_limb_4_col140),
            eval!(context, cube_252_output_limb_5_col141),
            eval!(context, cube_252_output_limb_6_col142),
            eval!(context, cube_252_output_limb_7_col143),
            eval!(context, cube_252_output_limb_8_col144),
            eval!(context, cube_252_output_limb_9_col145),
            eval!(context, combination_limb_0_col146),
            eval!(context, combination_limb_1_col147),
            eval!(context, combination_limb_2_col148),
            eval!(context, combination_limb_3_col149),
            eval!(context, combination_limb_4_col150),
            eval!(context, combination_limb_5_col151),
            eval!(context, combination_limb_6_col152),
            eval!(context, combination_limb_7_col153),
            eval!(context, combination_limb_8_col154),
            eval!(context, combination_limb_9_col155),
            eval!(context, p_coef_col156),
            eval!(context, combination_limb_0_col157),
            eval!(context, combination_limb_1_col158),
            eval!(context, combination_limb_2_col159),
            eval!(context, combination_limb_3_col160),
            eval!(context, combination_limb_4_col161),
            eval!(context, combination_limb_5_col162),
            eval!(context, combination_limb_6_col163),
            eval!(context, combination_limb_7_col164),
            eval!(context, combination_limb_8_col165),
            eval!(context, combination_limb_9_col166),
            eval!(context, p_coef_col167),
        ],
        context,
        component_data,
        acc,
    );

    // Use Poseidon3PartialRoundsChain.
    let tuple_4 = &[
        eval!(context, 1343313504),
        eval!(context, input_limb_0_col0),
        eval!(context, input_limb_1_col1),
        eval!(context, input_limb_2_col2),
        eval!(context, input_limb_3_col3),
        eval!(context, input_limb_4_col4),
        eval!(context, input_limb_5_col5),
        eval!(context, input_limb_6_col6),
        eval!(context, input_limb_7_col7),
        eval!(context, input_limb_8_col8),
        eval!(context, input_limb_9_col9),
        eval!(context, input_limb_10_col10),
        eval!(context, input_limb_11_col11),
        eval!(context, input_limb_12_col12),
        eval!(context, input_limb_13_col13),
        eval!(context, input_limb_14_col14),
        eval!(context, input_limb_15_col15),
        eval!(context, input_limb_16_col16),
        eval!(context, input_limb_17_col17),
        eval!(context, input_limb_18_col18),
        eval!(context, input_limb_19_col19),
        eval!(context, input_limb_20_col20),
        eval!(context, input_limb_21_col21),
        eval!(context, input_limb_22_col22),
        eval!(context, input_limb_23_col23),
        eval!(context, input_limb_24_col24),
        eval!(context, input_limb_25_col25),
        eval!(context, input_limb_26_col26),
        eval!(context, input_limb_27_col27),
        eval!(context, input_limb_28_col28),
        eval!(context, input_limb_29_col29),
        eval!(context, input_limb_30_col30),
        eval!(context, input_limb_31_col31),
        eval!(context, input_limb_32_col32),
        eval!(context, input_limb_33_col33),
        eval!(context, input_limb_34_col34),
        eval!(context, input_limb_35_col35),
        eval!(context, input_limb_36_col36),
        eval!(context, input_limb_37_col37),
        eval!(context, input_limb_38_col38),
        eval!(context, input_limb_39_col39),
        eval!(context, input_limb_40_col40),
        eval!(context, input_limb_41_col41),
    ];
    let numerator_4 = eval!(context, enabler);
    acc.add_to_relation(context, numerator_4, tuple_4);

    // Yield Poseidon3PartialRoundsChain.
    let tuple_5 = &[
        eval!(context, 1343313504),
        eval!(context, input_limb_0_col0),
        eval!(context, (input_limb_1_col1) + (1)),
        eval!(context, cube_252_output_limb_0_col104),
        eval!(context, cube_252_output_limb_1_col105),
        eval!(context, cube_252_output_limb_2_col106),
        eval!(context, cube_252_output_limb_3_col107),
        eval!(context, cube_252_output_limb_4_col108),
        eval!(context, cube_252_output_limb_5_col109),
        eval!(context, cube_252_output_limb_6_col110),
        eval!(context, cube_252_output_limb_7_col111),
        eval!(context, cube_252_output_limb_8_col112),
        eval!(context, cube_252_output_limb_9_col113),
        eval!(context, combination_limb_0_col125),
        eval!(context, combination_limb_1_col126),
        eval!(context, combination_limb_2_col127),
        eval!(context, combination_limb_3_col128),
        eval!(context, combination_limb_4_col129),
        eval!(context, combination_limb_5_col130),
        eval!(context, combination_limb_6_col131),
        eval!(context, combination_limb_7_col132),
        eval!(context, combination_limb_8_col133),
        eval!(context, combination_limb_9_col134),
        eval!(context, cube_252_output_limb_0_col136),
        eval!(context, cube_252_output_limb_1_col137),
        eval!(context, cube_252_output_limb_2_col138),
        eval!(context, cube_252_output_limb_3_col139),
        eval!(context, cube_252_output_limb_4_col140),
        eval!(context, cube_252_output_limb_5_col141),
        eval!(context, cube_252_output_limb_6_col142),
        eval!(context, cube_252_output_limb_7_col143),
        eval!(context, cube_252_output_limb_8_col144),
        eval!(context, cube_252_output_limb_9_col145),
        eval!(context, combination_limb_0_col157),
        eval!(context, combination_limb_1_col158),
        eval!(context, combination_limb_2_col159),
        eval!(context, combination_limb_3_col160),
        eval!(context, combination_limb_4_col161),
        eval!(context, combination_limb_5_col162),
        eval!(context, combination_limb_6_col163),
        eval!(context, combination_limb_7_col164),
        eval!(context, combination_limb_8_col165),
        eval!(context, combination_limb_9_col166),
    ];
    let numerator_5 = eval!(context, -(enabler));
    acc.add_to_relation(context, numerator_5, tuple_5);
}

pub struct Component {}
impl<Value: IValue> CircuitEval<Value> for Component {
    fn evaluate(
        &self,
        context: &mut Context<Value>,
        component_data: &ComponentData<'_>,
        acc: &mut CompositionConstraintAccumulator,
    ) {
        accumulate_constraints(component_data.trace_columns, context, component_data, acc);
    }

    fn trace_columns(&self) -> usize {
        N_TRACE_COLUMNS
    }

    fn interaction_columns(&self) -> usize {
        N_INTERACTION_COLUMNS
    }

    fn relation_uses_per_row(&self) -> &[RelationUse] {
        &RELATION_USES_PER_ROW
    }
}
