// This file was created by the AIR team.

use crate::cairo_air::components::prelude::*;

pub const N_TRACE_COLUMNS: usize = 342;
pub const N_INTERACTION_COLUMNS: usize = 56;

pub const RELATION_USES_PER_ROW: [RelationUse; 8] = [
    RelationUse { relation_id: "Cube252", uses: 2 },
    RelationUse { relation_id: "MemoryIdToBig", uses: 6 },
    RelationUse { relation_id: "Poseidon3PartialRoundsChain", uses: 1 },
    RelationUse { relation_id: "PoseidonFullRoundChain", uses: 2 },
    RelationUse { relation_id: "RangeCheck252Width27", uses: 2 },
    RelationUse { relation_id: "RangeCheck_3_3_3_3_3", uses: 2 },
    RelationUse { relation_id: "RangeCheck_4_4", uses: 3 },
    RelationUse { relation_id: "RangeCheck_4_4_4_4", uses: 6 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints(
    input: &[Var],
    context: &mut Context<impl IValue>,
    component_data: &ComponentData<'_>,
    acc: &mut CompositionConstraintAccumulator,
) {
    let [
        input_limb_0_col0,
        input_limb_1_col1,
        input_limb_2_col2,
        input_limb_3_col3,
        input_limb_4_col4,
        input_limb_5_col5,
        value_limb_0_col6,
        value_limb_1_col7,
        value_limb_2_col8,
        value_limb_3_col9,
        value_limb_4_col10,
        value_limb_5_col11,
        value_limb_6_col12,
        value_limb_7_col13,
        value_limb_8_col14,
        value_limb_9_col15,
        value_limb_10_col16,
        value_limb_11_col17,
        value_limb_12_col18,
        value_limb_13_col19,
        value_limb_14_col20,
        value_limb_15_col21,
        value_limb_16_col22,
        value_limb_17_col23,
        value_limb_18_col24,
        value_limb_19_col25,
        value_limb_20_col26,
        value_limb_21_col27,
        value_limb_22_col28,
        value_limb_23_col29,
        value_limb_24_col30,
        value_limb_25_col31,
        value_limb_26_col32,
        value_limb_27_col33,
        value_limb_0_col34,
        value_limb_1_col35,
        value_limb_2_col36,
        value_limb_3_col37,
        value_limb_4_col38,
        value_limb_5_col39,
        value_limb_6_col40,
        value_limb_7_col41,
        value_limb_8_col42,
        value_limb_9_col43,
        value_limb_10_col44,
        value_limb_11_col45,
        value_limb_12_col46,
        value_limb_13_col47,
        value_limb_14_col48,
        value_limb_15_col49,
        value_limb_16_col50,
        value_limb_17_col51,
        value_limb_18_col52,
        value_limb_19_col53,
        value_limb_20_col54,
        value_limb_21_col55,
        value_limb_22_col56,
        value_limb_23_col57,
        value_limb_24_col58,
        value_limb_25_col59,
        value_limb_26_col60,
        value_limb_27_col61,
        value_limb_0_col62,
        value_limb_1_col63,
        value_limb_2_col64,
        value_limb_3_col65,
        value_limb_4_col66,
        value_limb_5_col67,
        value_limb_6_col68,
        value_limb_7_col69,
        value_limb_8_col70,
        value_limb_9_col71,
        value_limb_10_col72,
        value_limb_11_col73,
        value_limb_12_col74,
        value_limb_13_col75,
        value_limb_14_col76,
        value_limb_15_col77,
        value_limb_16_col78,
        value_limb_17_col79,
        value_limb_18_col80,
        value_limb_19_col81,
        value_limb_20_col82,
        value_limb_21_col83,
        value_limb_22_col84,
        value_limb_23_col85,
        value_limb_24_col86,
        value_limb_25_col87,
        value_limb_26_col88,
        value_limb_27_col89,
        combination_limb_0_col90,
        combination_limb_1_col91,
        combination_limb_2_col92,
        combination_limb_3_col93,
        combination_limb_4_col94,
        combination_limb_5_col95,
        combination_limb_6_col96,
        combination_limb_7_col97,
        combination_limb_8_col98,
        combination_limb_9_col99,
        p_coef_col100,
        combination_limb_0_col101,
        combination_limb_1_col102,
        combination_limb_2_col103,
        combination_limb_3_col104,
        combination_limb_4_col105,
        combination_limb_5_col106,
        combination_limb_6_col107,
        combination_limb_7_col108,
        combination_limb_8_col109,
        combination_limb_9_col110,
        p_coef_col111,
        combination_limb_0_col112,
        combination_limb_1_col113,
        combination_limb_2_col114,
        combination_limb_3_col115,
        combination_limb_4_col116,
        combination_limb_5_col117,
        combination_limb_6_col118,
        combination_limb_7_col119,
        combination_limb_8_col120,
        combination_limb_9_col121,
        p_coef_col122,
        poseidon_full_round_chain_output_limb_0_col123,
        poseidon_full_round_chain_output_limb_1_col124,
        poseidon_full_round_chain_output_limb_2_col125,
        poseidon_full_round_chain_output_limb_3_col126,
        poseidon_full_round_chain_output_limb_4_col127,
        poseidon_full_round_chain_output_limb_5_col128,
        poseidon_full_round_chain_output_limb_6_col129,
        poseidon_full_round_chain_output_limb_7_col130,
        poseidon_full_round_chain_output_limb_8_col131,
        poseidon_full_round_chain_output_limb_9_col132,
        poseidon_full_round_chain_output_limb_10_col133,
        poseidon_full_round_chain_output_limb_11_col134,
        poseidon_full_round_chain_output_limb_12_col135,
        poseidon_full_round_chain_output_limb_13_col136,
        poseidon_full_round_chain_output_limb_14_col137,
        poseidon_full_round_chain_output_limb_15_col138,
        poseidon_full_round_chain_output_limb_16_col139,
        poseidon_full_round_chain_output_limb_17_col140,
        poseidon_full_round_chain_output_limb_18_col141,
        poseidon_full_round_chain_output_limb_19_col142,
        poseidon_full_round_chain_output_limb_20_col143,
        poseidon_full_round_chain_output_limb_21_col144,
        poseidon_full_round_chain_output_limb_22_col145,
        poseidon_full_round_chain_output_limb_23_col146,
        poseidon_full_round_chain_output_limb_24_col147,
        poseidon_full_round_chain_output_limb_25_col148,
        poseidon_full_round_chain_output_limb_26_col149,
        poseidon_full_round_chain_output_limb_27_col150,
        poseidon_full_round_chain_output_limb_28_col151,
        poseidon_full_round_chain_output_limb_29_col152,
        cube_252_output_limb_0_col153,
        cube_252_output_limb_1_col154,
        cube_252_output_limb_2_col155,
        cube_252_output_limb_3_col156,
        cube_252_output_limb_4_col157,
        cube_252_output_limb_5_col158,
        cube_252_output_limb_6_col159,
        cube_252_output_limb_7_col160,
        cube_252_output_limb_8_col161,
        cube_252_output_limb_9_col162,
        combination_limb_0_col163,
        combination_limb_1_col164,
        combination_limb_2_col165,
        combination_limb_3_col166,
        combination_limb_4_col167,
        combination_limb_5_col168,
        combination_limb_6_col169,
        combination_limb_7_col170,
        combination_limb_8_col171,
        combination_limb_9_col172,
        p_coef_col173,
        cube_252_output_limb_0_col174,
        cube_252_output_limb_1_col175,
        cube_252_output_limb_2_col176,
        cube_252_output_limb_3_col177,
        cube_252_output_limb_4_col178,
        cube_252_output_limb_5_col179,
        cube_252_output_limb_6_col180,
        cube_252_output_limb_7_col181,
        cube_252_output_limb_8_col182,
        cube_252_output_limb_9_col183,
        combination_limb_0_col184,
        combination_limb_1_col185,
        combination_limb_2_col186,
        combination_limb_3_col187,
        combination_limb_4_col188,
        combination_limb_5_col189,
        combination_limb_6_col190,
        combination_limb_7_col191,
        combination_limb_8_col192,
        combination_limb_9_col193,
        p_coef_col194,
        poseidon_3_partial_rounds_chain_output_limb_0_col195,
        poseidon_3_partial_rounds_chain_output_limb_1_col196,
        poseidon_3_partial_rounds_chain_output_limb_2_col197,
        poseidon_3_partial_rounds_chain_output_limb_3_col198,
        poseidon_3_partial_rounds_chain_output_limb_4_col199,
        poseidon_3_partial_rounds_chain_output_limb_5_col200,
        poseidon_3_partial_rounds_chain_output_limb_6_col201,
        poseidon_3_partial_rounds_chain_output_limb_7_col202,
        poseidon_3_partial_rounds_chain_output_limb_8_col203,
        poseidon_3_partial_rounds_chain_output_limb_9_col204,
        poseidon_3_partial_rounds_chain_output_limb_10_col205,
        poseidon_3_partial_rounds_chain_output_limb_11_col206,
        poseidon_3_partial_rounds_chain_output_limb_12_col207,
        poseidon_3_partial_rounds_chain_output_limb_13_col208,
        poseidon_3_partial_rounds_chain_output_limb_14_col209,
        poseidon_3_partial_rounds_chain_output_limb_15_col210,
        poseidon_3_partial_rounds_chain_output_limb_16_col211,
        poseidon_3_partial_rounds_chain_output_limb_17_col212,
        poseidon_3_partial_rounds_chain_output_limb_18_col213,
        poseidon_3_partial_rounds_chain_output_limb_19_col214,
        poseidon_3_partial_rounds_chain_output_limb_20_col215,
        poseidon_3_partial_rounds_chain_output_limb_21_col216,
        poseidon_3_partial_rounds_chain_output_limb_22_col217,
        poseidon_3_partial_rounds_chain_output_limb_23_col218,
        poseidon_3_partial_rounds_chain_output_limb_24_col219,
        poseidon_3_partial_rounds_chain_output_limb_25_col220,
        poseidon_3_partial_rounds_chain_output_limb_26_col221,
        poseidon_3_partial_rounds_chain_output_limb_27_col222,
        poseidon_3_partial_rounds_chain_output_limb_28_col223,
        poseidon_3_partial_rounds_chain_output_limb_29_col224,
        poseidon_3_partial_rounds_chain_output_limb_30_col225,
        poseidon_3_partial_rounds_chain_output_limb_31_col226,
        poseidon_3_partial_rounds_chain_output_limb_32_col227,
        poseidon_3_partial_rounds_chain_output_limb_33_col228,
        poseidon_3_partial_rounds_chain_output_limb_34_col229,
        poseidon_3_partial_rounds_chain_output_limb_35_col230,
        poseidon_3_partial_rounds_chain_output_limb_36_col231,
        poseidon_3_partial_rounds_chain_output_limb_37_col232,
        poseidon_3_partial_rounds_chain_output_limb_38_col233,
        poseidon_3_partial_rounds_chain_output_limb_39_col234,
        combination_limb_0_col235,
        combination_limb_1_col236,
        combination_limb_2_col237,
        combination_limb_3_col238,
        combination_limb_4_col239,
        combination_limb_5_col240,
        combination_limb_6_col241,
        combination_limb_7_col242,
        combination_limb_8_col243,
        combination_limb_9_col244,
        p_coef_col245,
        combination_limb_0_col246,
        combination_limb_1_col247,
        combination_limb_2_col248,
        combination_limb_3_col249,
        combination_limb_4_col250,
        combination_limb_5_col251,
        combination_limb_6_col252,
        combination_limb_7_col253,
        combination_limb_8_col254,
        combination_limb_9_col255,
        p_coef_col256,
        poseidon_full_round_chain_output_limb_0_col257,
        poseidon_full_round_chain_output_limb_1_col258,
        poseidon_full_round_chain_output_limb_2_col259,
        poseidon_full_round_chain_output_limb_3_col260,
        poseidon_full_round_chain_output_limb_4_col261,
        poseidon_full_round_chain_output_limb_5_col262,
        poseidon_full_round_chain_output_limb_6_col263,
        poseidon_full_round_chain_output_limb_7_col264,
        poseidon_full_round_chain_output_limb_8_col265,
        poseidon_full_round_chain_output_limb_9_col266,
        poseidon_full_round_chain_output_limb_10_col267,
        poseidon_full_round_chain_output_limb_11_col268,
        poseidon_full_round_chain_output_limb_12_col269,
        poseidon_full_round_chain_output_limb_13_col270,
        poseidon_full_round_chain_output_limb_14_col271,
        poseidon_full_round_chain_output_limb_15_col272,
        poseidon_full_round_chain_output_limb_16_col273,
        poseidon_full_round_chain_output_limb_17_col274,
        poseidon_full_round_chain_output_limb_18_col275,
        poseidon_full_round_chain_output_limb_19_col276,
        poseidon_full_round_chain_output_limb_20_col277,
        poseidon_full_round_chain_output_limb_21_col278,
        poseidon_full_round_chain_output_limb_22_col279,
        poseidon_full_round_chain_output_limb_23_col280,
        poseidon_full_round_chain_output_limb_24_col281,
        poseidon_full_round_chain_output_limb_25_col282,
        poseidon_full_round_chain_output_limb_26_col283,
        poseidon_full_round_chain_output_limb_27_col284,
        poseidon_full_round_chain_output_limb_28_col285,
        poseidon_full_round_chain_output_limb_29_col286,
        unpacked_limb_0_col287,
        unpacked_limb_1_col288,
        unpacked_limb_3_col289,
        unpacked_limb_4_col290,
        unpacked_limb_6_col291,
        unpacked_limb_7_col292,
        unpacked_limb_9_col293,
        unpacked_limb_10_col294,
        unpacked_limb_12_col295,
        unpacked_limb_13_col296,
        unpacked_limb_15_col297,
        unpacked_limb_16_col298,
        unpacked_limb_18_col299,
        unpacked_limb_19_col300,
        unpacked_limb_21_col301,
        unpacked_limb_22_col302,
        unpacked_limb_24_col303,
        unpacked_limb_25_col304,
        unpacked_limb_0_col305,
        unpacked_limb_1_col306,
        unpacked_limb_3_col307,
        unpacked_limb_4_col308,
        unpacked_limb_6_col309,
        unpacked_limb_7_col310,
        unpacked_limb_9_col311,
        unpacked_limb_10_col312,
        unpacked_limb_12_col313,
        unpacked_limb_13_col314,
        unpacked_limb_15_col315,
        unpacked_limb_16_col316,
        unpacked_limb_18_col317,
        unpacked_limb_19_col318,
        unpacked_limb_21_col319,
        unpacked_limb_22_col320,
        unpacked_limb_24_col321,
        unpacked_limb_25_col322,
        unpacked_limb_0_col323,
        unpacked_limb_1_col324,
        unpacked_limb_3_col325,
        unpacked_limb_4_col326,
        unpacked_limb_6_col327,
        unpacked_limb_7_col328,
        unpacked_limb_9_col329,
        unpacked_limb_10_col330,
        unpacked_limb_12_col331,
        unpacked_limb_13_col332,
        unpacked_limb_15_col333,
        unpacked_limb_16_col334,
        unpacked_limb_18_col335,
        unpacked_limb_19_col336,
        unpacked_limb_21_col337,
        unpacked_limb_22_col338,
        unpacked_limb_24_col339,
        unpacked_limb_25_col340,
        multiplicity_0,
    ] = input.try_into().unwrap();
    let seq = seq_of_component_size(context, component_data, acc);

    read_positive_known_id_num_bits_252::accumulate_constraints(
        &[
            eval!(context, input_limb_0_col0),
            eval!(context, value_limb_0_col6),
            eval!(context, value_limb_1_col7),
            eval!(context, value_limb_2_col8),
            eval!(context, value_limb_3_col9),
            eval!(context, value_limb_4_col10),
            eval!(context, value_limb_5_col11),
            eval!(context, value_limb_6_col12),
            eval!(context, value_limb_7_col13),
            eval!(context, value_limb_8_col14),
            eval!(context, value_limb_9_col15),
            eval!(context, value_limb_10_col16),
            eval!(context, value_limb_11_col17),
            eval!(context, value_limb_12_col18),
            eval!(context, value_limb_13_col19),
            eval!(context, value_limb_14_col20),
            eval!(context, value_limb_15_col21),
            eval!(context, value_limb_16_col22),
            eval!(context, value_limb_17_col23),
            eval!(context, value_limb_18_col24),
            eval!(context, value_limb_19_col25),
            eval!(context, value_limb_20_col26),
            eval!(context, value_limb_21_col27),
            eval!(context, value_limb_22_col28),
            eval!(context, value_limb_23_col29),
            eval!(context, value_limb_24_col30),
            eval!(context, value_limb_25_col31),
            eval!(context, value_limb_26_col32),
            eval!(context, value_limb_27_col33),
        ],
        context,
        component_data,
        acc,
    );

    let packed_input_state_0_tmp_34cc4_2_limb_0 = eval!(
        context,
        ((value_limb_0_col6) + ((value_limb_1_col7) * (512))) + ((value_limb_2_col8) * (262144))
    );

    let packed_input_state_0_tmp_34cc4_2_limb_1 = eval!(
        context,
        ((value_limb_3_col9) + ((value_limb_4_col10) * (512))) + ((value_limb_5_col11) * (262144))
    );

    let packed_input_state_0_tmp_34cc4_2_limb_2 = eval!(
        context,
        ((value_limb_6_col12) + ((value_limb_7_col13) * (512))) + ((value_limb_8_col14) * (262144))
    );

    let packed_input_state_0_tmp_34cc4_2_limb_3 = eval!(
        context,
        ((value_limb_9_col15) + ((value_limb_10_col16) * (512)))
            + ((value_limb_11_col17) * (262144))
    );

    let packed_input_state_0_tmp_34cc4_2_limb_4 = eval!(
        context,
        ((value_limb_12_col18) + ((value_limb_13_col19) * (512)))
            + ((value_limb_14_col20) * (262144))
    );

    let packed_input_state_0_tmp_34cc4_2_limb_5 = eval!(
        context,
        ((value_limb_15_col21) + ((value_limb_16_col22) * (512)))
            + ((value_limb_17_col23) * (262144))
    );

    let packed_input_state_0_tmp_34cc4_2_limb_6 = eval!(
        context,
        ((value_limb_18_col24) + ((value_limb_19_col25) * (512)))
            + ((value_limb_20_col26) * (262144))
    );

    let packed_input_state_0_tmp_34cc4_2_limb_7 = eval!(
        context,
        ((value_limb_21_col27) + ((value_limb_22_col28) * (512)))
            + ((value_limb_23_col29) * (262144))
    );

    let packed_input_state_0_tmp_34cc4_2_limb_8 = eval!(
        context,
        ((value_limb_24_col30) + ((value_limb_25_col31) * (512)))
            + ((value_limb_26_col32) * (262144))
    );

    read_positive_known_id_num_bits_252::accumulate_constraints(
        &[
            eval!(context, input_limb_1_col1),
            eval!(context, value_limb_0_col34),
            eval!(context, value_limb_1_col35),
            eval!(context, value_limb_2_col36),
            eval!(context, value_limb_3_col37),
            eval!(context, value_limb_4_col38),
            eval!(context, value_limb_5_col39),
            eval!(context, value_limb_6_col40),
            eval!(context, value_limb_7_col41),
            eval!(context, value_limb_8_col42),
            eval!(context, value_limb_9_col43),
            eval!(context, value_limb_10_col44),
            eval!(context, value_limb_11_col45),
            eval!(context, value_limb_12_col46),
            eval!(context, value_limb_13_col47),
            eval!(context, value_limb_14_col48),
            eval!(context, value_limb_15_col49),
            eval!(context, value_limb_16_col50),
            eval!(context, value_limb_17_col51),
            eval!(context, value_limb_18_col52),
            eval!(context, value_limb_19_col53),
            eval!(context, value_limb_20_col54),
            eval!(context, value_limb_21_col55),
            eval!(context, value_limb_22_col56),
            eval!(context, value_limb_23_col57),
            eval!(context, value_limb_24_col58),
            eval!(context, value_limb_25_col59),
            eval!(context, value_limb_26_col60),
            eval!(context, value_limb_27_col61),
        ],
        context,
        component_data,
        acc,
    );

    let packed_input_state_1_tmp_34cc4_5_limb_0 = eval!(
        context,
        ((value_limb_0_col34) + ((value_limb_1_col35) * (512))) + ((value_limb_2_col36) * (262144))
    );

    let packed_input_state_1_tmp_34cc4_5_limb_1 = eval!(
        context,
        ((value_limb_3_col37) + ((value_limb_4_col38) * (512))) + ((value_limb_5_col39) * (262144))
    );

    let packed_input_state_1_tmp_34cc4_5_limb_2 = eval!(
        context,
        ((value_limb_6_col40) + ((value_limb_7_col41) * (512))) + ((value_limb_8_col42) * (262144))
    );

    let packed_input_state_1_tmp_34cc4_5_limb_3 = eval!(
        context,
        ((value_limb_9_col43) + ((value_limb_10_col44) * (512)))
            + ((value_limb_11_col45) * (262144))
    );

    let packed_input_state_1_tmp_34cc4_5_limb_4 = eval!(
        context,
        ((value_limb_12_col46) + ((value_limb_13_col47) * (512)))
            + ((value_limb_14_col48) * (262144))
    );

    let packed_input_state_1_tmp_34cc4_5_limb_5 = eval!(
        context,
        ((value_limb_15_col49) + ((value_limb_16_col50) * (512)))
            + ((value_limb_17_col51) * (262144))
    );

    let packed_input_state_1_tmp_34cc4_5_limb_6 = eval!(
        context,
        ((value_limb_18_col52) + ((value_limb_19_col53) * (512)))
            + ((value_limb_20_col54) * (262144))
    );

    let packed_input_state_1_tmp_34cc4_5_limb_7 = eval!(
        context,
        ((value_limb_21_col55) + ((value_limb_22_col56) * (512)))
            + ((value_limb_23_col57) * (262144))
    );

    let packed_input_state_1_tmp_34cc4_5_limb_8 = eval!(
        context,
        ((value_limb_24_col58) + ((value_limb_25_col59) * (512)))
            + ((value_limb_26_col60) * (262144))
    );

    read_positive_known_id_num_bits_252::accumulate_constraints(
        &[
            eval!(context, input_limb_2_col2),
            eval!(context, value_limb_0_col62),
            eval!(context, value_limb_1_col63),
            eval!(context, value_limb_2_col64),
            eval!(context, value_limb_3_col65),
            eval!(context, value_limb_4_col66),
            eval!(context, value_limb_5_col67),
            eval!(context, value_limb_6_col68),
            eval!(context, value_limb_7_col69),
            eval!(context, value_limb_8_col70),
            eval!(context, value_limb_9_col71),
            eval!(context, value_limb_10_col72),
            eval!(context, value_limb_11_col73),
            eval!(context, value_limb_12_col74),
            eval!(context, value_limb_13_col75),
            eval!(context, value_limb_14_col76),
            eval!(context, value_limb_15_col77),
            eval!(context, value_limb_16_col78),
            eval!(context, value_limb_17_col79),
            eval!(context, value_limb_18_col80),
            eval!(context, value_limb_19_col81),
            eval!(context, value_limb_20_col82),
            eval!(context, value_limb_21_col83),
            eval!(context, value_limb_22_col84),
            eval!(context, value_limb_23_col85),
            eval!(context, value_limb_24_col86),
            eval!(context, value_limb_25_col87),
            eval!(context, value_limb_26_col88),
            eval!(context, value_limb_27_col89),
        ],
        context,
        component_data,
        acc,
    );

    let packed_input_state_2_tmp_34cc4_8_limb_0 = eval!(
        context,
        ((value_limb_0_col62) + ((value_limb_1_col63) * (512))) + ((value_limb_2_col64) * (262144))
    );

    let packed_input_state_2_tmp_34cc4_8_limb_1 = eval!(
        context,
        ((value_limb_3_col65) + ((value_limb_4_col66) * (512))) + ((value_limb_5_col67) * (262144))
    );

    let packed_input_state_2_tmp_34cc4_8_limb_2 = eval!(
        context,
        ((value_limb_6_col68) + ((value_limb_7_col69) * (512))) + ((value_limb_8_col70) * (262144))
    );

    let packed_input_state_2_tmp_34cc4_8_limb_3 = eval!(
        context,
        ((value_limb_9_col71) + ((value_limb_10_col72) * (512)))
            + ((value_limb_11_col73) * (262144))
    );

    let packed_input_state_2_tmp_34cc4_8_limb_4 = eval!(
        context,
        ((value_limb_12_col74) + ((value_limb_13_col75) * (512)))
            + ((value_limb_14_col76) * (262144))
    );

    let packed_input_state_2_tmp_34cc4_8_limb_5 = eval!(
        context,
        ((value_limb_15_col77) + ((value_limb_16_col78) * (512)))
            + ((value_limb_17_col79) * (262144))
    );

    let packed_input_state_2_tmp_34cc4_8_limb_6 = eval!(
        context,
        ((value_limb_18_col80) + ((value_limb_19_col81) * (512)))
            + ((value_limb_20_col82) * (262144))
    );

    let packed_input_state_2_tmp_34cc4_8_limb_7 = eval!(
        context,
        ((value_limb_21_col83) + ((value_limb_22_col84) * (512)))
            + ((value_limb_23_col85) * (262144))
    );

    let packed_input_state_2_tmp_34cc4_8_limb_8 = eval!(
        context,
        ((value_limb_24_col86) + ((value_limb_25_col87) * (512)))
            + ((value_limb_26_col88) * (262144))
    );

    poseidon_hades_permutation::accumulate_constraints(
        &[
            eval!(context, packed_input_state_0_tmp_34cc4_2_limb_0),
            eval!(context, packed_input_state_0_tmp_34cc4_2_limb_1),
            eval!(context, packed_input_state_0_tmp_34cc4_2_limb_2),
            eval!(context, packed_input_state_0_tmp_34cc4_2_limb_3),
            eval!(context, packed_input_state_0_tmp_34cc4_2_limb_4),
            eval!(context, packed_input_state_0_tmp_34cc4_2_limb_5),
            eval!(context, packed_input_state_0_tmp_34cc4_2_limb_6),
            eval!(context, packed_input_state_0_tmp_34cc4_2_limb_7),
            eval!(context, packed_input_state_0_tmp_34cc4_2_limb_8),
            eval!(context, value_limb_27_col33),
            eval!(context, packed_input_state_1_tmp_34cc4_5_limb_0),
            eval!(context, packed_input_state_1_tmp_34cc4_5_limb_1),
            eval!(context, packed_input_state_1_tmp_34cc4_5_limb_2),
            eval!(context, packed_input_state_1_tmp_34cc4_5_limb_3),
            eval!(context, packed_input_state_1_tmp_34cc4_5_limb_4),
            eval!(context, packed_input_state_1_tmp_34cc4_5_limb_5),
            eval!(context, packed_input_state_1_tmp_34cc4_5_limb_6),
            eval!(context, packed_input_state_1_tmp_34cc4_5_limb_7),
            eval!(context, packed_input_state_1_tmp_34cc4_5_limb_8),
            eval!(context, value_limb_27_col61),
            eval!(context, packed_input_state_2_tmp_34cc4_8_limb_0),
            eval!(context, packed_input_state_2_tmp_34cc4_8_limb_1),
            eval!(context, packed_input_state_2_tmp_34cc4_8_limb_2),
            eval!(context, packed_input_state_2_tmp_34cc4_8_limb_3),
            eval!(context, packed_input_state_2_tmp_34cc4_8_limb_4),
            eval!(context, packed_input_state_2_tmp_34cc4_8_limb_5),
            eval!(context, packed_input_state_2_tmp_34cc4_8_limb_6),
            eval!(context, packed_input_state_2_tmp_34cc4_8_limb_7),
            eval!(context, packed_input_state_2_tmp_34cc4_8_limb_8),
            eval!(context, value_limb_27_col89),
            eval!(context, combination_limb_0_col90),
            eval!(context, combination_limb_1_col91),
            eval!(context, combination_limb_2_col92),
            eval!(context, combination_limb_3_col93),
            eval!(context, combination_limb_4_col94),
            eval!(context, combination_limb_5_col95),
            eval!(context, combination_limb_6_col96),
            eval!(context, combination_limb_7_col97),
            eval!(context, combination_limb_8_col98),
            eval!(context, combination_limb_9_col99),
            eval!(context, p_coef_col100),
            eval!(context, combination_limb_0_col101),
            eval!(context, combination_limb_1_col102),
            eval!(context, combination_limb_2_col103),
            eval!(context, combination_limb_3_col104),
            eval!(context, combination_limb_4_col105),
            eval!(context, combination_limb_5_col106),
            eval!(context, combination_limb_6_col107),
            eval!(context, combination_limb_7_col108),
            eval!(context, combination_limb_8_col109),
            eval!(context, combination_limb_9_col110),
            eval!(context, p_coef_col111),
            eval!(context, combination_limb_0_col112),
            eval!(context, combination_limb_1_col113),
            eval!(context, combination_limb_2_col114),
            eval!(context, combination_limb_3_col115),
            eval!(context, combination_limb_4_col116),
            eval!(context, combination_limb_5_col117),
            eval!(context, combination_limb_6_col118),
            eval!(context, combination_limb_7_col119),
            eval!(context, combination_limb_8_col120),
            eval!(context, combination_limb_9_col121),
            eval!(context, p_coef_col122),
            eval!(context, poseidon_full_round_chain_output_limb_0_col123),
            eval!(context, poseidon_full_round_chain_output_limb_1_col124),
            eval!(context, poseidon_full_round_chain_output_limb_2_col125),
            eval!(context, poseidon_full_round_chain_output_limb_3_col126),
            eval!(context, poseidon_full_round_chain_output_limb_4_col127),
            eval!(context, poseidon_full_round_chain_output_limb_5_col128),
            eval!(context, poseidon_full_round_chain_output_limb_6_col129),
            eval!(context, poseidon_full_round_chain_output_limb_7_col130),
            eval!(context, poseidon_full_round_chain_output_limb_8_col131),
            eval!(context, poseidon_full_round_chain_output_limb_9_col132),
            eval!(context, poseidon_full_round_chain_output_limb_10_col133),
            eval!(context, poseidon_full_round_chain_output_limb_11_col134),
            eval!(context, poseidon_full_round_chain_output_limb_12_col135),
            eval!(context, poseidon_full_round_chain_output_limb_13_col136),
            eval!(context, poseidon_full_round_chain_output_limb_14_col137),
            eval!(context, poseidon_full_round_chain_output_limb_15_col138),
            eval!(context, poseidon_full_round_chain_output_limb_16_col139),
            eval!(context, poseidon_full_round_chain_output_limb_17_col140),
            eval!(context, poseidon_full_round_chain_output_limb_18_col141),
            eval!(context, poseidon_full_round_chain_output_limb_19_col142),
            eval!(context, poseidon_full_round_chain_output_limb_20_col143),
            eval!(context, poseidon_full_round_chain_output_limb_21_col144),
            eval!(context, poseidon_full_round_chain_output_limb_22_col145),
            eval!(context, poseidon_full_round_chain_output_limb_23_col146),
            eval!(context, poseidon_full_round_chain_output_limb_24_col147),
            eval!(context, poseidon_full_round_chain_output_limb_25_col148),
            eval!(context, poseidon_full_round_chain_output_limb_26_col149),
            eval!(context, poseidon_full_round_chain_output_limb_27_col150),
            eval!(context, poseidon_full_round_chain_output_limb_28_col151),
            eval!(context, poseidon_full_round_chain_output_limb_29_col152),
            eval!(context, cube_252_output_limb_0_col153),
            eval!(context, cube_252_output_limb_1_col154),
            eval!(context, cube_252_output_limb_2_col155),
            eval!(context, cube_252_output_limb_3_col156),
            eval!(context, cube_252_output_limb_4_col157),
            eval!(context, cube_252_output_limb_5_col158),
            eval!(context, cube_252_output_limb_6_col159),
            eval!(context, cube_252_output_limb_7_col160),
            eval!(context, cube_252_output_limb_8_col161),
            eval!(context, cube_252_output_limb_9_col162),
            eval!(context, combination_limb_0_col163),
            eval!(context, combination_limb_1_col164),
            eval!(context, combination_limb_2_col165),
            eval!(context, combination_limb_3_col166),
            eval!(context, combination_limb_4_col167),
            eval!(context, combination_limb_5_col168),
            eval!(context, combination_limb_6_col169),
            eval!(context, combination_limb_7_col170),
            eval!(context, combination_limb_8_col171),
            eval!(context, combination_limb_9_col172),
            eval!(context, p_coef_col173),
            eval!(context, cube_252_output_limb_0_col174),
            eval!(context, cube_252_output_limb_1_col175),
            eval!(context, cube_252_output_limb_2_col176),
            eval!(context, cube_252_output_limb_3_col177),
            eval!(context, cube_252_output_limb_4_col178),
            eval!(context, cube_252_output_limb_5_col179),
            eval!(context, cube_252_output_limb_6_col180),
            eval!(context, cube_252_output_limb_7_col181),
            eval!(context, cube_252_output_limb_8_col182),
            eval!(context, cube_252_output_limb_9_col183),
            eval!(context, combination_limb_0_col184),
            eval!(context, combination_limb_1_col185),
            eval!(context, combination_limb_2_col186),
            eval!(context, combination_limb_3_col187),
            eval!(context, combination_limb_4_col188),
            eval!(context, combination_limb_5_col189),
            eval!(context, combination_limb_6_col190),
            eval!(context, combination_limb_7_col191),
            eval!(context, combination_limb_8_col192),
            eval!(context, combination_limb_9_col193),
            eval!(context, p_coef_col194),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_0_col195),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_1_col196),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_2_col197),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_3_col198),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_4_col199),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_5_col200),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_6_col201),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_7_col202),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_8_col203),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_9_col204),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_10_col205),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_11_col206),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_12_col207),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_13_col208),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_14_col209),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_15_col210),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_16_col211),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_17_col212),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_18_col213),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_19_col214),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_20_col215),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_21_col216),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_22_col217),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_23_col218),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_24_col219),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_25_col220),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_26_col221),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_27_col222),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_28_col223),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_29_col224),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_30_col225),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_31_col226),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_32_col227),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_33_col228),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_34_col229),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_35_col230),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_36_col231),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_37_col232),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_38_col233),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_39_col234),
            eval!(context, combination_limb_0_col235),
            eval!(context, combination_limb_1_col236),
            eval!(context, combination_limb_2_col237),
            eval!(context, combination_limb_3_col238),
            eval!(context, combination_limb_4_col239),
            eval!(context, combination_limb_5_col240),
            eval!(context, combination_limb_6_col241),
            eval!(context, combination_limb_7_col242),
            eval!(context, combination_limb_8_col243),
            eval!(context, combination_limb_9_col244),
            eval!(context, p_coef_col245),
            eval!(context, combination_limb_0_col246),
            eval!(context, combination_limb_1_col247),
            eval!(context, combination_limb_2_col248),
            eval!(context, combination_limb_3_col249),
            eval!(context, combination_limb_4_col250),
            eval!(context, combination_limb_5_col251),
            eval!(context, combination_limb_6_col252),
            eval!(context, combination_limb_7_col253),
            eval!(context, combination_limb_8_col254),
            eval!(context, combination_limb_9_col255),
            eval!(context, p_coef_col256),
            eval!(context, poseidon_full_round_chain_output_limb_0_col257),
            eval!(context, poseidon_full_round_chain_output_limb_1_col258),
            eval!(context, poseidon_full_round_chain_output_limb_2_col259),
            eval!(context, poseidon_full_round_chain_output_limb_3_col260),
            eval!(context, poseidon_full_round_chain_output_limb_4_col261),
            eval!(context, poseidon_full_round_chain_output_limb_5_col262),
            eval!(context, poseidon_full_round_chain_output_limb_6_col263),
            eval!(context, poseidon_full_round_chain_output_limb_7_col264),
            eval!(context, poseidon_full_round_chain_output_limb_8_col265),
            eval!(context, poseidon_full_round_chain_output_limb_9_col266),
            eval!(context, poseidon_full_round_chain_output_limb_10_col267),
            eval!(context, poseidon_full_round_chain_output_limb_11_col268),
            eval!(context, poseidon_full_round_chain_output_limb_12_col269),
            eval!(context, poseidon_full_round_chain_output_limb_13_col270),
            eval!(context, poseidon_full_round_chain_output_limb_14_col271),
            eval!(context, poseidon_full_round_chain_output_limb_15_col272),
            eval!(context, poseidon_full_round_chain_output_limb_16_col273),
            eval!(context, poseidon_full_round_chain_output_limb_17_col274),
            eval!(context, poseidon_full_round_chain_output_limb_18_col275),
            eval!(context, poseidon_full_round_chain_output_limb_19_col276),
            eval!(context, poseidon_full_round_chain_output_limb_20_col277),
            eval!(context, poseidon_full_round_chain_output_limb_21_col278),
            eval!(context, poseidon_full_round_chain_output_limb_22_col279),
            eval!(context, poseidon_full_round_chain_output_limb_23_col280),
            eval!(context, poseidon_full_round_chain_output_limb_24_col281),
            eval!(context, poseidon_full_round_chain_output_limb_25_col282),
            eval!(context, poseidon_full_round_chain_output_limb_26_col283),
            eval!(context, poseidon_full_round_chain_output_limb_27_col284),
            eval!(context, poseidon_full_round_chain_output_limb_28_col285),
            eval!(context, poseidon_full_round_chain_output_limb_29_col286),
        ],
        context,
        component_data,
        acc,
    );

    let [
        felt_252_unpack_from_27_output_tmp_34cc4_162_limb_2,
        felt_252_unpack_from_27_output_tmp_34cc4_162_limb_5,
        felt_252_unpack_from_27_output_tmp_34cc4_162_limb_8,
        felt_252_unpack_from_27_output_tmp_34cc4_162_limb_11,
        felt_252_unpack_from_27_output_tmp_34cc4_162_limb_14,
        felt_252_unpack_from_27_output_tmp_34cc4_162_limb_17,
        felt_252_unpack_from_27_output_tmp_34cc4_162_limb_20,
        felt_252_unpack_from_27_output_tmp_34cc4_162_limb_23,
        felt_252_unpack_from_27_output_tmp_34cc4_162_limb_26,
        felt_252_unpack_from_27_output_tmp_34cc4_162_limb_27,
    ] = felt_252_unpack_from_27::accumulate_constraints(
        &[
            eval!(context, poseidon_full_round_chain_output_limb_0_col257),
            eval!(context, poseidon_full_round_chain_output_limb_1_col258),
            eval!(context, poseidon_full_round_chain_output_limb_2_col259),
            eval!(context, poseidon_full_round_chain_output_limb_3_col260),
            eval!(context, poseidon_full_round_chain_output_limb_4_col261),
            eval!(context, poseidon_full_round_chain_output_limb_5_col262),
            eval!(context, poseidon_full_round_chain_output_limb_6_col263),
            eval!(context, poseidon_full_round_chain_output_limb_7_col264),
            eval!(context, poseidon_full_round_chain_output_limb_8_col265),
            eval!(context, poseidon_full_round_chain_output_limb_9_col266),
            eval!(context, unpacked_limb_0_col287),
            eval!(context, unpacked_limb_1_col288),
            eval!(context, unpacked_limb_3_col289),
            eval!(context, unpacked_limb_4_col290),
            eval!(context, unpacked_limb_6_col291),
            eval!(context, unpacked_limb_7_col292),
            eval!(context, unpacked_limb_9_col293),
            eval!(context, unpacked_limb_10_col294),
            eval!(context, unpacked_limb_12_col295),
            eval!(context, unpacked_limb_13_col296),
            eval!(context, unpacked_limb_15_col297),
            eval!(context, unpacked_limb_16_col298),
            eval!(context, unpacked_limb_18_col299),
            eval!(context, unpacked_limb_19_col300),
            eval!(context, unpacked_limb_21_col301),
            eval!(context, unpacked_limb_22_col302),
            eval!(context, unpacked_limb_24_col303),
            eval!(context, unpacked_limb_25_col304),
        ],
        context,
        component_data,
        acc,
    )
    .try_into()
    .unwrap();

    // Use MemoryIdToBig.
    let tuple_32 = &[
        eval!(context, 1662111297),
        eval!(context, input_limb_3_col3),
        eval!(context, unpacked_limb_0_col287),
        eval!(context, unpacked_limb_1_col288),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_162_limb_2),
        eval!(context, unpacked_limb_3_col289),
        eval!(context, unpacked_limb_4_col290),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_162_limb_5),
        eval!(context, unpacked_limb_6_col291),
        eval!(context, unpacked_limb_7_col292),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_162_limb_8),
        eval!(context, unpacked_limb_9_col293),
        eval!(context, unpacked_limb_10_col294),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_162_limb_11),
        eval!(context, unpacked_limb_12_col295),
        eval!(context, unpacked_limb_13_col296),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_162_limb_14),
        eval!(context, unpacked_limb_15_col297),
        eval!(context, unpacked_limb_16_col298),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_162_limb_17),
        eval!(context, unpacked_limb_18_col299),
        eval!(context, unpacked_limb_19_col300),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_162_limb_20),
        eval!(context, unpacked_limb_21_col301),
        eval!(context, unpacked_limb_22_col302),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_162_limb_23),
        eval!(context, unpacked_limb_24_col303),
        eval!(context, unpacked_limb_25_col304),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_162_limb_26),
        eval!(context, poseidon_full_round_chain_output_limb_9_col266),
    ];
    let numerator_32 = eval!(context, 1);
    acc.add_to_relation(context, numerator_32, tuple_32);

    let [
        felt_252_unpack_from_27_output_tmp_34cc4_164_limb_2,
        felt_252_unpack_from_27_output_tmp_34cc4_164_limb_5,
        felt_252_unpack_from_27_output_tmp_34cc4_164_limb_8,
        felt_252_unpack_from_27_output_tmp_34cc4_164_limb_11,
        felt_252_unpack_from_27_output_tmp_34cc4_164_limb_14,
        felt_252_unpack_from_27_output_tmp_34cc4_164_limb_17,
        felt_252_unpack_from_27_output_tmp_34cc4_164_limb_20,
        felt_252_unpack_from_27_output_tmp_34cc4_164_limb_23,
        felt_252_unpack_from_27_output_tmp_34cc4_164_limb_26,
        felt_252_unpack_from_27_output_tmp_34cc4_164_limb_27,
    ] = felt_252_unpack_from_27::accumulate_constraints(
        &[
            eval!(context, poseidon_full_round_chain_output_limb_10_col267),
            eval!(context, poseidon_full_round_chain_output_limb_11_col268),
            eval!(context, poseidon_full_round_chain_output_limb_12_col269),
            eval!(context, poseidon_full_round_chain_output_limb_13_col270),
            eval!(context, poseidon_full_round_chain_output_limb_14_col271),
            eval!(context, poseidon_full_round_chain_output_limb_15_col272),
            eval!(context, poseidon_full_round_chain_output_limb_16_col273),
            eval!(context, poseidon_full_round_chain_output_limb_17_col274),
            eval!(context, poseidon_full_round_chain_output_limb_18_col275),
            eval!(context, poseidon_full_round_chain_output_limb_19_col276),
            eval!(context, unpacked_limb_0_col305),
            eval!(context, unpacked_limb_1_col306),
            eval!(context, unpacked_limb_3_col307),
            eval!(context, unpacked_limb_4_col308),
            eval!(context, unpacked_limb_6_col309),
            eval!(context, unpacked_limb_7_col310),
            eval!(context, unpacked_limb_9_col311),
            eval!(context, unpacked_limb_10_col312),
            eval!(context, unpacked_limb_12_col313),
            eval!(context, unpacked_limb_13_col314),
            eval!(context, unpacked_limb_15_col315),
            eval!(context, unpacked_limb_16_col316),
            eval!(context, unpacked_limb_18_col317),
            eval!(context, unpacked_limb_19_col318),
            eval!(context, unpacked_limb_21_col319),
            eval!(context, unpacked_limb_22_col320),
            eval!(context, unpacked_limb_24_col321),
            eval!(context, unpacked_limb_25_col322),
        ],
        context,
        component_data,
        acc,
    )
    .try_into()
    .unwrap();

    // Use MemoryIdToBig.
    let tuple_34 = &[
        eval!(context, 1662111297),
        eval!(context, input_limb_4_col4),
        eval!(context, unpacked_limb_0_col305),
        eval!(context, unpacked_limb_1_col306),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_164_limb_2),
        eval!(context, unpacked_limb_3_col307),
        eval!(context, unpacked_limb_4_col308),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_164_limb_5),
        eval!(context, unpacked_limb_6_col309),
        eval!(context, unpacked_limb_7_col310),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_164_limb_8),
        eval!(context, unpacked_limb_9_col311),
        eval!(context, unpacked_limb_10_col312),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_164_limb_11),
        eval!(context, unpacked_limb_12_col313),
        eval!(context, unpacked_limb_13_col314),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_164_limb_14),
        eval!(context, unpacked_limb_15_col315),
        eval!(context, unpacked_limb_16_col316),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_164_limb_17),
        eval!(context, unpacked_limb_18_col317),
        eval!(context, unpacked_limb_19_col318),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_164_limb_20),
        eval!(context, unpacked_limb_21_col319),
        eval!(context, unpacked_limb_22_col320),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_164_limb_23),
        eval!(context, unpacked_limb_24_col321),
        eval!(context, unpacked_limb_25_col322),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_164_limb_26),
        eval!(context, poseidon_full_round_chain_output_limb_19_col276),
    ];
    let numerator_34 = eval!(context, 1);
    acc.add_to_relation(context, numerator_34, tuple_34);

    let [
        felt_252_unpack_from_27_output_tmp_34cc4_166_limb_2,
        felt_252_unpack_from_27_output_tmp_34cc4_166_limb_5,
        felt_252_unpack_from_27_output_tmp_34cc4_166_limb_8,
        felt_252_unpack_from_27_output_tmp_34cc4_166_limb_11,
        felt_252_unpack_from_27_output_tmp_34cc4_166_limb_14,
        felt_252_unpack_from_27_output_tmp_34cc4_166_limb_17,
        felt_252_unpack_from_27_output_tmp_34cc4_166_limb_20,
        felt_252_unpack_from_27_output_tmp_34cc4_166_limb_23,
        felt_252_unpack_from_27_output_tmp_34cc4_166_limb_26,
        felt_252_unpack_from_27_output_tmp_34cc4_166_limb_27,
    ] = felt_252_unpack_from_27::accumulate_constraints(
        &[
            eval!(context, poseidon_full_round_chain_output_limb_20_col277),
            eval!(context, poseidon_full_round_chain_output_limb_21_col278),
            eval!(context, poseidon_full_round_chain_output_limb_22_col279),
            eval!(context, poseidon_full_round_chain_output_limb_23_col280),
            eval!(context, poseidon_full_round_chain_output_limb_24_col281),
            eval!(context, poseidon_full_round_chain_output_limb_25_col282),
            eval!(context, poseidon_full_round_chain_output_limb_26_col283),
            eval!(context, poseidon_full_round_chain_output_limb_27_col284),
            eval!(context, poseidon_full_round_chain_output_limb_28_col285),
            eval!(context, poseidon_full_round_chain_output_limb_29_col286),
            eval!(context, unpacked_limb_0_col323),
            eval!(context, unpacked_limb_1_col324),
            eval!(context, unpacked_limb_3_col325),
            eval!(context, unpacked_limb_4_col326),
            eval!(context, unpacked_limb_6_col327),
            eval!(context, unpacked_limb_7_col328),
            eval!(context, unpacked_limb_9_col329),
            eval!(context, unpacked_limb_10_col330),
            eval!(context, unpacked_limb_12_col331),
            eval!(context, unpacked_limb_13_col332),
            eval!(context, unpacked_limb_15_col333),
            eval!(context, unpacked_limb_16_col334),
            eval!(context, unpacked_limb_18_col335),
            eval!(context, unpacked_limb_19_col336),
            eval!(context, unpacked_limb_21_col337),
            eval!(context, unpacked_limb_22_col338),
            eval!(context, unpacked_limb_24_col339),
            eval!(context, unpacked_limb_25_col340),
        ],
        context,
        component_data,
        acc,
    )
    .try_into()
    .unwrap();

    // Use MemoryIdToBig.
    let tuple_36 = &[
        eval!(context, 1662111297),
        eval!(context, input_limb_5_col5),
        eval!(context, unpacked_limb_0_col323),
        eval!(context, unpacked_limb_1_col324),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_166_limb_2),
        eval!(context, unpacked_limb_3_col325),
        eval!(context, unpacked_limb_4_col326),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_166_limb_5),
        eval!(context, unpacked_limb_6_col327),
        eval!(context, unpacked_limb_7_col328),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_166_limb_8),
        eval!(context, unpacked_limb_9_col329),
        eval!(context, unpacked_limb_10_col330),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_166_limb_11),
        eval!(context, unpacked_limb_12_col331),
        eval!(context, unpacked_limb_13_col332),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_166_limb_14),
        eval!(context, unpacked_limb_15_col333),
        eval!(context, unpacked_limb_16_col334),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_166_limb_17),
        eval!(context, unpacked_limb_18_col335),
        eval!(context, unpacked_limb_19_col336),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_166_limb_20),
        eval!(context, unpacked_limb_21_col337),
        eval!(context, unpacked_limb_22_col338),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_166_limb_23),
        eval!(context, unpacked_limb_24_col339),
        eval!(context, unpacked_limb_25_col340),
        eval!(context, felt_252_unpack_from_27_output_tmp_34cc4_166_limb_26),
        eval!(context, poseidon_full_round_chain_output_limb_29_col286),
    ];
    let numerator_36 = eval!(context, 1);
    acc.add_to_relation(context, numerator_36, tuple_36);

    // Yield PoseidonAggregator.
    let tuple_37 = &[
        eval!(context, 1551892206),
        eval!(context, input_limb_0_col0),
        eval!(context, input_limb_1_col1),
        eval!(context, input_limb_2_col2),
        eval!(context, input_limb_3_col3),
        eval!(context, input_limb_4_col4),
        eval!(context, input_limb_5_col5),
    ];
    let numerator_37 = eval!(context, -(multiplicity_0));
    acc.add_to_relation(context, numerator_37, tuple_37);
}

pub struct Component {}
impl<Value: IValue> CircuitEval<Value> for Component {
    fn evaluate(
        &self,
        context: &mut Context<Value>,
        component_data: &ComponentData<'_>,
        acc: &mut CompositionConstraintAccumulator,
    ) {
        accumulate_constraints(component_data.trace_columns, context, component_data, acc);
    }

    fn trace_columns(&self) -> usize {
        N_TRACE_COLUMNS
    }

    fn interaction_columns(&self) -> usize {
        N_INTERACTION_COLUMNS
    }

    fn relation_uses_per_row(&self) -> &[RelationUse] {
        &RELATION_USES_PER_ROW
    }
}
