// This file was created by the AIR team.

use crate::cairo_air::components::prelude::*;

pub const N_TRACE_COLUMNS: usize = 126;
pub const N_INTERACTION_COLUMNS: usize = 24;

pub const RELATION_USES_PER_ROW: [RelationUse; 4] = [
    RelationUse { relation_id: "Cube252", uses: 3 },
    RelationUse { relation_id: "PoseidonFullRoundChain", uses: 1 },
    RelationUse { relation_id: "PoseidonRoundKeys", uses: 1 },
    RelationUse { relation_id: "RangeCheck_3_3_3_3_3", uses: 6 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints(
    input: &[Var],
    context: &mut Context<impl IValue>,
    component_data: &ComponentData<'_>,
    acc: &mut CompositionConstraintAccumulator,
) {
    let [
        input_limb_0_col0,
        input_limb_1_col1,
        input_limb_2_col2,
        input_limb_3_col3,
        input_limb_4_col4,
        input_limb_5_col5,
        input_limb_6_col6,
        input_limb_7_col7,
        input_limb_8_col8,
        input_limb_9_col9,
        input_limb_10_col10,
        input_limb_11_col11,
        input_limb_12_col12,
        input_limb_13_col13,
        input_limb_14_col14,
        input_limb_15_col15,
        input_limb_16_col16,
        input_limb_17_col17,
        input_limb_18_col18,
        input_limb_19_col19,
        input_limb_20_col20,
        input_limb_21_col21,
        input_limb_22_col22,
        input_limb_23_col23,
        input_limb_24_col24,
        input_limb_25_col25,
        input_limb_26_col26,
        input_limb_27_col27,
        input_limb_28_col28,
        input_limb_29_col29,
        input_limb_30_col30,
        input_limb_31_col31,
        cube_252_output_limb_0_col32,
        cube_252_output_limb_1_col33,
        cube_252_output_limb_2_col34,
        cube_252_output_limb_3_col35,
        cube_252_output_limb_4_col36,
        cube_252_output_limb_5_col37,
        cube_252_output_limb_6_col38,
        cube_252_output_limb_7_col39,
        cube_252_output_limb_8_col40,
        cube_252_output_limb_9_col41,
        cube_252_output_limb_0_col42,
        cube_252_output_limb_1_col43,
        cube_252_output_limb_2_col44,
        cube_252_output_limb_3_col45,
        cube_252_output_limb_4_col46,
        cube_252_output_limb_5_col47,
        cube_252_output_limb_6_col48,
        cube_252_output_limb_7_col49,
        cube_252_output_limb_8_col50,
        cube_252_output_limb_9_col51,
        cube_252_output_limb_0_col52,
        cube_252_output_limb_1_col53,
        cube_252_output_limb_2_col54,
        cube_252_output_limb_3_col55,
        cube_252_output_limb_4_col56,
        cube_252_output_limb_5_col57,
        cube_252_output_limb_6_col58,
        cube_252_output_limb_7_col59,
        cube_252_output_limb_8_col60,
        cube_252_output_limb_9_col61,
        poseidon_round_keys_output_limb_0_col62,
        poseidon_round_keys_output_limb_1_col63,
        poseidon_round_keys_output_limb_2_col64,
        poseidon_round_keys_output_limb_3_col65,
        poseidon_round_keys_output_limb_4_col66,
        poseidon_round_keys_output_limb_5_col67,
        poseidon_round_keys_output_limb_6_col68,
        poseidon_round_keys_output_limb_7_col69,
        poseidon_round_keys_output_limb_8_col70,
        poseidon_round_keys_output_limb_9_col71,
        poseidon_round_keys_output_limb_10_col72,
        poseidon_round_keys_output_limb_11_col73,
        poseidon_round_keys_output_limb_12_col74,
        poseidon_round_keys_output_limb_13_col75,
        poseidon_round_keys_output_limb_14_col76,
        poseidon_round_keys_output_limb_15_col77,
        poseidon_round_keys_output_limb_16_col78,
        poseidon_round_keys_output_limb_17_col79,
        poseidon_round_keys_output_limb_18_col80,
        poseidon_round_keys_output_limb_19_col81,
        poseidon_round_keys_output_limb_20_col82,
        poseidon_round_keys_output_limb_21_col83,
        poseidon_round_keys_output_limb_22_col84,
        poseidon_round_keys_output_limb_23_col85,
        poseidon_round_keys_output_limb_24_col86,
        poseidon_round_keys_output_limb_25_col87,
        poseidon_round_keys_output_limb_26_col88,
        poseidon_round_keys_output_limb_27_col89,
        poseidon_round_keys_output_limb_28_col90,
        poseidon_round_keys_output_limb_29_col91,
        combination_limb_0_col92,
        combination_limb_1_col93,
        combination_limb_2_col94,
        combination_limb_3_col95,
        combination_limb_4_col96,
        combination_limb_5_col97,
        combination_limb_6_col98,
        combination_limb_7_col99,
        combination_limb_8_col100,
        combination_limb_9_col101,
        p_coef_col102,
        combination_limb_0_col103,
        combination_limb_1_col104,
        combination_limb_2_col105,
        combination_limb_3_col106,
        combination_limb_4_col107,
        combination_limb_5_col108,
        combination_limb_6_col109,
        combination_limb_7_col110,
        combination_limb_8_col111,
        combination_limb_9_col112,
        p_coef_col113,
        combination_limb_0_col114,
        combination_limb_1_col115,
        combination_limb_2_col116,
        combination_limb_3_col117,
        combination_limb_4_col118,
        combination_limb_5_col119,
        combination_limb_6_col120,
        combination_limb_7_col121,
        combination_limb_8_col122,
        combination_limb_9_col123,
        p_coef_col124,
        enabler,
    ] = input.try_into().unwrap();
    let enabler_constraint_value = eval!(context, ((enabler) * (enabler)) - (enabler));
    acc.add_constraint(context, enabler_constraint_value);

    // Use Cube252.
    let tuple_0 = &[
        eval!(context, 1987997202),
        eval!(context, input_limb_2_col2),
        eval!(context, input_limb_3_col3),
        eval!(context, input_limb_4_col4),
        eval!(context, input_limb_5_col5),
        eval!(context, input_limb_6_col6),
        eval!(context, input_limb_7_col7),
        eval!(context, input_limb_8_col8),
        eval!(context, input_limb_9_col9),
        eval!(context, input_limb_10_col10),
        eval!(context, input_limb_11_col11),
        eval!(context, cube_252_output_limb_0_col32),
        eval!(context, cube_252_output_limb_1_col33),
        eval!(context, cube_252_output_limb_2_col34),
        eval!(context, cube_252_output_limb_3_col35),
        eval!(context, cube_252_output_limb_4_col36),
        eval!(context, cube_252_output_limb_5_col37),
        eval!(context, cube_252_output_limb_6_col38),
        eval!(context, cube_252_output_limb_7_col39),
        eval!(context, cube_252_output_limb_8_col40),
        eval!(context, cube_252_output_limb_9_col41),
    ];
    let numerator_0 = eval!(context, 1);
    acc.add_to_relation(context, numerator_0, tuple_0);

    // Use Cube252.
    let tuple_1 = &[
        eval!(context, 1987997202),
        eval!(context, input_limb_12_col12),
        eval!(context, input_limb_13_col13),
        eval!(context, input_limb_14_col14),
        eval!(context, input_limb_15_col15),
        eval!(context, input_limb_16_col16),
        eval!(context, input_limb_17_col17),
        eval!(context, input_limb_18_col18),
        eval!(context, input_limb_19_col19),
        eval!(context, input_limb_20_col20),
        eval!(context, input_limb_21_col21),
        eval!(context, cube_252_output_limb_0_col42),
        eval!(context, cube_252_output_limb_1_col43),
        eval!(context, cube_252_output_limb_2_col44),
        eval!(context, cube_252_output_limb_3_col45),
        eval!(context, cube_252_output_limb_4_col46),
        eval!(context, cube_252_output_limb_5_col47),
        eval!(context, cube_252_output_limb_6_col48),
        eval!(context, cube_252_output_limb_7_col49),
        eval!(context, cube_252_output_limb_8_col50),
        eval!(context, cube_252_output_limb_9_col51),
    ];
    let numerator_1 = eval!(context, 1);
    acc.add_to_relation(context, numerator_1, tuple_1);

    // Use Cube252.
    let tuple_2 = &[
        eval!(context, 1987997202),
        eval!(context, input_limb_22_col22),
        eval!(context, input_limb_23_col23),
        eval!(context, input_limb_24_col24),
        eval!(context, input_limb_25_col25),
        eval!(context, input_limb_26_col26),
        eval!(context, input_limb_27_col27),
        eval!(context, input_limb_28_col28),
        eval!(context, input_limb_29_col29),
        eval!(context, input_limb_30_col30),
        eval!(context, input_limb_31_col31),
        eval!(context, cube_252_output_limb_0_col52),
        eval!(context, cube_252_output_limb_1_col53),
        eval!(context, cube_252_output_limb_2_col54),
        eval!(context, cube_252_output_limb_3_col55),
        eval!(context, cube_252_output_limb_4_col56),
        eval!(context, cube_252_output_limb_5_col57),
        eval!(context, cube_252_output_limb_6_col58),
        eval!(context, cube_252_output_limb_7_col59),
        eval!(context, cube_252_output_limb_8_col60),
        eval!(context, cube_252_output_limb_9_col61),
    ];
    let numerator_2 = eval!(context, 1);
    acc.add_to_relation(context, numerator_2, tuple_2);

    // Use PoseidonRoundKeys.
    let tuple_3 = &[
        eval!(context, 1024310512),
        eval!(context, input_limb_1_col1),
        eval!(context, poseidon_round_keys_output_limb_0_col62),
        eval!(context, poseidon_round_keys_output_limb_1_col63),
        eval!(context, poseidon_round_keys_output_limb_2_col64),
        eval!(context, poseidon_round_keys_output_limb_3_col65),
        eval!(context, poseidon_round_keys_output_limb_4_col66),
        eval!(context, poseidon_round_keys_output_limb_5_col67),
        eval!(context, poseidon_round_keys_output_limb_6_col68),
        eval!(context, poseidon_round_keys_output_limb_7_col69),
        eval!(context, poseidon_round_keys_output_limb_8_col70),
        eval!(context, poseidon_round_keys_output_limb_9_col71),
        eval!(context, poseidon_round_keys_output_limb_10_col72),
        eval!(context, poseidon_round_keys_output_limb_11_col73),
        eval!(context, poseidon_round_keys_output_limb_12_col74),
        eval!(context, poseidon_round_keys_output_limb_13_col75),
        eval!(context, poseidon_round_keys_output_limb_14_col76),
        eval!(context, poseidon_round_keys_output_limb_15_col77),
        eval!(context, poseidon_round_keys_output_limb_16_col78),
        eval!(context, poseidon_round_keys_output_limb_17_col79),
        eval!(context, poseidon_round_keys_output_limb_18_col80),
        eval!(context, poseidon_round_keys_output_limb_19_col81),
        eval!(context, poseidon_round_keys_output_limb_20_col82),
        eval!(context, poseidon_round_keys_output_limb_21_col83),
        eval!(context, poseidon_round_keys_output_limb_22_col84),
        eval!(context, poseidon_round_keys_output_limb_23_col85),
        eval!(context, poseidon_round_keys_output_limb_24_col86),
        eval!(context, poseidon_round_keys_output_limb_25_col87),
        eval!(context, poseidon_round_keys_output_limb_26_col88),
        eval!(context, poseidon_round_keys_output_limb_27_col89),
        eval!(context, poseidon_round_keys_output_limb_28_col90),
        eval!(context, poseidon_round_keys_output_limb_29_col91),
    ];
    let numerator_3 = eval!(context, 1);
    acc.add_to_relation(context, numerator_3, tuple_3);

    linear_combination_n_4_coefs_3_1_1_1::accumulate_constraints(
        &[
            eval!(context, cube_252_output_limb_0_col32),
            eval!(context, cube_252_output_limb_1_col33),
            eval!(context, cube_252_output_limb_2_col34),
            eval!(context, cube_252_output_limb_3_col35),
            eval!(context, cube_252_output_limb_4_col36),
            eval!(context, cube_252_output_limb_5_col37),
            eval!(context, cube_252_output_limb_6_col38),
            eval!(context, cube_252_output_limb_7_col39),
            eval!(context, cube_252_output_limb_8_col40),
            eval!(context, cube_252_output_limb_9_col41),
            eval!(context, cube_252_output_limb_0_col42),
            eval!(context, cube_252_output_limb_1_col43),
            eval!(context, cube_252_output_limb_2_col44),
            eval!(context, cube_252_output_limb_3_col45),
            eval!(context, cube_252_output_limb_4_col46),
            eval!(context, cube_252_output_limb_5_col47),
            eval!(context, cube_252_output_limb_6_col48),
            eval!(context, cube_252_output_limb_7_col49),
            eval!(context, cube_252_output_limb_8_col50),
            eval!(context, cube_252_output_limb_9_col51),
            eval!(context, cube_252_output_limb_0_col52),
            eval!(context, cube_252_output_limb_1_col53),
            eval!(context, cube_252_output_limb_2_col54),
            eval!(context, cube_252_output_limb_3_col55),
            eval!(context, cube_252_output_limb_4_col56),
            eval!(context, cube_252_output_limb_5_col57),
            eval!(context, cube_252_output_limb_6_col58),
            eval!(context, cube_252_output_limb_7_col59),
            eval!(context, cube_252_output_limb_8_col60),
            eval!(context, cube_252_output_limb_9_col61),
            eval!(context, poseidon_round_keys_output_limb_0_col62),
            eval!(context, poseidon_round_keys_output_limb_1_col63),
            eval!(context, poseidon_round_keys_output_limb_2_col64),
            eval!(context, poseidon_round_keys_output_limb_3_col65),
            eval!(context, poseidon_round_keys_output_limb_4_col66),
            eval!(context, poseidon_round_keys_output_limb_5_col67),
            eval!(context, poseidon_round_keys_output_limb_6_col68),
            eval!(context, poseidon_round_keys_output_limb_7_col69),
            eval!(context, poseidon_round_keys_output_limb_8_col70),
            eval!(context, poseidon_round_keys_output_limb_9_col71),
            eval!(context, combination_limb_0_col92),
            eval!(context, combination_limb_1_col93),
            eval!(context, combination_limb_2_col94),
            eval!(context, combination_limb_3_col95),
            eval!(context, combination_limb_4_col96),
            eval!(context, combination_limb_5_col97),
            eval!(context, combination_limb_6_col98),
            eval!(context, combination_limb_7_col99),
            eval!(context, combination_limb_8_col100),
            eval!(context, combination_limb_9_col101),
            eval!(context, p_coef_col102),
        ],
        context,
        component_data,
        acc,
    );

    linear_combination_n_4_coefs_1_m1_1_1::accumulate_constraints(
        &[
            eval!(context, cube_252_output_limb_0_col32),
            eval!(context, cube_252_output_limb_1_col33),
            eval!(context, cube_252_output_limb_2_col34),
            eval!(context, cube_252_output_limb_3_col35),
            eval!(context, cube_252_output_limb_4_col36),
            eval!(context, cube_252_output_limb_5_col37),
            eval!(context, cube_252_output_limb_6_col38),
            eval!(context, cube_252_output_limb_7_col39),
            eval!(context, cube_252_output_limb_8_col40),
            eval!(context, cube_252_output_limb_9_col41),
            eval!(context, cube_252_output_limb_0_col42),
            eval!(context, cube_252_output_limb_1_col43),
            eval!(context, cube_252_output_limb_2_col44),
            eval!(context, cube_252_output_limb_3_col45),
            eval!(context, cube_252_output_limb_4_col46),
            eval!(context, cube_252_output_limb_5_col47),
            eval!(context, cube_252_output_limb_6_col48),
            eval!(context, cube_252_output_limb_7_col49),
            eval!(context, cube_252_output_limb_8_col50),
            eval!(context, cube_252_output_limb_9_col51),
            eval!(context, cube_252_output_limb_0_col52),
            eval!(context, cube_252_output_limb_1_col53),
            eval!(context, cube_252_output_limb_2_col54),
            eval!(context, cube_252_output_limb_3_col55),
            eval!(context, cube_252_output_limb_4_col56),
            eval!(context, cube_252_output_limb_5_col57),
            eval!(context, cube_252_output_limb_6_col58),
            eval!(context, cube_252_output_limb_7_col59),
            eval!(context, cube_252_output_limb_8_col60),
            eval!(context, cube_252_output_limb_9_col61),
            eval!(context, poseidon_round_keys_output_limb_10_col72),
            eval!(context, poseidon_round_keys_output_limb_11_col73),
            eval!(context, poseidon_round_keys_output_limb_12_col74),
            eval!(context, poseidon_round_keys_output_limb_13_col75),
            eval!(context, poseidon_round_keys_output_limb_14_col76),
            eval!(context, poseidon_round_keys_output_limb_15_col77),
            eval!(context, poseidon_round_keys_output_limb_16_col78),
            eval!(context, poseidon_round_keys_output_limb_17_col79),
            eval!(context, poseidon_round_keys_output_limb_18_col80),
            eval!(context, poseidon_round_keys_output_limb_19_col81),
            eval!(context, combination_limb_0_col103),
            eval!(context, combination_limb_1_col104),
            eval!(context, combination_limb_2_col105),
            eval!(context, combination_limb_3_col106),
            eval!(context, combination_limb_4_col107),
            eval!(context, combination_limb_5_col108),
            eval!(context, combination_limb_6_col109),
            eval!(context, combination_limb_7_col110),
            eval!(context, combination_limb_8_col111),
            eval!(context, combination_limb_9_col112),
            eval!(context, p_coef_col113),
        ],
        context,
        component_data,
        acc,
    );

    linear_combination_n_4_coefs_1_1_m2_1::accumulate_constraints(
        &[
            eval!(context, cube_252_output_limb_0_col32),
            eval!(context, cube_252_output_limb_1_col33),
            eval!(context, cube_252_output_limb_2_col34),
            eval!(context, cube_252_output_limb_3_col35),
            eval!(context, cube_252_output_limb_4_col36),
            eval!(context, cube_252_output_limb_5_col37),
            eval!(context, cube_252_output_limb_6_col38),
            eval!(context, cube_252_output_limb_7_col39),
            eval!(context, cube_252_output_limb_8_col40),
            eval!(context, cube_252_output_limb_9_col41),
            eval!(context, cube_252_output_limb_0_col42),
            eval!(context, cube_252_output_limb_1_col43),
            eval!(context, cube_252_output_limb_2_col44),
            eval!(context, cube_252_output_limb_3_col45),
            eval!(context, cube_252_output_limb_4_col46),
            eval!(context, cube_252_output_limb_5_col47),
            eval!(context, cube_252_output_limb_6_col48),
            eval!(context, cube_252_output_limb_7_col49),
            eval!(context, cube_252_output_limb_8_col50),
            eval!(context, cube_252_output_limb_9_col51),
            eval!(context, cube_252_output_limb_0_col52),
            eval!(context, cube_252_output_limb_1_col53),
            eval!(context, cube_252_output_limb_2_col54),
            eval!(context, cube_252_output_limb_3_col55),
            eval!(context, cube_252_output_limb_4_col56),
            eval!(context, cube_252_output_limb_5_col57),
            eval!(context, cube_252_output_limb_6_col58),
            eval!(context, cube_252_output_limb_7_col59),
            eval!(context, cube_252_output_limb_8_col60),
            eval!(context, cube_252_output_limb_9_col61),
            eval!(context, poseidon_round_keys_output_limb_20_col82),
            eval!(context, poseidon_round_keys_output_limb_21_col83),
            eval!(context, poseidon_round_keys_output_limb_22_col84),
            eval!(context, poseidon_round_keys_output_limb_23_col85),
            eval!(context, poseidon_round_keys_output_limb_24_col86),
            eval!(context, poseidon_round_keys_output_limb_25_col87),
            eval!(context, poseidon_round_keys_output_limb_26_col88),
            eval!(context, poseidon_round_keys_output_limb_27_col89),
            eval!(context, poseidon_round_keys_output_limb_28_col90),
            eval!(context, poseidon_round_keys_output_limb_29_col91),
            eval!(context, combination_limb_0_col114),
            eval!(context, combination_limb_1_col115),
            eval!(context, combination_limb_2_col116),
            eval!(context, combination_limb_3_col117),
            eval!(context, combination_limb_4_col118),
            eval!(context, combination_limb_5_col119),
            eval!(context, combination_limb_6_col120),
            eval!(context, combination_limb_7_col121),
            eval!(context, combination_limb_8_col122),
            eval!(context, combination_limb_9_col123),
            eval!(context, p_coef_col124),
        ],
        context,
        component_data,
        acc,
    );

    // Use PoseidonFullRoundChain.
    let tuple_7 = &[
        eval!(context, 1480369132),
        eval!(context, input_limb_0_col0),
        eval!(context, input_limb_1_col1),
        eval!(context, input_limb_2_col2),
        eval!(context, input_limb_3_col3),
        eval!(context, input_limb_4_col4),
        eval!(context, input_limb_5_col5),
        eval!(context, input_limb_6_col6),
        eval!(context, input_limb_7_col7),
        eval!(context, input_limb_8_col8),
        eval!(context, input_limb_9_col9),
        eval!(context, input_limb_10_col10),
        eval!(context, input_limb_11_col11),
        eval!(context, input_limb_12_col12),
        eval!(context, input_limb_13_col13),
        eval!(context, input_limb_14_col14),
        eval!(context, input_limb_15_col15),
        eval!(context, input_limb_16_col16),
        eval!(context, input_limb_17_col17),
        eval!(context, input_limb_18_col18),
        eval!(context, input_limb_19_col19),
        eval!(context, input_limb_20_col20),
        eval!(context, input_limb_21_col21),
        eval!(context, input_limb_22_col22),
        eval!(context, input_limb_23_col23),
        eval!(context, input_limb_24_col24),
        eval!(context, input_limb_25_col25),
        eval!(context, input_limb_26_col26),
        eval!(context, input_limb_27_col27),
        eval!(context, input_limb_28_col28),
        eval!(context, input_limb_29_col29),
        eval!(context, input_limb_30_col30),
        eval!(context, input_limb_31_col31),
    ];
    let numerator_7 = eval!(context, enabler);
    acc.add_to_relation(context, numerator_7, tuple_7);

    // Yield PoseidonFullRoundChain.
    let tuple_8 = &[
        eval!(context, 1480369132),
        eval!(context, input_limb_0_col0),
        eval!(context, (input_limb_1_col1) + (1)),
        eval!(context, combination_limb_0_col92),
        eval!(context, combination_limb_1_col93),
        eval!(context, combination_limb_2_col94),
        eval!(context, combination_limb_3_col95),
        eval!(context, combination_limb_4_col96),
        eval!(context, combination_limb_5_col97),
        eval!(context, combination_limb_6_col98),
        eval!(context, combination_limb_7_col99),
        eval!(context, combination_limb_8_col100),
        eval!(context, combination_limb_9_col101),
        eval!(context, combination_limb_0_col103),
        eval!(context, combination_limb_1_col104),
        eval!(context, combination_limb_2_col105),
        eval!(context, combination_limb_3_col106),
        eval!(context, combination_limb_4_col107),
        eval!(context, combination_limb_5_col108),
        eval!(context, combination_limb_6_col109),
        eval!(context, combination_limb_7_col110),
        eval!(context, combination_limb_8_col111),
        eval!(context, combination_limb_9_col112),
        eval!(context, combination_limb_0_col114),
        eval!(context, combination_limb_1_col115),
        eval!(context, combination_limb_2_col116),
        eval!(context, combination_limb_3_col117),
        eval!(context, combination_limb_4_col118),
        eval!(context, combination_limb_5_col119),
        eval!(context, combination_limb_6_col120),
        eval!(context, combination_limb_7_col121),
        eval!(context, combination_limb_8_col122),
        eval!(context, combination_limb_9_col123),
    ];
    let numerator_8 = eval!(context, -(enabler));
    acc.add_to_relation(context, numerator_8, tuple_8);
}

pub struct Component {}
impl<Value: IValue> CircuitEval<Value> for Component {
    fn evaluate(
        &self,
        context: &mut Context<Value>,
        component_data: &ComponentData<'_>,
        acc: &mut CompositionConstraintAccumulator,
    ) {
        accumulate_constraints(component_data.trace_columns, context, component_data, acc);
    }

    fn trace_columns(&self) -> usize {
        N_TRACE_COLUMNS
    }

    fn interaction_columns(&self) -> usize {
        N_INTERACTION_COLUMNS
    }

    fn relation_uses_per_row(&self) -> &[RelationUse] {
        &RELATION_USES_PER_ROW
    }
}
