// This file was created by the AIR team.

use crate::cairo_air::components::prelude::*;

pub const RELATION_USES_PER_ROW: [RelationUse; 16] = [
    RelationUse { relation_id: "RangeCheck_20", uses: 4 },
    RelationUse { relation_id: "RangeCheck_20_B", uses: 4 },
    RelationUse { relation_id: "RangeCheck_20_C", uses: 4 },
    RelationUse { relation_id: "RangeCheck_20_D", uses: 4 },
    RelationUse { relation_id: "RangeCheck_20_E", uses: 3 },
    RelationUse { relation_id: "RangeCheck_20_F", uses: 3 },
    RelationUse { relation_id: "RangeCheck_20_G", uses: 3 },
    RelationUse { relation_id: "RangeCheck_20_H", uses: 3 },
    RelationUse { relation_id: "RangeCheck_9_9", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_B", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_C", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_D", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_E", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_F", uses: 2 },
    RelationUse { relation_id: "RangeCheck_9_9_G", uses: 1 },
    RelationUse { relation_id: "RangeCheck_9_9_H", uses: 1 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints<Value: IValue>(
    input: &[Var],
    context: &mut Context<Value>,
    component_data: &dyn ComponentDataTrait<Value>,
    acc: &mut CompositionConstraintAccumulator,
) -> Vec<Var> {
    let [
        mul_252_input_a_limb_0,
        mul_252_input_a_limb_1,
        mul_252_input_a_limb_2,
        mul_252_input_a_limb_3,
        mul_252_input_a_limb_4,
        mul_252_input_a_limb_5,
        mul_252_input_a_limb_6,
        mul_252_input_a_limb_7,
        mul_252_input_a_limb_8,
        mul_252_input_a_limb_9,
        mul_252_input_a_limb_10,
        mul_252_input_a_limb_11,
        mul_252_input_a_limb_12,
        mul_252_input_a_limb_13,
        mul_252_input_a_limb_14,
        mul_252_input_a_limb_15,
        mul_252_input_a_limb_16,
        mul_252_input_a_limb_17,
        mul_252_input_a_limb_18,
        mul_252_input_a_limb_19,
        mul_252_input_a_limb_20,
        mul_252_input_a_limb_21,
        mul_252_input_a_limb_22,
        mul_252_input_a_limb_23,
        mul_252_input_a_limb_24,
        mul_252_input_a_limb_25,
        mul_252_input_a_limb_26,
        mul_252_input_a_limb_27,
        mul_252_input_b_limb_0,
        mul_252_input_b_limb_1,
        mul_252_input_b_limb_2,
        mul_252_input_b_limb_3,
        mul_252_input_b_limb_4,
        mul_252_input_b_limb_5,
        mul_252_input_b_limb_6,
        mul_252_input_b_limb_7,
        mul_252_input_b_limb_8,
        mul_252_input_b_limb_9,
        mul_252_input_b_limb_10,
        mul_252_input_b_limb_11,
        mul_252_input_b_limb_12,
        mul_252_input_b_limb_13,
        mul_252_input_b_limb_14,
        mul_252_input_b_limb_15,
        mul_252_input_b_limb_16,
        mul_252_input_b_limb_17,
        mul_252_input_b_limb_18,
        mul_252_input_b_limb_19,
        mul_252_input_b_limb_20,
        mul_252_input_b_limb_21,
        mul_252_input_b_limb_22,
        mul_252_input_b_limb_23,
        mul_252_input_b_limb_24,
        mul_252_input_b_limb_25,
        mul_252_input_b_limb_26,
        mul_252_input_b_limb_27,
        mul_res_limb_0_col0,
        mul_res_limb_1_col1,
        mul_res_limb_2_col2,
        mul_res_limb_3_col3,
        mul_res_limb_4_col4,
        mul_res_limb_5_col5,
        mul_res_limb_6_col6,
        mul_res_limb_7_col7,
        mul_res_limb_8_col8,
        mul_res_limb_9_col9,
        mul_res_limb_10_col10,
        mul_res_limb_11_col11,
        mul_res_limb_12_col12,
        mul_res_limb_13_col13,
        mul_res_limb_14_col14,
        mul_res_limb_15_col15,
        mul_res_limb_16_col16,
        mul_res_limb_17_col17,
        mul_res_limb_18_col18,
        mul_res_limb_19_col19,
        mul_res_limb_20_col20,
        mul_res_limb_21_col21,
        mul_res_limb_22_col22,
        mul_res_limb_23_col23,
        mul_res_limb_24_col24,
        mul_res_limb_25_col25,
        mul_res_limb_26_col26,
        mul_res_limb_27_col27,
        k_col28,
        carry_0_col29,
        carry_1_col30,
        carry_2_col31,
        carry_3_col32,
        carry_4_col33,
        carry_5_col34,
        carry_6_col35,
        carry_7_col36,
        carry_8_col37,
        carry_9_col38,
        carry_10_col39,
        carry_11_col40,
        carry_12_col41,
        carry_13_col42,
        carry_14_col43,
        carry_15_col44,
        carry_16_col45,
        carry_17_col46,
        carry_18_col47,
        carry_19_col48,
        carry_20_col49,
        carry_21_col50,
        carry_22_col51,
        carry_23_col52,
        carry_24_col53,
        carry_25_col54,
        carry_26_col55,
    ] = input.try_into().unwrap();

    range_check_mem_value_n_28::accumulate_constraints(
        &[
            eval!(context, mul_res_limb_0_col0),
            eval!(context, mul_res_limb_1_col1),
            eval!(context, mul_res_limb_2_col2),
            eval!(context, mul_res_limb_3_col3),
            eval!(context, mul_res_limb_4_col4),
            eval!(context, mul_res_limb_5_col5),
            eval!(context, mul_res_limb_6_col6),
            eval!(context, mul_res_limb_7_col7),
            eval!(context, mul_res_limb_8_col8),
            eval!(context, mul_res_limb_9_col9),
            eval!(context, mul_res_limb_10_col10),
            eval!(context, mul_res_limb_11_col11),
            eval!(context, mul_res_limb_12_col12),
            eval!(context, mul_res_limb_13_col13),
            eval!(context, mul_res_limb_14_col14),
            eval!(context, mul_res_limb_15_col15),
            eval!(context, mul_res_limb_16_col16),
            eval!(context, mul_res_limb_17_col17),
            eval!(context, mul_res_limb_18_col18),
            eval!(context, mul_res_limb_19_col19),
            eval!(context, mul_res_limb_20_col20),
            eval!(context, mul_res_limb_21_col21),
            eval!(context, mul_res_limb_22_col22),
            eval!(context, mul_res_limb_23_col23),
            eval!(context, mul_res_limb_24_col24),
            eval!(context, mul_res_limb_25_col25),
            eval!(context, mul_res_limb_26_col26),
            eval!(context, mul_res_limb_27_col27),
        ],
        context,
        component_data,
        acc,
    );

    verify_mul_252::accumulate_constraints(
        &[
            eval!(context, mul_252_input_a_limb_0),
            eval!(context, mul_252_input_a_limb_1),
            eval!(context, mul_252_input_a_limb_2),
            eval!(context, mul_252_input_a_limb_3),
            eval!(context, mul_252_input_a_limb_4),
            eval!(context, mul_252_input_a_limb_5),
            eval!(context, mul_252_input_a_limb_6),
            eval!(context, mul_252_input_a_limb_7),
            eval!(context, mul_252_input_a_limb_8),
            eval!(context, mul_252_input_a_limb_9),
            eval!(context, mul_252_input_a_limb_10),
            eval!(context, mul_252_input_a_limb_11),
            eval!(context, mul_252_input_a_limb_12),
            eval!(context, mul_252_input_a_limb_13),
            eval!(context, mul_252_input_a_limb_14),
            eval!(context, mul_252_input_a_limb_15),
            eval!(context, mul_252_input_a_limb_16),
            eval!(context, mul_252_input_a_limb_17),
            eval!(context, mul_252_input_a_limb_18),
            eval!(context, mul_252_input_a_limb_19),
            eval!(context, mul_252_input_a_limb_20),
            eval!(context, mul_252_input_a_limb_21),
            eval!(context, mul_252_input_a_limb_22),
            eval!(context, mul_252_input_a_limb_23),
            eval!(context, mul_252_input_a_limb_24),
            eval!(context, mul_252_input_a_limb_25),
            eval!(context, mul_252_input_a_limb_26),
            eval!(context, mul_252_input_a_limb_27),
            eval!(context, mul_252_input_b_limb_0),
            eval!(context, mul_252_input_b_limb_1),
            eval!(context, mul_252_input_b_limb_2),
            eval!(context, mul_252_input_b_limb_3),
            eval!(context, mul_252_input_b_limb_4),
            eval!(context, mul_252_input_b_limb_5),
            eval!(context, mul_252_input_b_limb_6),
            eval!(context, mul_252_input_b_limb_7),
            eval!(context, mul_252_input_b_limb_8),
            eval!(context, mul_252_input_b_limb_9),
            eval!(context, mul_252_input_b_limb_10),
            eval!(context, mul_252_input_b_limb_11),
            eval!(context, mul_252_input_b_limb_12),
            eval!(context, mul_252_input_b_limb_13),
            eval!(context, mul_252_input_b_limb_14),
            eval!(context, mul_252_input_b_limb_15),
            eval!(context, mul_252_input_b_limb_16),
            eval!(context, mul_252_input_b_limb_17),
            eval!(context, mul_252_input_b_limb_18),
            eval!(context, mul_252_input_b_limb_19),
            eval!(context, mul_252_input_b_limb_20),
            eval!(context, mul_252_input_b_limb_21),
            eval!(context, mul_252_input_b_limb_22),
            eval!(context, mul_252_input_b_limb_23),
            eval!(context, mul_252_input_b_limb_24),
            eval!(context, mul_252_input_b_limb_25),
            eval!(context, mul_252_input_b_limb_26),
            eval!(context, mul_252_input_b_limb_27),
            eval!(context, mul_res_limb_0_col0),
            eval!(context, mul_res_limb_1_col1),
            eval!(context, mul_res_limb_2_col2),
            eval!(context, mul_res_limb_3_col3),
            eval!(context, mul_res_limb_4_col4),
            eval!(context, mul_res_limb_5_col5),
            eval!(context, mul_res_limb_6_col6),
            eval!(context, mul_res_limb_7_col7),
            eval!(context, mul_res_limb_8_col8),
            eval!(context, mul_res_limb_9_col9),
            eval!(context, mul_res_limb_10_col10),
            eval!(context, mul_res_limb_11_col11),
            eval!(context, mul_res_limb_12_col12),
            eval!(context, mul_res_limb_13_col13),
            eval!(context, mul_res_limb_14_col14),
            eval!(context, mul_res_limb_15_col15),
            eval!(context, mul_res_limb_16_col16),
            eval!(context, mul_res_limb_17_col17),
            eval!(context, mul_res_limb_18_col18),
            eval!(context, mul_res_limb_19_col19),
            eval!(context, mul_res_limb_20_col20),
            eval!(context, mul_res_limb_21_col21),
            eval!(context, mul_res_limb_22_col22),
            eval!(context, mul_res_limb_23_col23),
            eval!(context, mul_res_limb_24_col24),
            eval!(context, mul_res_limb_25_col25),
            eval!(context, mul_res_limb_26_col26),
            eval!(context, mul_res_limb_27_col27),
            eval!(context, k_col28),
            eval!(context, carry_0_col29),
            eval!(context, carry_1_col30),
            eval!(context, carry_2_col31),
            eval!(context, carry_3_col32),
            eval!(context, carry_4_col33),
            eval!(context, carry_5_col34),
            eval!(context, carry_6_col35),
            eval!(context, carry_7_col36),
            eval!(context, carry_8_col37),
            eval!(context, carry_9_col38),
            eval!(context, carry_10_col39),
            eval!(context, carry_11_col40),
            eval!(context, carry_12_col41),
            eval!(context, carry_13_col42),
            eval!(context, carry_14_col43),
            eval!(context, carry_15_col44),
            eval!(context, carry_16_col45),
            eval!(context, carry_17_col46),
            eval!(context, carry_18_col47),
            eval!(context, carry_19_col48),
            eval!(context, carry_20_col49),
            eval!(context, carry_21_col50),
            eval!(context, carry_22_col51),
            eval!(context, carry_23_col52),
            eval!(context, carry_24_col53),
            eval!(context, carry_25_col54),
            eval!(context, carry_26_col55),
        ],
        context,
        component_data,
        acc,
    );
    vec![]
}
