// This file was created by the AIR team.

use crate::cairo_air::components::prelude::*;

pub const RELATION_USES_PER_ROW: [RelationUse; 7] = [
    RelationUse { relation_id: "Cube252", uses: 2 },
    RelationUse { relation_id: "Poseidon3PartialRoundsChain", uses: 1 },
    RelationUse { relation_id: "PoseidonFullRoundChain", uses: 2 },
    RelationUse { relation_id: "RangeCheck252Width27", uses: 2 },
    RelationUse { relation_id: "RangeCheck_3_3_3_3_3", uses: 2 },
    RelationUse { relation_id: "RangeCheck_4_4", uses: 3 },
    RelationUse { relation_id: "RangeCheck_4_4_4_4", uses: 6 },
];

#[allow(unused_variables)]
pub fn accumulate_constraints(
    input: &[Var],
    context: &mut Context<impl IValue>,
    component_data: &ComponentData<'_>,
    acc: &mut CompositionConstraintAccumulator,
) -> Vec<Var> {
    let [
        poseidon_hades_permutation_input_limb_0,
        poseidon_hades_permutation_input_limb_1,
        poseidon_hades_permutation_input_limb_2,
        poseidon_hades_permutation_input_limb_3,
        poseidon_hades_permutation_input_limb_4,
        poseidon_hades_permutation_input_limb_5,
        poseidon_hades_permutation_input_limb_6,
        poseidon_hades_permutation_input_limb_7,
        poseidon_hades_permutation_input_limb_8,
        poseidon_hades_permutation_input_limb_9,
        poseidon_hades_permutation_input_limb_10,
        poseidon_hades_permutation_input_limb_11,
        poseidon_hades_permutation_input_limb_12,
        poseidon_hades_permutation_input_limb_13,
        poseidon_hades_permutation_input_limb_14,
        poseidon_hades_permutation_input_limb_15,
        poseidon_hades_permutation_input_limb_16,
        poseidon_hades_permutation_input_limb_17,
        poseidon_hades_permutation_input_limb_18,
        poseidon_hades_permutation_input_limb_19,
        poseidon_hades_permutation_input_limb_20,
        poseidon_hades_permutation_input_limb_21,
        poseidon_hades_permutation_input_limb_22,
        poseidon_hades_permutation_input_limb_23,
        poseidon_hades_permutation_input_limb_24,
        poseidon_hades_permutation_input_limb_25,
        poseidon_hades_permutation_input_limb_26,
        poseidon_hades_permutation_input_limb_27,
        poseidon_hades_permutation_input_limb_28,
        poseidon_hades_permutation_input_limb_29,
        combination_limb_0_col0,
        combination_limb_1_col1,
        combination_limb_2_col2,
        combination_limb_3_col3,
        combination_limb_4_col4,
        combination_limb_5_col5,
        combination_limb_6_col6,
        combination_limb_7_col7,
        combination_limb_8_col8,
        combination_limb_9_col9,
        p_coef_col10,
        combination_limb_0_col11,
        combination_limb_1_col12,
        combination_limb_2_col13,
        combination_limb_3_col14,
        combination_limb_4_col15,
        combination_limb_5_col16,
        combination_limb_6_col17,
        combination_limb_7_col18,
        combination_limb_8_col19,
        combination_limb_9_col20,
        p_coef_col21,
        combination_limb_0_col22,
        combination_limb_1_col23,
        combination_limb_2_col24,
        combination_limb_3_col25,
        combination_limb_4_col26,
        combination_limb_5_col27,
        combination_limb_6_col28,
        combination_limb_7_col29,
        combination_limb_8_col30,
        combination_limb_9_col31,
        p_coef_col32,
        poseidon_full_round_chain_output_limb_0_col33,
        poseidon_full_round_chain_output_limb_1_col34,
        poseidon_full_round_chain_output_limb_2_col35,
        poseidon_full_round_chain_output_limb_3_col36,
        poseidon_full_round_chain_output_limb_4_col37,
        poseidon_full_round_chain_output_limb_5_col38,
        poseidon_full_round_chain_output_limb_6_col39,
        poseidon_full_round_chain_output_limb_7_col40,
        poseidon_full_round_chain_output_limb_8_col41,
        poseidon_full_round_chain_output_limb_9_col42,
        poseidon_full_round_chain_output_limb_10_col43,
        poseidon_full_round_chain_output_limb_11_col44,
        poseidon_full_round_chain_output_limb_12_col45,
        poseidon_full_round_chain_output_limb_13_col46,
        poseidon_full_round_chain_output_limb_14_col47,
        poseidon_full_round_chain_output_limb_15_col48,
        poseidon_full_round_chain_output_limb_16_col49,
        poseidon_full_round_chain_output_limb_17_col50,
        poseidon_full_round_chain_output_limb_18_col51,
        poseidon_full_round_chain_output_limb_19_col52,
        poseidon_full_round_chain_output_limb_20_col53,
        poseidon_full_round_chain_output_limb_21_col54,
        poseidon_full_round_chain_output_limb_22_col55,
        poseidon_full_round_chain_output_limb_23_col56,
        poseidon_full_round_chain_output_limb_24_col57,
        poseidon_full_round_chain_output_limb_25_col58,
        poseidon_full_round_chain_output_limb_26_col59,
        poseidon_full_round_chain_output_limb_27_col60,
        poseidon_full_round_chain_output_limb_28_col61,
        poseidon_full_round_chain_output_limb_29_col62,
        cube_252_output_limb_0_col63,
        cube_252_output_limb_1_col64,
        cube_252_output_limb_2_col65,
        cube_252_output_limb_3_col66,
        cube_252_output_limb_4_col67,
        cube_252_output_limb_5_col68,
        cube_252_output_limb_6_col69,
        cube_252_output_limb_7_col70,
        cube_252_output_limb_8_col71,
        cube_252_output_limb_9_col72,
        combination_limb_0_col73,
        combination_limb_1_col74,
        combination_limb_2_col75,
        combination_limb_3_col76,
        combination_limb_4_col77,
        combination_limb_5_col78,
        combination_limb_6_col79,
        combination_limb_7_col80,
        combination_limb_8_col81,
        combination_limb_9_col82,
        p_coef_col83,
        cube_252_output_limb_0_col84,
        cube_252_output_limb_1_col85,
        cube_252_output_limb_2_col86,
        cube_252_output_limb_3_col87,
        cube_252_output_limb_4_col88,
        cube_252_output_limb_5_col89,
        cube_252_output_limb_6_col90,
        cube_252_output_limb_7_col91,
        cube_252_output_limb_8_col92,
        cube_252_output_limb_9_col93,
        combination_limb_0_col94,
        combination_limb_1_col95,
        combination_limb_2_col96,
        combination_limb_3_col97,
        combination_limb_4_col98,
        combination_limb_5_col99,
        combination_limb_6_col100,
        combination_limb_7_col101,
        combination_limb_8_col102,
        combination_limb_9_col103,
        p_coef_col104,
        poseidon_3_partial_rounds_chain_output_limb_0_col105,
        poseidon_3_partial_rounds_chain_output_limb_1_col106,
        poseidon_3_partial_rounds_chain_output_limb_2_col107,
        poseidon_3_partial_rounds_chain_output_limb_3_col108,
        poseidon_3_partial_rounds_chain_output_limb_4_col109,
        poseidon_3_partial_rounds_chain_output_limb_5_col110,
        poseidon_3_partial_rounds_chain_output_limb_6_col111,
        poseidon_3_partial_rounds_chain_output_limb_7_col112,
        poseidon_3_partial_rounds_chain_output_limb_8_col113,
        poseidon_3_partial_rounds_chain_output_limb_9_col114,
        poseidon_3_partial_rounds_chain_output_limb_10_col115,
        poseidon_3_partial_rounds_chain_output_limb_11_col116,
        poseidon_3_partial_rounds_chain_output_limb_12_col117,
        poseidon_3_partial_rounds_chain_output_limb_13_col118,
        poseidon_3_partial_rounds_chain_output_limb_14_col119,
        poseidon_3_partial_rounds_chain_output_limb_15_col120,
        poseidon_3_partial_rounds_chain_output_limb_16_col121,
        poseidon_3_partial_rounds_chain_output_limb_17_col122,
        poseidon_3_partial_rounds_chain_output_limb_18_col123,
        poseidon_3_partial_rounds_chain_output_limb_19_col124,
        poseidon_3_partial_rounds_chain_output_limb_20_col125,
        poseidon_3_partial_rounds_chain_output_limb_21_col126,
        poseidon_3_partial_rounds_chain_output_limb_22_col127,
        poseidon_3_partial_rounds_chain_output_limb_23_col128,
        poseidon_3_partial_rounds_chain_output_limb_24_col129,
        poseidon_3_partial_rounds_chain_output_limb_25_col130,
        poseidon_3_partial_rounds_chain_output_limb_26_col131,
        poseidon_3_partial_rounds_chain_output_limb_27_col132,
        poseidon_3_partial_rounds_chain_output_limb_28_col133,
        poseidon_3_partial_rounds_chain_output_limb_29_col134,
        poseidon_3_partial_rounds_chain_output_limb_30_col135,
        poseidon_3_partial_rounds_chain_output_limb_31_col136,
        poseidon_3_partial_rounds_chain_output_limb_32_col137,
        poseidon_3_partial_rounds_chain_output_limb_33_col138,
        poseidon_3_partial_rounds_chain_output_limb_34_col139,
        poseidon_3_partial_rounds_chain_output_limb_35_col140,
        poseidon_3_partial_rounds_chain_output_limb_36_col141,
        poseidon_3_partial_rounds_chain_output_limb_37_col142,
        poseidon_3_partial_rounds_chain_output_limb_38_col143,
        poseidon_3_partial_rounds_chain_output_limb_39_col144,
        combination_limb_0_col145,
        combination_limb_1_col146,
        combination_limb_2_col147,
        combination_limb_3_col148,
        combination_limb_4_col149,
        combination_limb_5_col150,
        combination_limb_6_col151,
        combination_limb_7_col152,
        combination_limb_8_col153,
        combination_limb_9_col154,
        p_coef_col155,
        combination_limb_0_col156,
        combination_limb_1_col157,
        combination_limb_2_col158,
        combination_limb_3_col159,
        combination_limb_4_col160,
        combination_limb_5_col161,
        combination_limb_6_col162,
        combination_limb_7_col163,
        combination_limb_8_col164,
        combination_limb_9_col165,
        p_coef_col166,
        poseidon_full_round_chain_output_limb_0_col167,
        poseidon_full_round_chain_output_limb_1_col168,
        poseidon_full_round_chain_output_limb_2_col169,
        poseidon_full_round_chain_output_limb_3_col170,
        poseidon_full_round_chain_output_limb_4_col171,
        poseidon_full_round_chain_output_limb_5_col172,
        poseidon_full_round_chain_output_limb_6_col173,
        poseidon_full_round_chain_output_limb_7_col174,
        poseidon_full_round_chain_output_limb_8_col175,
        poseidon_full_round_chain_output_limb_9_col176,
        poseidon_full_round_chain_output_limb_10_col177,
        poseidon_full_round_chain_output_limb_11_col178,
        poseidon_full_round_chain_output_limb_12_col179,
        poseidon_full_round_chain_output_limb_13_col180,
        poseidon_full_round_chain_output_limb_14_col181,
        poseidon_full_round_chain_output_limb_15_col182,
        poseidon_full_round_chain_output_limb_16_col183,
        poseidon_full_round_chain_output_limb_17_col184,
        poseidon_full_round_chain_output_limb_18_col185,
        poseidon_full_round_chain_output_limb_19_col186,
        poseidon_full_round_chain_output_limb_20_col187,
        poseidon_full_round_chain_output_limb_21_col188,
        poseidon_full_round_chain_output_limb_22_col189,
        poseidon_full_round_chain_output_limb_23_col190,
        poseidon_full_round_chain_output_limb_24_col191,
        poseidon_full_round_chain_output_limb_25_col192,
        poseidon_full_round_chain_output_limb_26_col193,
        poseidon_full_round_chain_output_limb_27_col194,
        poseidon_full_round_chain_output_limb_28_col195,
        poseidon_full_round_chain_output_limb_29_col196,
    ] = input.try_into().unwrap();
    let seq = seq_of_component_size(context, component_data, acc);

    linear_combination_n_2_coefs_1_1::accumulate_constraints(
        &[
            eval!(context, poseidon_hades_permutation_input_limb_0),
            eval!(context, poseidon_hades_permutation_input_limb_1),
            eval!(context, poseidon_hades_permutation_input_limb_2),
            eval!(context, poseidon_hades_permutation_input_limb_3),
            eval!(context, poseidon_hades_permutation_input_limb_4),
            eval!(context, poseidon_hades_permutation_input_limb_5),
            eval!(context, poseidon_hades_permutation_input_limb_6),
            eval!(context, poseidon_hades_permutation_input_limb_7),
            eval!(context, poseidon_hades_permutation_input_limb_8),
            eval!(context, poseidon_hades_permutation_input_limb_9),
            eval!(context, 74972783),
            eval!(context, 117420501),
            eval!(context, 112795138),
            eval!(context, 91013252),
            eval!(context, 60709090),
            eval!(context, 44848225),
            eval!(context, 108487870),
            eval!(context, 44781849),
            eval!(context, 102193642),
            eval!(context, 208),
            eval!(context, combination_limb_0_col0),
            eval!(context, combination_limb_1_col1),
            eval!(context, combination_limb_2_col2),
            eval!(context, combination_limb_3_col3),
            eval!(context, combination_limb_4_col4),
            eval!(context, combination_limb_5_col5),
            eval!(context, combination_limb_6_col6),
            eval!(context, combination_limb_7_col7),
            eval!(context, combination_limb_8_col8),
            eval!(context, combination_limb_9_col9),
            eval!(context, p_coef_col10),
        ],
        context,
        component_data,
        acc,
    );

    linear_combination_n_2_coefs_1_1::accumulate_constraints(
        &[
            eval!(context, poseidon_hades_permutation_input_limb_10),
            eval!(context, poseidon_hades_permutation_input_limb_11),
            eval!(context, poseidon_hades_permutation_input_limb_12),
            eval!(context, poseidon_hades_permutation_input_limb_13),
            eval!(context, poseidon_hades_permutation_input_limb_14),
            eval!(context, poseidon_hades_permutation_input_limb_15),
            eval!(context, poseidon_hades_permutation_input_limb_16),
            eval!(context, poseidon_hades_permutation_input_limb_17),
            eval!(context, poseidon_hades_permutation_input_limb_18),
            eval!(context, poseidon_hades_permutation_input_limb_19),
            eval!(context, 41224388),
            eval!(context, 90391646),
            eval!(context, 36279186),
            eval!(context, 129717753),
            eval!(context, 94624323),
            eval!(context, 75104388),
            eval!(context, 133303902),
            eval!(context, 48945103),
            eval!(context, 41320857),
            eval!(context, 112),
            eval!(context, combination_limb_0_col11),
            eval!(context, combination_limb_1_col12),
            eval!(context, combination_limb_2_col13),
            eval!(context, combination_limb_3_col14),
            eval!(context, combination_limb_4_col15),
            eval!(context, combination_limb_5_col16),
            eval!(context, combination_limb_6_col17),
            eval!(context, combination_limb_7_col18),
            eval!(context, combination_limb_8_col19),
            eval!(context, combination_limb_9_col20),
            eval!(context, p_coef_col21),
        ],
        context,
        component_data,
        acc,
    );

    linear_combination_n_2_coefs_1_1::accumulate_constraints(
        &[
            eval!(context, poseidon_hades_permutation_input_limb_20),
            eval!(context, poseidon_hades_permutation_input_limb_21),
            eval!(context, poseidon_hades_permutation_input_limb_22),
            eval!(context, poseidon_hades_permutation_input_limb_23),
            eval!(context, poseidon_hades_permutation_input_limb_24),
            eval!(context, poseidon_hades_permutation_input_limb_25),
            eval!(context, poseidon_hades_permutation_input_limb_26),
            eval!(context, poseidon_hades_permutation_input_limb_27),
            eval!(context, poseidon_hades_permutation_input_limb_28),
            eval!(context, poseidon_hades_permutation_input_limb_29),
            eval!(context, 4883209),
            eval!(context, 28820206),
            eval!(context, 79012328),
            eval!(context, 49157069),
            eval!(context, 78826183),
            eval!(context, 72285071),
            eval!(context, 33413160),
            eval!(context, 90842759),
            eval!(context, 60124463),
            eval!(context, 116),
            eval!(context, combination_limb_0_col22),
            eval!(context, combination_limb_1_col23),
            eval!(context, combination_limb_2_col24),
            eval!(context, combination_limb_3_col25),
            eval!(context, combination_limb_4_col26),
            eval!(context, combination_limb_5_col27),
            eval!(context, combination_limb_6_col28),
            eval!(context, combination_limb_7_col29),
            eval!(context, combination_limb_8_col30),
            eval!(context, combination_limb_9_col31),
            eval!(context, p_coef_col32),
        ],
        context,
        component_data,
        acc,
    );

    let poseidon_full_round_chain_chain_tmp_tmp_7d028_63 = eval!(context, (seq) * (2));

    // Yield PoseidonFullRoundChain.
    let tuple_4 = &[
        eval!(context, 1480369132),
        eval!(context, poseidon_full_round_chain_chain_tmp_tmp_7d028_63),
        eval!(context, 0),
        eval!(context, combination_limb_0_col0),
        eval!(context, combination_limb_1_col1),
        eval!(context, combination_limb_2_col2),
        eval!(context, combination_limb_3_col3),
        eval!(context, combination_limb_4_col4),
        eval!(context, combination_limb_5_col5),
        eval!(context, combination_limb_6_col6),
        eval!(context, combination_limb_7_col7),
        eval!(context, combination_limb_8_col8),
        eval!(context, combination_limb_9_col9),
        eval!(context, combination_limb_0_col11),
        eval!(context, combination_limb_1_col12),
        eval!(context, combination_limb_2_col13),
        eval!(context, combination_limb_3_col14),
        eval!(context, combination_limb_4_col15),
        eval!(context, combination_limb_5_col16),
        eval!(context, combination_limb_6_col17),
        eval!(context, combination_limb_7_col18),
        eval!(context, combination_limb_8_col19),
        eval!(context, combination_limb_9_col20),
        eval!(context, combination_limb_0_col22),
        eval!(context, combination_limb_1_col23),
        eval!(context, combination_limb_2_col24),
        eval!(context, combination_limb_3_col25),
        eval!(context, combination_limb_4_col26),
        eval!(context, combination_limb_5_col27),
        eval!(context, combination_limb_6_col28),
        eval!(context, combination_limb_7_col29),
        eval!(context, combination_limb_8_col30),
        eval!(context, combination_limb_9_col31),
    ];
    let numerator_4 = eval!(context, -(1));
    acc.add_to_relation(context, numerator_4, tuple_4);

    // Use PoseidonFullRoundChain.
    let tuple_5 = &[
        eval!(context, 1480369132),
        eval!(context, poseidon_full_round_chain_chain_tmp_tmp_7d028_63),
        eval!(context, 4),
        eval!(context, poseidon_full_round_chain_output_limb_0_col33),
        eval!(context, poseidon_full_round_chain_output_limb_1_col34),
        eval!(context, poseidon_full_round_chain_output_limb_2_col35),
        eval!(context, poseidon_full_round_chain_output_limb_3_col36),
        eval!(context, poseidon_full_round_chain_output_limb_4_col37),
        eval!(context, poseidon_full_round_chain_output_limb_5_col38),
        eval!(context, poseidon_full_round_chain_output_limb_6_col39),
        eval!(context, poseidon_full_round_chain_output_limb_7_col40),
        eval!(context, poseidon_full_round_chain_output_limb_8_col41),
        eval!(context, poseidon_full_round_chain_output_limb_9_col42),
        eval!(context, poseidon_full_round_chain_output_limb_10_col43),
        eval!(context, poseidon_full_round_chain_output_limb_11_col44),
        eval!(context, poseidon_full_round_chain_output_limb_12_col45),
        eval!(context, poseidon_full_round_chain_output_limb_13_col46),
        eval!(context, poseidon_full_round_chain_output_limb_14_col47),
        eval!(context, poseidon_full_round_chain_output_limb_15_col48),
        eval!(context, poseidon_full_round_chain_output_limb_16_col49),
        eval!(context, poseidon_full_round_chain_output_limb_17_col50),
        eval!(context, poseidon_full_round_chain_output_limb_18_col51),
        eval!(context, poseidon_full_round_chain_output_limb_19_col52),
        eval!(context, poseidon_full_round_chain_output_limb_20_col53),
        eval!(context, poseidon_full_round_chain_output_limb_21_col54),
        eval!(context, poseidon_full_round_chain_output_limb_22_col55),
        eval!(context, poseidon_full_round_chain_output_limb_23_col56),
        eval!(context, poseidon_full_round_chain_output_limb_24_col57),
        eval!(context, poseidon_full_round_chain_output_limb_25_col58),
        eval!(context, poseidon_full_round_chain_output_limb_26_col59),
        eval!(context, poseidon_full_round_chain_output_limb_27_col60),
        eval!(context, poseidon_full_round_chain_output_limb_28_col61),
        eval!(context, poseidon_full_round_chain_output_limb_29_col62),
    ];
    let numerator_5 = eval!(context, 1);
    acc.add_to_relation(context, numerator_5, tuple_5);

    // Use RangeCheck252Width27.
    let tuple_6 = &[
        eval!(context, 1090315331),
        eval!(context, poseidon_full_round_chain_output_limb_0_col33),
        eval!(context, poseidon_full_round_chain_output_limb_1_col34),
        eval!(context, poseidon_full_round_chain_output_limb_2_col35),
        eval!(context, poseidon_full_round_chain_output_limb_3_col36),
        eval!(context, poseidon_full_round_chain_output_limb_4_col37),
        eval!(context, poseidon_full_round_chain_output_limb_5_col38),
        eval!(context, poseidon_full_round_chain_output_limb_6_col39),
        eval!(context, poseidon_full_round_chain_output_limb_7_col40),
        eval!(context, poseidon_full_round_chain_output_limb_8_col41),
        eval!(context, poseidon_full_round_chain_output_limb_9_col42),
    ];
    let numerator_6 = eval!(context, 1);
    acc.add_to_relation(context, numerator_6, tuple_6);

    // Use RangeCheck252Width27.
    let tuple_7 = &[
        eval!(context, 1090315331),
        eval!(context, poseidon_full_round_chain_output_limb_10_col43),
        eval!(context, poseidon_full_round_chain_output_limb_11_col44),
        eval!(context, poseidon_full_round_chain_output_limb_12_col45),
        eval!(context, poseidon_full_round_chain_output_limb_13_col46),
        eval!(context, poseidon_full_round_chain_output_limb_14_col47),
        eval!(context, poseidon_full_round_chain_output_limb_15_col48),
        eval!(context, poseidon_full_round_chain_output_limb_16_col49),
        eval!(context, poseidon_full_round_chain_output_limb_17_col50),
        eval!(context, poseidon_full_round_chain_output_limb_18_col51),
        eval!(context, poseidon_full_round_chain_output_limb_19_col52),
    ];
    let numerator_7 = eval!(context, 1);
    acc.add_to_relation(context, numerator_7, tuple_7);

    // Use Cube252.
    let tuple_8 = &[
        eval!(context, 1987997202),
        eval!(context, poseidon_full_round_chain_output_limb_20_col53),
        eval!(context, poseidon_full_round_chain_output_limb_21_col54),
        eval!(context, poseidon_full_round_chain_output_limb_22_col55),
        eval!(context, poseidon_full_round_chain_output_limb_23_col56),
        eval!(context, poseidon_full_round_chain_output_limb_24_col57),
        eval!(context, poseidon_full_round_chain_output_limb_25_col58),
        eval!(context, poseidon_full_round_chain_output_limb_26_col59),
        eval!(context, poseidon_full_round_chain_output_limb_27_col60),
        eval!(context, poseidon_full_round_chain_output_limb_28_col61),
        eval!(context, poseidon_full_round_chain_output_limb_29_col62),
        eval!(context, cube_252_output_limb_0_col63),
        eval!(context, cube_252_output_limb_1_col64),
        eval!(context, cube_252_output_limb_2_col65),
        eval!(context, cube_252_output_limb_3_col66),
        eval!(context, cube_252_output_limb_4_col67),
        eval!(context, cube_252_output_limb_5_col68),
        eval!(context, cube_252_output_limb_6_col69),
        eval!(context, cube_252_output_limb_7_col70),
        eval!(context, cube_252_output_limb_8_col71),
        eval!(context, cube_252_output_limb_9_col72),
    ];
    let numerator_8 = eval!(context, 1);
    acc.add_to_relation(context, numerator_8, tuple_8);

    linear_combination_n_4_coefs_1_1_m2_1::accumulate_constraints(
        &[
            eval!(context, poseidon_full_round_chain_output_limb_0_col33),
            eval!(context, poseidon_full_round_chain_output_limb_1_col34),
            eval!(context, poseidon_full_round_chain_output_limb_2_col35),
            eval!(context, poseidon_full_round_chain_output_limb_3_col36),
            eval!(context, poseidon_full_round_chain_output_limb_4_col37),
            eval!(context, poseidon_full_round_chain_output_limb_5_col38),
            eval!(context, poseidon_full_round_chain_output_limb_6_col39),
            eval!(context, poseidon_full_round_chain_output_limb_7_col40),
            eval!(context, poseidon_full_round_chain_output_limb_8_col41),
            eval!(context, poseidon_full_round_chain_output_limb_9_col42),
            eval!(context, poseidon_full_round_chain_output_limb_10_col43),
            eval!(context, poseidon_full_round_chain_output_limb_11_col44),
            eval!(context, poseidon_full_round_chain_output_limb_12_col45),
            eval!(context, poseidon_full_round_chain_output_limb_13_col46),
            eval!(context, poseidon_full_round_chain_output_limb_14_col47),
            eval!(context, poseidon_full_round_chain_output_limb_15_col48),
            eval!(context, poseidon_full_round_chain_output_limb_16_col49),
            eval!(context, poseidon_full_round_chain_output_limb_17_col50),
            eval!(context, poseidon_full_round_chain_output_limb_18_col51),
            eval!(context, poseidon_full_round_chain_output_limb_19_col52),
            eval!(context, cube_252_output_limb_0_col63),
            eval!(context, cube_252_output_limb_1_col64),
            eval!(context, cube_252_output_limb_2_col65),
            eval!(context, cube_252_output_limb_3_col66),
            eval!(context, cube_252_output_limb_4_col67),
            eval!(context, cube_252_output_limb_5_col68),
            eval!(context, cube_252_output_limb_6_col69),
            eval!(context, cube_252_output_limb_7_col70),
            eval!(context, cube_252_output_limb_8_col71),
            eval!(context, cube_252_output_limb_9_col72),
            eval!(context, 103094260),
            eval!(context, 121146754),
            eval!(context, 95050340),
            eval!(context, 16173996),
            eval!(context, 50758155),
            eval!(context, 54415179),
            eval!(context, 19292069),
            eval!(context, 45351266),
            eval!(context, 122233508),
            eval!(context, 248),
            eval!(context, combination_limb_0_col73),
            eval!(context, combination_limb_1_col74),
            eval!(context, combination_limb_2_col75),
            eval!(context, combination_limb_3_col76),
            eval!(context, combination_limb_4_col77),
            eval!(context, combination_limb_5_col78),
            eval!(context, combination_limb_6_col79),
            eval!(context, combination_limb_7_col80),
            eval!(context, combination_limb_8_col81),
            eval!(context, combination_limb_9_col82),
            eval!(context, p_coef_col83),
        ],
        context,
        component_data,
        acc,
    );

    // Use Cube252.
    let tuple_10 = &[
        eval!(context, 1987997202),
        eval!(context, combination_limb_0_col73),
        eval!(context, combination_limb_1_col74),
        eval!(context, combination_limb_2_col75),
        eval!(context, combination_limb_3_col76),
        eval!(context, combination_limb_4_col77),
        eval!(context, combination_limb_5_col78),
        eval!(context, combination_limb_6_col79),
        eval!(context, combination_limb_7_col80),
        eval!(context, combination_limb_8_col81),
        eval!(context, combination_limb_9_col82),
        eval!(context, cube_252_output_limb_0_col84),
        eval!(context, cube_252_output_limb_1_col85),
        eval!(context, cube_252_output_limb_2_col86),
        eval!(context, cube_252_output_limb_3_col87),
        eval!(context, cube_252_output_limb_4_col88),
        eval!(context, cube_252_output_limb_5_col89),
        eval!(context, cube_252_output_limb_6_col90),
        eval!(context, cube_252_output_limb_7_col91),
        eval!(context, cube_252_output_limb_8_col92),
        eval!(context, cube_252_output_limb_9_col93),
    ];
    let numerator_10 = eval!(context, 1);
    acc.add_to_relation(context, numerator_10, tuple_10);

    linear_combination_n_4_coefs_4_2_m2_1::accumulate_constraints(
        &[
            eval!(context, poseidon_full_round_chain_output_limb_0_col33),
            eval!(context, poseidon_full_round_chain_output_limb_1_col34),
            eval!(context, poseidon_full_round_chain_output_limb_2_col35),
            eval!(context, poseidon_full_round_chain_output_limb_3_col36),
            eval!(context, poseidon_full_round_chain_output_limb_4_col37),
            eval!(context, poseidon_full_round_chain_output_limb_5_col38),
            eval!(context, poseidon_full_round_chain_output_limb_6_col39),
            eval!(context, poseidon_full_round_chain_output_limb_7_col40),
            eval!(context, poseidon_full_round_chain_output_limb_8_col41),
            eval!(context, poseidon_full_round_chain_output_limb_9_col42),
            eval!(context, cube_252_output_limb_0_col63),
            eval!(context, cube_252_output_limb_1_col64),
            eval!(context, cube_252_output_limb_2_col65),
            eval!(context, cube_252_output_limb_3_col66),
            eval!(context, cube_252_output_limb_4_col67),
            eval!(context, cube_252_output_limb_5_col68),
            eval!(context, cube_252_output_limb_6_col69),
            eval!(context, cube_252_output_limb_7_col70),
            eval!(context, cube_252_output_limb_8_col71),
            eval!(context, cube_252_output_limb_9_col72),
            eval!(context, cube_252_output_limb_0_col84),
            eval!(context, cube_252_output_limb_1_col85),
            eval!(context, cube_252_output_limb_2_col86),
            eval!(context, cube_252_output_limb_3_col87),
            eval!(context, cube_252_output_limb_4_col88),
            eval!(context, cube_252_output_limb_5_col89),
            eval!(context, cube_252_output_limb_6_col90),
            eval!(context, cube_252_output_limb_7_col91),
            eval!(context, cube_252_output_limb_8_col92),
            eval!(context, cube_252_output_limb_9_col93),
            eval!(context, 121657377),
            eval!(context, 112479959),
            eval!(context, 130418270),
            eval!(context, 4974792),
            eval!(context, 59852719),
            eval!(context, 120369218),
            eval!(context, 62439890),
            eval!(context, 50468641),
            eval!(context, 86573645),
            eval!(context, 154),
            eval!(context, combination_limb_0_col94),
            eval!(context, combination_limb_1_col95),
            eval!(context, combination_limb_2_col96),
            eval!(context, combination_limb_3_col97),
            eval!(context, combination_limb_4_col98),
            eval!(context, combination_limb_5_col99),
            eval!(context, combination_limb_6_col100),
            eval!(context, combination_limb_7_col101),
            eval!(context, combination_limb_8_col102),
            eval!(context, combination_limb_9_col103),
            eval!(context, p_coef_col104),
        ],
        context,
        component_data,
        acc,
    );

    // Yield Poseidon3PartialRoundsChain.
    let tuple_12 = &[
        eval!(context, 1343313504),
        eval!(context, seq),
        eval!(context, 4),
        eval!(context, cube_252_output_limb_0_col63),
        eval!(context, cube_252_output_limb_1_col64),
        eval!(context, cube_252_output_limb_2_col65),
        eval!(context, cube_252_output_limb_3_col66),
        eval!(context, cube_252_output_limb_4_col67),
        eval!(context, cube_252_output_limb_5_col68),
        eval!(context, cube_252_output_limb_6_col69),
        eval!(context, cube_252_output_limb_7_col70),
        eval!(context, cube_252_output_limb_8_col71),
        eval!(context, cube_252_output_limb_9_col72),
        eval!(context, combination_limb_0_col73),
        eval!(context, combination_limb_1_col74),
        eval!(context, combination_limb_2_col75),
        eval!(context, combination_limb_3_col76),
        eval!(context, combination_limb_4_col77),
        eval!(context, combination_limb_5_col78),
        eval!(context, combination_limb_6_col79),
        eval!(context, combination_limb_7_col80),
        eval!(context, combination_limb_8_col81),
        eval!(context, combination_limb_9_col82),
        eval!(context, cube_252_output_limb_0_col84),
        eval!(context, cube_252_output_limb_1_col85),
        eval!(context, cube_252_output_limb_2_col86),
        eval!(context, cube_252_output_limb_3_col87),
        eval!(context, cube_252_output_limb_4_col88),
        eval!(context, cube_252_output_limb_5_col89),
        eval!(context, cube_252_output_limb_6_col90),
        eval!(context, cube_252_output_limb_7_col91),
        eval!(context, cube_252_output_limb_8_col92),
        eval!(context, cube_252_output_limb_9_col93),
        eval!(context, combination_limb_0_col94),
        eval!(context, combination_limb_1_col95),
        eval!(context, combination_limb_2_col96),
        eval!(context, combination_limb_3_col97),
        eval!(context, combination_limb_4_col98),
        eval!(context, combination_limb_5_col99),
        eval!(context, combination_limb_6_col100),
        eval!(context, combination_limb_7_col101),
        eval!(context, combination_limb_8_col102),
        eval!(context, combination_limb_9_col103),
    ];
    let numerator_12 = eval!(context, -(1));
    acc.add_to_relation(context, numerator_12, tuple_12);

    // Use Poseidon3PartialRoundsChain.
    let tuple_13 = &[
        eval!(context, 1343313504),
        eval!(context, seq),
        eval!(context, 31),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_0_col105),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_1_col106),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_2_col107),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_3_col108),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_4_col109),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_5_col110),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_6_col111),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_7_col112),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_8_col113),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_9_col114),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_10_col115),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_11_col116),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_12_col117),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_13_col118),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_14_col119),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_15_col120),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_16_col121),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_17_col122),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_18_col123),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_19_col124),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_20_col125),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_21_col126),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_22_col127),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_23_col128),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_24_col129),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_25_col130),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_26_col131),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_27_col132),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_28_col133),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_29_col134),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_30_col135),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_31_col136),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_32_col137),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_33_col138),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_34_col139),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_35_col140),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_36_col141),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_37_col142),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_38_col143),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_39_col144),
    ];
    let numerator_13 = eval!(context, 1);
    acc.add_to_relation(context, numerator_13, tuple_13);

    linear_combination_n_4_coefs_4_2_1_1::accumulate_constraints(
        &[
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_0_col105),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_1_col106),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_2_col107),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_3_col108),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_4_col109),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_5_col110),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_6_col111),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_7_col112),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_8_col113),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_9_col114),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_10_col115),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_11_col116),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_12_col117),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_13_col118),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_14_col119),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_15_col120),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_16_col121),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_17_col122),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_18_col123),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_19_col124),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_20_col125),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_21_col126),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_22_col127),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_23_col128),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_24_col129),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_25_col130),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_26_col131),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_27_col132),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_28_col133),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_29_col134),
            eval!(context, 40454143),
            eval!(context, 49554771),
            eval!(context, 55508188),
            eval!(context, 116986206),
            eval!(context, 88680813),
            eval!(context, 45553283),
            eval!(context, 62360091),
            eval!(context, 77099918),
            eval!(context, 22899501),
            eval!(context, 99),
            eval!(context, combination_limb_0_col145),
            eval!(context, combination_limb_1_col146),
            eval!(context, combination_limb_2_col147),
            eval!(context, combination_limb_3_col148),
            eval!(context, combination_limb_4_col149),
            eval!(context, combination_limb_5_col150),
            eval!(context, combination_limb_6_col151),
            eval!(context, combination_limb_7_col152),
            eval!(context, combination_limb_8_col153),
            eval!(context, combination_limb_9_col154),
            eval!(context, p_coef_col155),
        ],
        context,
        component_data,
        acc,
    );

    linear_combination_n_4_coefs_4_2_1_1::accumulate_constraints(
        &[
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_20_col125),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_21_col126),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_22_col127),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_23_col128),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_24_col129),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_25_col130),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_26_col131),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_27_col132),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_28_col133),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_29_col134),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_30_col135),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_31_col136),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_32_col137),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_33_col138),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_34_col139),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_35_col140),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_36_col141),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_37_col142),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_38_col143),
            eval!(context, poseidon_3_partial_rounds_chain_output_limb_39_col144),
            eval!(context, combination_limb_0_col145),
            eval!(context, combination_limb_1_col146),
            eval!(context, combination_limb_2_col147),
            eval!(context, combination_limb_3_col148),
            eval!(context, combination_limb_4_col149),
            eval!(context, combination_limb_5_col150),
            eval!(context, combination_limb_6_col151),
            eval!(context, combination_limb_7_col152),
            eval!(context, combination_limb_8_col153),
            eval!(context, combination_limb_9_col154),
            eval!(context, 48383197),
            eval!(context, 48193339),
            eval!(context, 55955004),
            eval!(context, 65659846),
            eval!(context, 68491350),
            eval!(context, 119023582),
            eval!(context, 33439011),
            eval!(context, 58475513),
            eval!(context, 18765944),
            eval!(context, 20),
            eval!(context, combination_limb_0_col156),
            eval!(context, combination_limb_1_col157),
            eval!(context, combination_limb_2_col158),
            eval!(context, combination_limb_3_col159),
            eval!(context, combination_limb_4_col160),
            eval!(context, combination_limb_5_col161),
            eval!(context, combination_limb_6_col162),
            eval!(context, combination_limb_7_col163),
            eval!(context, combination_limb_8_col164),
            eval!(context, combination_limb_9_col165),
            eval!(context, p_coef_col166),
        ],
        context,
        component_data,
        acc,
    );

    let poseidon_full_round_chain_chain_id_tmp_7d028_146 =
        eval!(context, (poseidon_full_round_chain_chain_tmp_tmp_7d028_63) + (1));

    // Yield PoseidonFullRoundChain.
    let tuple_17 = &[
        eval!(context, 1480369132),
        eval!(context, poseidon_full_round_chain_chain_id_tmp_7d028_146),
        eval!(context, 31),
        eval!(context, combination_limb_0_col156),
        eval!(context, combination_limb_1_col157),
        eval!(context, combination_limb_2_col158),
        eval!(context, combination_limb_3_col159),
        eval!(context, combination_limb_4_col160),
        eval!(context, combination_limb_5_col161),
        eval!(context, combination_limb_6_col162),
        eval!(context, combination_limb_7_col163),
        eval!(context, combination_limb_8_col164),
        eval!(context, combination_limb_9_col165),
        eval!(context, combination_limb_0_col145),
        eval!(context, combination_limb_1_col146),
        eval!(context, combination_limb_2_col147),
        eval!(context, combination_limb_3_col148),
        eval!(context, combination_limb_4_col149),
        eval!(context, combination_limb_5_col150),
        eval!(context, combination_limb_6_col151),
        eval!(context, combination_limb_7_col152),
        eval!(context, combination_limb_8_col153),
        eval!(context, combination_limb_9_col154),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_30_col135),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_31_col136),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_32_col137),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_33_col138),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_34_col139),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_35_col140),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_36_col141),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_37_col142),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_38_col143),
        eval!(context, poseidon_3_partial_rounds_chain_output_limb_39_col144),
    ];
    let numerator_17 = eval!(context, -(1));
    acc.add_to_relation(context, numerator_17, tuple_17);

    // Use PoseidonFullRoundChain.
    let tuple_18 = &[
        eval!(context, 1480369132),
        eval!(context, poseidon_full_round_chain_chain_id_tmp_7d028_146),
        eval!(context, 35),
        eval!(context, poseidon_full_round_chain_output_limb_0_col167),
        eval!(context, poseidon_full_round_chain_output_limb_1_col168),
        eval!(context, poseidon_full_round_chain_output_limb_2_col169),
        eval!(context, poseidon_full_round_chain_output_limb_3_col170),
        eval!(context, poseidon_full_round_chain_output_limb_4_col171),
        eval!(context, poseidon_full_round_chain_output_limb_5_col172),
        eval!(context, poseidon_full_round_chain_output_limb_6_col173),
        eval!(context, poseidon_full_round_chain_output_limb_7_col174),
        eval!(context, poseidon_full_round_chain_output_limb_8_col175),
        eval!(context, poseidon_full_round_chain_output_limb_9_col176),
        eval!(context, poseidon_full_round_chain_output_limb_10_col177),
        eval!(context, poseidon_full_round_chain_output_limb_11_col178),
        eval!(context, poseidon_full_round_chain_output_limb_12_col179),
        eval!(context, poseidon_full_round_chain_output_limb_13_col180),
        eval!(context, poseidon_full_round_chain_output_limb_14_col181),
        eval!(context, poseidon_full_round_chain_output_limb_15_col182),
        eval!(context, poseidon_full_round_chain_output_limb_16_col183),
        eval!(context, poseidon_full_round_chain_output_limb_17_col184),
        eval!(context, poseidon_full_round_chain_output_limb_18_col185),
        eval!(context, poseidon_full_round_chain_output_limb_19_col186),
        eval!(context, poseidon_full_round_chain_output_limb_20_col187),
        eval!(context, poseidon_full_round_chain_output_limb_21_col188),
        eval!(context, poseidon_full_round_chain_output_limb_22_col189),
        eval!(context, poseidon_full_round_chain_output_limb_23_col190),
        eval!(context, poseidon_full_round_chain_output_limb_24_col191),
        eval!(context, poseidon_full_round_chain_output_limb_25_col192),
        eval!(context, poseidon_full_round_chain_output_limb_26_col193),
        eval!(context, poseidon_full_round_chain_output_limb_27_col194),
        eval!(context, poseidon_full_round_chain_output_limb_28_col195),
        eval!(context, poseidon_full_round_chain_output_limb_29_col196),
    ];
    let numerator_18 = eval!(context, 1);
    acc.add_to_relation(context, numerator_18, tuple_18);
    vec![]
}
