pub const MAX_SEQUENCE_LOG_SIZE: usize = 20;

pub const PREPROCESSED_COLUMNS_ORDER: [&str; 156] = [
    "seq_4",
    "blake_sigma_0",
    "blake_sigma_1",
    "blake_sigma_2",
    "blake_sigma_3",
    "blake_sigma_4",
    "blake_sigma_5",
    "blake_sigma_6",
    "blake_sigma_7",
    "blake_sigma_8",
    "blake_sigma_9",
    "blake_sigma_10",
    "blake_sigma_11",
    "blake_sigma_12",
    "blake_sigma_13",
    "blake_sigma_14",
    "blake_sigma_15",
    "seq_5",
    "seq_6",
    "poseidon_round_keys_0",
    "poseidon_round_keys_1",
    "poseidon_round_keys_2",
    "poseidon_round_keys_3",
    "poseidon_round_keys_4",
    "poseidon_round_keys_5",
    "poseidon_round_keys_6",
    "poseidon_round_keys_7",
    "poseidon_round_keys_8",
    "poseidon_round_keys_9",
    "poseidon_round_keys_10",
    "poseidon_round_keys_11",
    "poseidon_round_keys_12",
    "poseidon_round_keys_13",
    "poseidon_round_keys_14",
    "poseidon_round_keys_15",
    "poseidon_round_keys_16",
    "poseidon_round_keys_17",
    "poseidon_round_keys_18",
    "poseidon_round_keys_19",
    "poseidon_round_keys_20",
    "poseidon_round_keys_21",
    "poseidon_round_keys_22",
    "poseidon_round_keys_23",
    "poseidon_round_keys_24",
    "poseidon_round_keys_25",
    "poseidon_round_keys_26",
    "poseidon_round_keys_27",
    "poseidon_round_keys_28",
    "poseidon_round_keys_29",
    "seq_7",
    "range_check_4_3_column_0",
    "range_check_4_3_column_1",
    "seq_8",
    "bitwise_xor_4_0",
    "bitwise_xor_4_1",
    "bitwise_xor_4_2",
    "range_check_4_4_column_0",
    "range_check_4_4_column_1",
    "seq_9",
    "seq_10",
    "seq_11",
    "seq_12",
    "seq_13",
    "seq_14",
    "bitwise_xor_7_0",
    "bitwise_xor_7_1",
    "bitwise_xor_7_2",
    "range_check_7_2_5_column_0",
    "range_check_7_2_5_column_1",
    "range_check_7_2_5_column_2",
    "seq_15",
    "range_check_3_3_3_3_3_column_0",
    "range_check_3_3_3_3_3_column_1",
    "range_check_3_3_3_3_3_column_2",
    "range_check_3_3_3_3_3_column_3",
    "range_check_3_3_3_3_3_column_4",
    "pedersen_points_small_0",
    "pedersen_points_small_1",
    "pedersen_points_small_2",
    "pedersen_points_small_3",
    "pedersen_points_small_4",
    "pedersen_points_small_5",
    "pedersen_points_small_6",
    "pedersen_points_small_7",
    "pedersen_points_small_8",
    "pedersen_points_small_9",
    "pedersen_points_small_10",
    "pedersen_points_small_11",
    "pedersen_points_small_12",
    "pedersen_points_small_13",
    "pedersen_points_small_14",
    "pedersen_points_small_15",
    "pedersen_points_small_16",
    "pedersen_points_small_17",
    "pedersen_points_small_18",
    "pedersen_points_small_19",
    "pedersen_points_small_20",
    "pedersen_points_small_21",
    "pedersen_points_small_22",
    "pedersen_points_small_23",
    "pedersen_points_small_24",
    "pedersen_points_small_25",
    "pedersen_points_small_26",
    "pedersen_points_small_27",
    "pedersen_points_small_28",
    "pedersen_points_small_29",
    "pedersen_points_small_30",
    "pedersen_points_small_31",
    "pedersen_points_small_32",
    "pedersen_points_small_33",
    "pedersen_points_small_34",
    "pedersen_points_small_35",
    "pedersen_points_small_36",
    "pedersen_points_small_37",
    "pedersen_points_small_38",
    "pedersen_points_small_39",
    "pedersen_points_small_40",
    "pedersen_points_small_41",
    "pedersen_points_small_42",
    "pedersen_points_small_43",
    "pedersen_points_small_44",
    "pedersen_points_small_45",
    "pedersen_points_small_46",
    "pedersen_points_small_47",
    "pedersen_points_small_48",
    "pedersen_points_small_49",
    "pedersen_points_small_50",
    "pedersen_points_small_51",
    "pedersen_points_small_52",
    "pedersen_points_small_53",
    "pedersen_points_small_54",
    "pedersen_points_small_55",
    "seq_16",
    "bitwise_xor_8_0",
    "bitwise_xor_8_1",
    "bitwise_xor_8_2",
    "range_check_4_4_4_4_column_0",
    "range_check_4_4_4_4_column_1",
    "range_check_4_4_4_4_column_2",
    "range_check_4_4_4_4_column_3",
    "seq_17",
    "seq_18",
    "bitwise_xor_9_0",
    "bitwise_xor_9_1",
    "bitwise_xor_9_2",
    "range_check_9_9_column_0",
    "range_check_9_9_column_1",
    "range_check_3_6_6_3_column_0",
    "range_check_3_6_6_3_column_1",
    "range_check_3_6_6_3_column_2",
    "range_check_3_6_6_3_column_3",
    "seq_19",
    "seq_20",
    "bitwise_xor_10_0",
    "bitwise_xor_10_1",
    "bitwise_xor_10_2",
    // "seq_21",
    // "seq_22",
    // "seq_23",
    // "pedersen_points_0",
    // "pedersen_points_1",
    // "pedersen_points_2",
    // "pedersen_points_3",
    // "pedersen_points_4",
    // "pedersen_points_5",
    // "pedersen_points_6",
    // "pedersen_points_7",
    // "pedersen_points_8",
    // "pedersen_points_9",
    // "pedersen_points_10",
    // "pedersen_points_11",
    // "pedersen_points_12",
    // "pedersen_points_13",
    // "pedersen_points_14",
    // "pedersen_points_15",
    // "pedersen_points_16",
    // "pedersen_points_17",
    // "pedersen_points_18",
    // "pedersen_points_19",
    // "pedersen_points_20",
    // "pedersen_points_21",
    // "pedersen_points_22",
    // "pedersen_points_23",
    // "pedersen_points_24",
    // "pedersen_points_25",
    // "pedersen_points_26",
    // "pedersen_points_27",
    // "pedersen_points_28",
    // "pedersen_points_29",
    // "pedersen_points_30",
    // "pedersen_points_31",
    // "pedersen_points_32",
    // "pedersen_points_33",
    // "pedersen_points_34",
    // "pedersen_points_35",
    // "pedersen_points_36",
    // "pedersen_points_37",
    // "pedersen_points_38",
    // "pedersen_points_39",
    // "pedersen_points_40",
    // "pedersen_points_41",
    // "pedersen_points_42",
    // "pedersen_points_43",
    // "pedersen_points_44",
    // "pedersen_points_45",
    // "pedersen_points_46",
    // "pedersen_points_47",
    // "pedersen_points_48",
    // "pedersen_points_49",
    // "pedersen_points_50",
    // "pedersen_points_51",
    // "pedersen_points_52",
    // "pedersen_points_53",
    // "pedersen_points_54",
    // "pedersen_points_55",
    // "seq_24",
    // "seq_25",
];
